export const libro02 = [
  { id: "hz000801", palabra: "运动", pinyin: "yu4n do4ng", significado: "deporte" },
  { id: "hz000802", palabra: "足球", pinyin: "zu2 qiu2", significado: "fútbol" },
  { id: "hz000803", palabra: "踢", pinyin: "ti1", significado: "jugar, patear" },
  { id: "hz000804", palabra: "可", pinyin: "ke3", significado: "sumamente" },
  { id: "hz000805", palabra: "多", pinyin: "duo1", significado: "mucho" },
  { id: "hz000806", palabra: "网球", pinyin: "wa3ng qiu2", significado: "tenis" },
  { id: "hz000807", palabra: "游泳", pinyin: "yo2u yo3ng", significado: "nadar" },
  { id: "hz000808", palabra: "滑冰", pinyin: "hua2 bi1ng", significado: "patinar" },
  { id: "hz000809", palabra: "以后", pinyin: "yi3 ho4u", significado: "en adelante" },
  { id: "hz000810", palabra: "会", pinyin: "hui4", significado: "saber" },
  { id: "hz000811", palabra: "只", pinyin: "zhi3", significado: "sólo" },
  { id: "hz000812", palabra: "游", pinyin: "yo2u", significado: "nadar" },
  { id: "hz000813", palabra: "愿意", pinyin: "yua4n yi4", significado: "querer" },
  { id: "hz000814", palabra: "当", pinyin: "da1ng", significado: "ser" },
  { id: "hz000815", palabra: "教练", pinyin: "jia4o lia4n", significado: "entrenador" },
  { id: "hz000816", palabra: "排球", pinyin: "pa2i qiu2", significado: "voleibol" },
  { id: "hz000817", palabra: "篮球", pinyin: "la2n qiu2", significado: "baloncesto" },
  { id: "hz000818", palabra: "乒乓球", pinyin: "pi1ng pa1ng qui2", significado: "tenis de mesa" },
  { id: "hz000819", palabra: "体操", pinyin: "ti3 ca1o", significado: "gimnasia" },
  { id: "hz000820", palabra: "流利", pinyin: "liu2 li4", significado: "fluido" },
  { id: "hz000821", palabra: "整齐", pinyin: "zhe3ng qi2", significado: "ordenado" },
  { id: "hz000822", palabra: "旅行", pinyin: "lv3 xi2ng", significado: "viajar" },
  { id: "hz000823", palabra: "见面", pinyin: "jia4n mia4n", significado: "entrevistarse" },
  { id: "hz000824", palabra: "健康", pinyin: "jia4n ka1ng", significado: "sano" },
  { id: "hz000825", palabra: "活动", pinyin: "huo2 do4ng", significado: "actividad" },
  { id: "hz000826", palabra: "以前", pinyin: "yi3 qia2n", significado: "antes" },
  { id: "hz000827", palabra: "过", pinyin: "guo0", significado: "alguna vez" },
  { id: "hz000828", palabra: "听说", pinyin: "ti1ng shu1o", significado: "haber oído decir" },
  { id: "hz000829", palabra: "有名", pinyin: "yo3u mi2ng", significado: "famoso" },
  { id: "hz000830", palabra: "烤鸭", pinyin: "ka3o ya1", significado: "pato laqueado" },
  { id: "hz000831", palabra: "店", pinyin: "dia4n", significado: "restaurante" },
  { id: "hz000832", palabra: "已经", pinyin: "yi3 ji1ng", significado: "ya" },
  { id: "hz000833", palabra: "历史", pinyin: "li4 shi3", significado: "historia" },
  { id: "hz000834", palabra: "座位", pinyin: "zuo4 we4i", significado: "asiento" },
  { id: "hz000835", palabra: "提前", pinyin: "ti2 qia2n", significado: "previamente" },
  { id: "hz000836", palabra: "预订", pinyin: "yu4 di4ng", significado: "reservar" },
  { id: "hz000837", palabra: "几", pinyin: "ji3", significado: "varios" },
  { id: "hz000838", palabra: "今天", pinyin: "ji1n tia1n", significado: "hoy" },
  { id: "hz000839", palabra: "请客", pinyin: "qi3ng ke4", significado: "invitar" },
  { id: "hz000840", palabra: "点菜", pinyin: "dia3n ca4i", significado: "pedir de comer" },
  { id: "hz000841", palabra: "要", pinyin: "ya4o", significado: "querer" },
  { id: "hz000842", palabra: "啤酒", pinyin: "pi2 jiu3", significado: "cerveza" },
  { id: "hz000843", palabra: "杯", pinyin: "be1i", significado: "vaso" },
  { id: "hz000844", palabra: "矿泉水", pinyin: "kua4ng qua2n shui3", significado: "agua mineral" },
  { id: "hz000845", palabra: "只", pinyin: "zhi1", significado: "clasif. Animales" },
  { id: "hz000846", palabra: "瓶", pinyin: "pi2ng", significado: "botella" },
  { id: "hz000847", palabra: "全聚德", pinyin: "qua2n ju4 de2", significado: "Quanjude" },
  {
    id: "hz000848",
    palabra: "松鼠鳜鱼",
    pinyin: "so1ng shu2 gui4 yu2",
    significado: "pescado-ardilla",
  },
  { id: "hz000849", palabra: "西兰花", pinyin: "xi1 la2n hua1", significado: "brócoli" },
  { id: "hz000850", palabra: "葡萄酒", pinyin: "pu2 ta2o jiu3", significado: "vino" },
  { id: "hz000851", palabra: "白酒", pinyin: "ba2i jiu3", significado: "licor" },
  { id: "hz000852", palabra: "青菜", pinyin: "qi1ng ca4i", significado: "verduras, legumbres" },
  { id: "hz000853", palabra: "荤菜", pinyin: "hu1n ca4i", significado: "platos de carne" },
  { id: "hz000854", palabra: "蔬菜", pinyin: "shu1 c4ai", significado: "legumbres, hortalizas" },
  { id: "hz000855", palabra: "杯子", pinyin: "be1i zi0", significado: "vaso" },
  { id: "hz000856", palabra: "饱", pinyin: "ba3o", significado: "lleno" },
  { id: "hz000857", palabra: "鸡蛋", pinyin: "ji1 da4n", significado: "huevo (de gallina)" },
  { id: "hz000858", palabra: "酒", pinyin: "jiu4", significado: "bebidas alcohólicas" },
  { id: "hz000859", palabra: "图书馆", pinyin: "tu2 shu1 gua3n", significado: "biblioteca" },
  { id: "hz000860", palabra: "找", pinyin: "zha3o", significado: "buscar" },
  { id: "hz000861", palabra: "报", pinyin: "ba3o", significado: "periódico" },
  { id: "hz000862", palabra: "招聘", pinyin: "zha1 pi4n", significado: "solictar (trabajo)" },
  { id: "hz000863", palabra: "广告", pinyin: "gua3ng ga3o", significado: "anuncio" },
  { id: "hz000864", palabra: "公司", pinyin: "go1ng si1", significado: "compañía" },
  { id: "hz000865", palabra: "需要", pinyin: "xu1 ya4o", significado: "necesitar" },
  { id: "hz000866", palabra: "懂", pinyin: "do3ng", significado: "entender" },
  { id: "hz000867", palabra: "听", pinyin: "ti1ng", significado: "escuchar" },
  { id: "hz000868", palabra: "广播", pinyin: "gua3ng bo1", significado: "radiodifusión" },
  { id: "hz000869", palabra: "简历", pinyin: "jia3n li4", significado: "curriculum vitae" },
  { id: "hz000870", palabra: "准备", pinyin: "zhu3n be4i", significado: "preparar" },
  { id: "hz000871", palabra: "经理", pinyin: "ji1ng li3", significado: "genrente" },
  { id: "hz000872", palabra: "先", pinyin: "xia1n", significado: "antes que nada" },
  { id: "hz000873", palabra: "面试", pinyin: "mia4n shi4", significado: "entrevistar" },
  { id: "hz000874", palabra: "一下", pinyin: "yi2 xia4", significado: "una vez" },
  { id: "hz000875", palabra: "中文", pinyin: "zho1ng we2n", significado: "lengua china" },
  { id: "hz000876", palabra: "杂志", pinyin: "za2 zhi4", significado: "revista" },
  { id: "hz000877", palabra: "小说", pinyin: "xia3o shuo1", significado: "novela" },
  { id: "hz000878", palabra: "画报", pinyin: "hua4 ba4o", significado: "revista ilustrada" },
  { id: "hz000879", palabra: "电视", pinyin: "dia4n shi4", significado: "televisión" },
  { id: "hz000880", palabra: "笔试", pinyin: "bi3 shi4", significado: "examen escrito" },
  { id: "hz000881", palabra: "口试", pinyin: "ko3 shi4", significado: "examen oral" },
  { id: "hz000882", palabra: "考试", pinyin: "ka3o shi4", significado: "examen, examinar" },
  { id: "hz000883", palabra: "考", pinyin: "ka3o", significado: "examinar" },
  { id: "hz000884", palabra: "成绩", pinyin: "che2ng ji4", significado: "éxito, resultado" },
  { id: "hz000885", palabra: "翻译", pinyin: "fa1n yi4", significado: "traducir, traducción" },
  { id: "hz000886", palabra: "词典", pinyin: "ci2 dia3n", significado: "diccionario" },
  { id: "hz000887", palabra: "辅导", pinyin: "fu3 da3o", significado: "atender (consultas)" },
  { id: "hz000888", palabra: "复习", pinyin: "fu4 xi2", significado: "repasar" },
  { id: "hz000889", palabra: "多", pinyin: "duo1", significado: "¿cuánto?" },
  { id: "hz000890", palabra: "长", pinyin: "cha2ng", significado: "largo" },
  { id: "hz000891", palabra: "谈话", pinyin: "ta2n hua4", significado: "conversar" },
  { id: "hz000892", palabra: "用", pinyin: "yo4ng", significado: "usar" },
  { id: "hz000893", palabra: "硬件", pinyin: "yi4ng jia4n", significado: "hardware" },
  { id: "hz000894", palabra: "软件", pinyin: "rua3n jia4n", significado: "software" },
  { id: "hz000895", palabra: "大学", pinyin: "da4 xue2", significado: "universidad" },
  { id: "hz000896", palabra: "毕业", pinyin: "bi4 ye4", significado: "graduarse" },
  { id: "hz000897", palabra: "计算机", pinyin: "ji4 sua4n ji1", significado: "ordenador" },
  { id: "hz000898", palabra: "专业", pinyin: "zhua1n ye4", significado: "carrera" },
  { id: "hz000899", palabra: "秘书", pinyin: "mi4 shu1", significado: "secretario" },
  { id: "hz000900", palabra: "合同", pinyin: "he2 tong0", significado: "contrato" },
  { id: "hz000901", palabra: "同意", pinyin: "to2ng yi4", significado: "estar de acuerdo" },
  { id: "hz000902", palabra: "通知", pinyin: "to1ng zhi1", significado: "aviso, avisar" },
  { id: "hz000903", palabra: "职员", pinyin: "zhi2 yua2n", significado: "empleado" },
  { id: "hz000904", palabra: "英文", pinyin: "yi1ng we2n", significado: "lengua inglesa" },
  { id: "hz000905", palabra: "美国", pinyin: "me3i guo2", significado: "EEUU" },
  { id: "hz000906", palabra: "小时", pinyin: "xia3o shi2", significado: "hora" },
  { id: "hz000907", palabra: "服务", pinyin: "fu2 wu4", significado: "servir" },
  { id: "hz000908", palabra: "接着", pinyin: "jie1 zhe0", significado: "continuar" },
  { id: "hz000909", palabra: "继续", pinyin: "ji4 xu4", significado: "seguir" },
  { id: "hz000910", palabra: "技术", pinyin: "ji4 shu4", significado: "técnica" },
  { id: "hz000911", palabra: "计划", pinyin: "ji4 hua4", significado: "plan" },
  { id: "hz000912", palabra: "教育", pinyin: "jia4o yu4", significado: "educar" },
  { id: "hz000913", palabra: "解决", pinyin: "jie3 jue2", significado: "solucionar" },
  { id: "hz000914", palabra: "经济", pinyin: "ji1ng ji4", significado: "economía" },
  { id: "hz000915", palabra: "科学", pinyin: "ke1 xue2", significado: "ciencia" },
  { id: "hz000916", palabra: "饭店", pinyin: "fa4n dia4n", significado: "hotel" },
  { id: "hz000917", palabra: "房间", pinyin: "fa3ng jia1n", significado: "habitación" },
  {
    id: "hz000918",
    palabra: "标准间",
    pinyin: "bia1o zhu3n jia1n",
    significado: "habitación estándar",
  },
  {
    id: "hz000919",
    palabra: "豪华间",
    pinyin: "ha2o hua2 ji1an",
    significado: "habitación de lujo",
  },
  { id: "hz000920", palabra: "住", pinyin: "zhu4", significado: "ocupar, usar" },
  { id: "hz000921", palabra: "离", pinyin: "li2", significado: "de" },
  { id: "hz000922", palabra: "机场", pinyin: "ji1 cha3ng", significado: "aeropuerto" },
  { id: "hz000923", palabra: "远", pinyin: "yua3n", significado: "lejano, lejos" },
  { id: "hz000924", palabra: "从 . . 到", pinyin: "co2ng 0 0 da4o", significado: "desde .. hasta" },
  { id: "hz000925", palabra: "公里", pinyin: "go1ng li3", significado: "kilómetro" },
  { id: "hz000926", palabra: "市中心", pinyin: "shi4 zho1n xi1n", significado: "centro urbano" },
  { id: "hz000927", palabra: "步行", pinyin: "bu4 xi2ng", significado: "caminar" },
  { id: "hz000928", palabra: "分钟", pinyin: "fe1n zho1ng", significado: "minuto" },
  { id: "hz000929", palabra: "左右", pinyin: "zuo3 yo4u", significado: "aproximadamente" },
  { id: "hz000930", palabra: "安排", pinyin: "a1n pa2i", significado: "arreglar" },
  { id: "hz000931", palabra: "发", pinyin: "fa1", significado: "enviar" },
  { id: "hz000932", palabra: "传真", pinyin: "chua2n zhe1n", significado: "fax" },
  { id: "hz000933", palabra: "西安", pinyin: "xi1 a1n", significado: "Xian" },
  { id: "hz000934", palabra: "开", pinyin: "ka1i", significado: "conducir" },
  { id: "hz000935", palabra: "车", pinyin: "che1", significado: "vehículo" },
  { id: "hz000936", palabra: "去年", pinyin: "qu4 nia2n", significado: "el año pasado" },
  { id: "hz000937", palabra: "套间", pinyin: "ta4o jia1n", significado: "apartamento" },
  { id: "hz000938", palabra: "办理", pinyin: "ba4n li3", significado: "arreglar, tramitar" },
  { id: "hz000939", palabra: "车站", pinyin: "che1 zha4n", significado: "estación de vehículos" },
  { id: "hz000940", palabra: "出租汽车", pinyin: "chu1 zu1 qi4 che1", significado: "taxi" },
  { id: "hz000941", palabra: "电车", pinyin: "dia4n che1", significado: "tranvía" },
  { id: "hz000942", palabra: "成", pinyin: "che2ng", significado: "ciudad" },
  { id: "hz000943", palabra: "出发", pinyin: "chu1 fa1", significado: "partir" },
  { id: "hz000944", palabra: "方向", pinyin: "fa1ng xia4ng", significado: "dirección" },
  { id: "hz000945", palabra: "照片", pinyin: "zha4o pia4n", significado: "foto" },
  { id: "hz000946", palabra: "照", pinyin: "zha4o", significado: "sacar, tomar" },
  { id: "hz000947", palabra: "男朋友", pinyin: "na2n pe2ng you0", significado: "novio" },
  { id: "hz000948", palabra: "坐", pinyin: "zuo4", significado: "tomar (vehiculo)" },
  { id: "hz000949", palabra: "火车", pinyin: "huo3 che1", significado: "tren" },
  { id: "hz000950", palabra: "第", pinyin: "di4", significado: "prefijo numeral" },
  { id: "hz000951", palabra: "照相", pinyin: "zha4o xia4ng", significado: "fotografiar" },
  { id: "hz000952", palabra: "帅", pinyin: "shua4i", significado: "guapo" },
  { id: "hz000953", palabra: "嘛", pinyin: "ma0", significado: "partícula expletiva" },
  { id: "hz000954", palabra: "为什么", pinyin: "we4i she2n me0", significado: "por qué" },
  { id: "hz000955", palabra: "努力", pinyin: "nu3 li4", significado: "aplicado" },
  { id: "hz000956", palabra: "上海", pinyin: "sha4ng ha3i", significado: "Shanghai" },
  { id: "hz000957", palabra: "外滩", pinyin: "wa4i ta1n", significado: "Waitan" },
  { id: "hz000958", palabra: "骑", pinyin: "qi4", significado: "montar" },
  { id: "hz000959", palabra: "自行车", pinyin: "zi4 xi2ng che1", significado: "bicicleta" },
  { id: "hz000960", palabra: "摩托车", pinyin: "mo2 tuo1 che1", significado: "motocicleta" },
  { id: "hz000961", palabra: "三轮车", pinyin: "sa1n lu2n che1", significado: "triciclo" },
  { id: "hz000962", palabra: "姑娘", pinyin: "gu1 niang0", significado: "chica" },
  { id: "hz000963", palabra: "关系", pinyin: "gua1n xi0", significado: "relacion/relacionarse" },
  { id: "hz000964", palabra: "关心", pinyin: "gua1n xi1n", significado: "interesarse por" },
  { id: "hz000965", palabra: "家庭", pinyin: "jia1 ti2ng", significado: "familia" },
  { id: "hz000966", palabra: "说话", pinyin: "shuo1 hua4", significado: "hablar" },
  { id: "hz000967", palabra: "做", pinyin: "zuo4", significado: "hacer" },
  { id: "hz000968", palabra: "梦", pinyin: "me4ng", significado: "soñar, sueño" },
  { id: "hz000969", palabra: "怒朋友", pinyin: "nu3 pe2ng you0", significado: "novia" },
  { id: "hz000970", palabra: "狗", pinyin: "go3u", significado: "perro" },
  { id: "hz000971", palabra: "叫", pinyin: "jia4o", significado: "llamar" },
  { id: "hz000972", palabra: "养", pinyin: "ya3ng", significado: "criar" },
  { id: "hz000973", palabra: "它", pinyin: "ta1", significado: "ello" },
  { id: "hz000974", palabra: "好像", pinyin: "ha3o xia4ng", significado: "al parecer" },
  { id: "hz000975", palabra: "没错", pinyin: "me2i cuo4", significado: "exacto" },
  { id: "hz000976", palabra: "极了", pinyin: "ji2 le0", significado: "sufijo ísimo" },
  { id: "hz000977", palabra: "这么", pinyin: "zhe4 me0", significado: "tal, tan" },
  { id: "hz000978", palabra: "汤", pinyin: "ta1ng", significado: "sopa" },
  { id: "hz000979", palabra: "这样", pinyin: "zhe4 ya4ng", significado: "así" },
  { id: "hz000980", palabra: "下班", pinyin: "xia4 ba1n", significado: "fin del trabajo" },
  { id: "hz000981", palabra: "结婚", pinyin: "jie2 hu1n", significado: "casarse" },
  { id: "hz000982", palabra: "久", pinyin: "jiu3", significado: "largo tiempo" },
  { id: "hz000983", palabra: "小看", pinyin: "xia3o ka4n", significado: "menospreciar" },
  { id: "hz000984", palabra: "露", pinyin: "lo4u", significado: "exhibir" },
  { id: "hz000985", palabra: "一手", pinyin: "yi4 sho3u", significado: "habilidad" },
  { id: "hz000986", palabra: "定", pinyin: "di4ng", significado: "quedar" },
  { id: "hz000987", palabra: "名字", pinyin: "Mi2ng zi3", significado: "Mingzi" },
  { id: "hz000988", palabra: "露西", pinyin: "lu4 xi1", significado: "Rusi" },
  { id: "hz000989", palabra: "认识", pinyin: "re4n shi0", significado: "conocer" },
  { id: "hz000990", palabra: "中餐", pinyin: "zho1ng ca1n", significado: "comida china" },
  { id: "hz000991", palabra: "西餐", pinyin: "xi1 ca1n", significado: "comida occidental" },
  { id: "hz000992", palabra: "快餐", pinyin: "kua4i ca1n", significado: "comida rápida" },
  { id: "hz000993", palabra: "餐馆", pinyin: "ca1n gua3n", significado: "restaurante" },
  { id: "hz000994", palabra: "早餐", pinyin: "za3o ca1n", significado: "desayuno" },
  { id: "hz000995", palabra: "午餐", pinyin: "wu3 ca1n", significado: "almuerzo" },
  { id: "hz000996", palabra: "晚餐", pinyin: "wa3n ca1n", significado: "cena" },
  { id: "hz000997", palabra: "夜宵", pinyin: "ye4 xia1o", significado: "comida ligera (noche)" },
  { id: "hz000998", palabra: "早点", pinyin: "za30 dia3n", significado: "desayuno" },
  {
    id: "hz000999",
    palabra: "出差",
    pinyin: "chu1 cha1i",
    significado: "salir de viaje de negocios",
  },
  { id: "hz001000", palabra: "经常", pinyin: "ji1ng cha2ng", significado: "a menudo" },
  { id: "hz001001", palabra: "挺", pinyin: "ti3ng", significado: "muy" },
  { id: "hz001002", palabra: "辛苦", pinyin: "xi1n ku3", significado: "duro" },
  { id: "hz001003", palabra: "连。。也", pinyin: "lia2n 0 0 ye3", significado: "incluso" },
  { id: "hz001004", palabra: "周末", pinyin: "zho1u mo4", significado: "fin de semana" },
  { id: "hz001005", palabra: "休息", pinyin: "xiu1 xi0", significado: "descansar" },
  { id: "hz001006", palabra: "地", pinyin: "de0", significado: "partícula" },
  { id: "hz001007", palabra: "出来", pinyin: "chu1 la2i", significado: "salir" },
  { id: "hz001008", palabra: "回", pinyin: "hui2", significado: "regresar" },
  { id: "hz001009", palabra: "中午", pinyin: "zho1ng wu3", significado: "mediodía" },
  { id: "hz001010", palabra: "饭", pinyin: "fa4n", significado: "comida" },
  { id: "hz001011", palabra: "随便", pinyin: "sui2 bia4n", significado: "como sea" },
  { id: "hz001012", palabra: "一些", pinyin: "yi4 xie1", significado: "alguno que otro" },
  { id: "hz001013", palabra: "快餐", pinyin: "kua4 ca1n", significado: "comida rápida" },
  { id: "hz001014", palabra: "什么", pinyin: "she2n me0", significado: "cosas por el estilo" },
  { id: "hz001015", palabra: "注意", pinyin: "zhu4 yi4", significado: "tener cuidado con" },
  { id: "hz001016", palabra: "干", pinyin: "ga4n", significado: "hacer" },
  { id: "hz001017", palabra: "孩子", pinyin: "ha2i zi0", significado: "hijo" },
  { id: "hz001018", palabra: "带", pinyin: "da4i", significado: "llevar" },
  { id: "hz001019", palabra: "出去", pinyin: "chu1 qu4", significado: "salir" },
  { id: "hz001020", palabra: "不过", pinyin: "bu2 guo4", significado: "pero" },
  { id: "hz001021", palabra: "爱人", pinyin: "a4i ren0", significado: "marido/mujer" },
  {
    id: "hz001022",
    palabra: "游乐园",
    pinyin: "yo2u le4 yua3n",
    significado: "Parque de atracciones",
  },
  { id: "hz001023", palabra: "自己", pinyin: "zi4 ji3", significado: "uno mismo" },
  {
    id: "hz001024",
    palabra: "痛痛快快",
    pinyin: "to4ng to4ng kua4i kua4i",
    significado: "a nuestas anchas",
  },
  { id: "hz001025", palabra: "轻轻松松", pinyin: "qi1ng qi1ng so1ng so1ng", significado: "cómodo" },
  { id: "hz001026", palabra: "忘", pinyin: "wa4ng", significado: "olvidar" },
  { id: "hz001027", palabra: "静", pinyin: "ji4ng", significado: "tranquilo" },
  { id: "hz001028", palabra: "安静", pinyin: "a1n ji4ng", significado: "tranquilo, silencioso" },
  { id: "hz001029", palabra: "北边", pinyin: "be3i bian0", significado: "norte" },
  { id: "hz001030", palabra: "必须", pinyin: "bi4 xu1", significado: "tener que" },
  { id: "hz001031", palabra: "电影", pinyin: "dia4n yi3ng", significado: "cine, película" },
  { id: "hz001032", palabra: "放假", pinyin: "fa4ng jia4", significado: "tener vacaciones" },
  { id: "hz001033", palabra: "高兴", pinyin: "ga1o xi4ng", significado: "contento" },
  { id: "hz001034", palabra: "不要", pinyin: "bu2 ya4o", significado: "no" },
  { id: "hz001035", palabra: "得到", pinyin: "de2 da4o", significado: "lograr" },
  { id: "hz001036", palabra: "曾经", pinyin: "ce2ng ji1ng", significado: "acción pasada" },
  { id: "hz001037", palabra: "熟悉", pinyin: "shu2 xi1", significado: "conocer bien" },
  { id: "hz001038", palabra: "敢", pinyin: "ga3n", significado: "atreverse" },
  { id: "hz001039", palabra: "到处", pinyin: "da4o chu4", significado: "por todas partes" },
  { id: "hz001040", palabra: "跑", pinyin: "pa3o", significado: "recorrer" },
  { id: "hz001041", palabra: "给", pinyin: "ge3i", significado: "dar" },
  { id: "hz001042", palabra: "印象", pinyin: "yi4n xia4ng", significado: "impresión" },
  { id: "hz001043", palabra: "如何", pinyin: "ru2 he2", significado: "qué, como" },
  { id: "hz001044", palabra: "深", pinyin: "she1n", significado: "profundo" },
  { id: "hz001045", palabra: "感情", pinyin: "ga3n qi2ng", significado: "sentimiento" },
  { id: "hz001046", palabra: "所以", pinyin: "suo3 yi3", significado: "por eso" },
  { id: "hz001047", palabra: "变化", pinyin: "bia4n hua4", significado: "cambio" },
  { id: "hz001048", palabra: "一样", pinyin: "yi2 ya4ng", significado: "igual" },
  { id: "hz001049", palabra: "地方", pinyin: "di4 fang0", significado: "sitio" },
  { id: "hz001050", palabra: "认识", pinyin: "re4n shi0", significado: "conocer" },
  { id: "hz001051", palabra: "汽车", pinyin: "qi4 che1", significado: "automovil" },
  { id: "hz001052", palabra: "越来越", pinyin: "yue4 la2i yue4", significado: "cada vez mas" },
  { id: "hz001053", palabra: "热情", pinyin: "re4 qi2ng", significado: "cordial" },
  { id: "hz001054", palabra: "穿着", pinyin: "chua1n zhuo2", significado: "indumentaria" },
  { id: "hz001055", palabra: "打扮", pinyin: "da3 ban0", significado: "ataviarse" },
  { id: "hz001056", palabra: "变", pinyin: "bia4n", significado: "cambiar" },
  { id: "hz001057", palabra: "时髦", pinyin: "shi2 ma2o", significado: "a la moda" },
  { id: "hz001058", palabra: "菲利普", pinyin: "fe1i li4 pu3", significado: "Felipe" },
  { id: "hz001059", palabra: "水平", pinyin: "shui3 pi2ng", significado: "nivel" },
  { id: "hz001060", palabra: "高", pinyin: "ga1o", significado: "alto" },
  { id: "hz001061", palabra: "同情", pinyin: "to2ng qi2ng", significado: "simpatizar" },
  { id: "hz001062", palabra: "从前", pinyin: "co2ng qia2n", significado: "antes" },
  { id: "hz001063", palabra: "丰富", pinyin: "fe1n fu4", significado: "rico, abundante" },
  { id: "hz001064", palabra: "感到", pinyin: "ga3n da4o", significado: "sentir" },
  { id: "hz001065", palabra: "欢迎", pinyin: "hua1n yi2ng", significado: "acoger" },
  { id: "hz001066", palabra: "机会", pinyin: "ji1 hui4", significado: "oportunidad" },
  { id: "hz001067", palabra: "特意", pinyin: "te4 yi4", significado: "de propio" },
  { id: "hz001068", palabra: "晨练", pinyin: "che2n lia4n", significado: "ejercicio matinal" },
  { id: "hz001069", palabra: "早晨", pinyin: "za3o chen", significado: "mañana" },
  { id: "hz001070", palabra: "注意", pinyin: "zhu4 yi4", significado: "darse cuenta" },
  { id: "hz001071", palabra: "特别", pinyin: "te4 bie3", significado: "sobre todo" },
  { id: "hz001072", palabra: "打", pinyin: "da3", significado: "practicar" },
  { id: "hz001073", palabra: "健美操", pinyin: "jia4n me3i ca1o", significado: "calistenia" },
  { id: "hz001074", palabra: "跑步", pinyin: "pa3o bu4", significado: "correr" },
  { id: "hz001075", palabra: "老大爷", pinyin: "la3o da4 ye0", significado: "abuelo" },
  { id: "hz001076", palabra: "散步", pinyin: "sa4n bu4", significado: "pasear" },
  { id: "hz001077", palabra: "唱", pinyin: "cha4ng", significado: "cantar" },
  { id: "hz001078", palabra: "老大妈", pinyin: "la3o da4 ma1", significado: "abuela" },
  { id: "hz001079", palabra: "大步", pinyin: "da4 bu4", significado: "a grandes pasos" },
  { id: "hz001080", palabra: "甩", pinyin: "shua3i", significado: "agitar" },
  { id: "hz001081", palabra: "手臂", pinyin: "sho3u bi4", significado: "brazo" },
  { id: "hz001082", palabra: "方式", pinyin: "fa1ng shi4", significado: "manera" },
  { id: "hz001083", palabra: "围", pinyin: "we2i", significado: "rodear" },
  { id: "hz001084", palabra: "唱歌", pinyin: "cha4n ge1", significado: "cantar canciones" },
  { id: "hz001085", palabra: "跳舞", pinyin: "tia4o wu3", significado: "bailar" },
  { id: "hz001086", palabra: "早上", pinyin: "za3o shang0", significado: "amanecer" },
  { id: "hz001087", palabra: "先", pinyin: "xia1n", significado: "ante todo, primero" },
  { id: "hz001088", palabra: "操场", pinyin: "ca1o cha3ng", significado: "campo de deporte" },
  { id: "hz001089", palabra: "网球", pinyin: "wa3ng qi2u", significado: "tenis" },
  { id: "hz001090", palabra: "决定", pinyin: "jue2 di4ng", significado: "decidir" },
  { id: "hz001091", palabra: "开始", pinyin: "ka1i shi3", significado: "empezar" },
  { id: "hz001092", palabra: "太极拳", pinyin: "ta4i ji2 qua2n", significado: "taijiquan" },
  { id: "hz001093", palabra: "京剧", pinyin: "ji1ng ju4", significado: "ópera de Pekín" },
  {
    id: "hz001094",
    palabra: "病情",
    pinyin: "bi4ng qi2ng",
    significado: "estado de la enfermedad",
  },
  { id: "hz001095", palabra: "病人", pinyin: "bi4n re2n", significado: "enfermo" },
  { id: "hz001096", palabra: "搞", pinyin: "ga3o", significado: "hacer" },
  { id: "hz001097", palabra: "代表", pinyin: "da4i bia3o", significado: "representante" },
  { id: "hz001098", palabra: "点钟", pinyin: "dia3n zho1ng", significado: "hora" },
  { id: "hz001099", palabra: "各种", pinyin: "ge4 zho3ng", significado: "toda clase de" },
];
