export const libro02 = [
  { id: "hz000801", palabra: "运动", pinyin: "yu4n do4ng", significado: "deporte" },
  { id: "hz000802", palabra: "足球", pinyin: "zu2 qiu2", significado: "fútbol" },
  { id: "hz000803", palabra: "踢", pinyin: "ti1", significado: "jugar, patear" },
  { id: "hz000804", palabra: "可", pinyin: "ke3", significado: "sumamente" },
  { id: "hz000805", palabra: "多", pinyin: "duo1", significado: "mucho" },
  { id: "hz000806", palabra: "网球", pinyin: "wa3ng qiu2", significado: "tenis" },
  { id: "hz000807", palabra: "游泳", pinyin: "yo2u yo3ng", significado: "nadar" },
  { id: "hz000808", palabra: "滑冰", pinyin: "hua2 bi1ng", significado: "patinar" },
  { id: "hz000809", palabra: "以后", pinyin: "yi3 ho4u", significado: "en adelante" },
  { id: "hz000810", palabra: "会", pinyin: "hui4", significado: "saber" },
  { id: "hz000811", palabra: "只", pinyin: "zhi3", significado: "sólo" },
  { id: "hz000812", palabra: "游", pinyin: "yo2u", significado: "nadar" },
  { id: "hz000813", palabra: "愿意", pinyin: "yua4n yi4", significado: "querer" },
  { id: "hz000814", palabra: "当", pinyin: "da1ng", significado: "ser" },
  { id: "hz000815", palabra: "教练", pinyin: "jia4o lia4n", significado: "entrenador" },
  { id: "hz000816", palabra: "排球", pinyin: "pa2i qiu2", significado: "voleibol" },
  { id: "hz000817", palabra: "篮球", pinyin: "la2n qiu2", significado: "baloncesto" },
  { id: "hz000818", palabra: "乒乓球", pinyin: "pi1ng pa1ng qui2", significado: "tenis de mesa" },
  { id: "hz000819", palabra: "体操", pinyin: "ti3 ca1o", significado: "gimnasia" },
  { id: "hz000820", palabra: "流利", pinyin: "liu2 li4", significado: "fluido" },
  { id: "hz000821", palabra: "整齐", pinyin: "zhe3ng qi2", significado: "ordenado" },
  { id: "hz000822", palabra: "旅行", pinyin: "lv3 xi2ng", significado: "viajar" },
  { id: "hz000823", palabra: "见面", pinyin: "jia4n mia4n", significado: "entrevistarse" },
  { id: "hz000824", palabra: "健康", pinyin: "jia4n ka1ng", significado: "sano" },
  { id: "hz000825", palabra: "活动", pinyin: "huo2 do4ng", significado: "actividad" },
  { id: "hz000826", palabra: "以前", pinyin: "yi3 qia2n", significado: "antes" },
  { id: "hz000827", palabra: "过", pinyin: "guo0", significado: "alguna vez" },
  { id: "hz000828", palabra: "听说", pinyin: "ti1ng shu1o", significado: "haber oído decir" },
  { id: "hz000829", palabra: "有名", pinyin: "yo3u mi2ng", significado: "famoso" },
  { id: "hz000830", palabra: "烤鸭", pinyin: "ka3o ya1", significado: "pato laqueado" },
  { id: "hz000831", palabra: "店", pinyin: "dia4n", significado: "restaurante" },
  { id: "hz000832", palabra: "已经", pinyin: "yi3 ji1ng", significado: "ya" },
  { id: "hz000833", palabra: "历史", pinyin: "li4 shi3", significado: "historia" },
  { id: "hz000834", palabra: "座位", pinyin: "zuo4 we4i", significado: "asiento" },
  { id: "hz000835", palabra: "提前", pinyin: "ti2 qia2n", significado: "previamente" },
  { id: "hz000836", palabra: "预订", pinyin: "yu4 di4ng", significado: "reservar" },
  { id: "hz000837", palabra: "几", pinyin: "ji3", significado: "varios" },
  { id: "hz000838", palabra: "今天", pinyin: "ji1n tia1n", significado: "hoy" },
  { id: "hz000839", palabra: "请客", pinyin: "qi3ng ke4", significado: "invitar" },
  { id: "hz000840", palabra: "点菜", pinyin: "dia3n ca4i", significado: "pedir de comer" },
  { id: "hz000841", palabra: "要", pinyin: "ya4o", significado: "querer" },
  { id: "hz000842", palabra: "啤酒", pinyin: "pi2 jiu3", significado: "cerveza" },
  { id: "hz000843", palabra: "杯", pinyin: "be1i", significado: "vaso" },
  { id: "hz000844", palabra: "矿泉水", pinyin: "kua4ng qua2n shui3", significado: "agua mineral" },
  { id: "hz000845", palabra: "只", pinyin: "zhi1", significado: "clasif. Animales" },
  { id: "hz000846", palabra: "瓶", pinyin: "pi2ng", significado: "botella" },
  { id: "hz000847", palabra: "全聚德", pinyin: "qua2n ju4 de2", significado: "Quanjude" },
  {
    id: "hz000848",
    palabra: "松鼠鳜鱼",
    pinyin: "so1ng shu2 gui4 yu2",
    significado: "pescado-ardilla",
  },
  { id: "hz000849", palabra: "西兰花", pinyin: "xi1 la2n hua1", significado: "brócoli" },
  { id: "hz000850", palabra: "葡萄酒", pinyin: "pu2 ta2o jiu3", significado: "vino" },
  { id: "hz000851", palabra: "白酒", pinyin: "ba2i jiu3", significado: "licor" },
  { id: "hz000852", palabra: "青菜", pinyin: "qi1ng ca4i", significado: "verduras, legumbres" },
  { id: "hz000853", palabra: "荤菜", pinyin: "hu1n ca4i", significado: "platos de carne" },
  { id: "hz000854", palabra: "蔬菜", pinyin: "shu1 c4ai", significado: "legumbres, hortalizas" },
  { id: "hz000855", palabra: "杯子", pinyin: "be1i zi0", significado: "vaso" },
  { id: "hz000856", palabra: "饱", pinyin: "ba3o", significado: "lleno" },
  { id: "hz000857", palabra: "鸡蛋", pinyin: "ji1 da4n", significado: "huevo (de gallina)" },
  { id: "hz000858", palabra: "酒", pinyin: "jiu4", significado: "bebidas alcohólicas" },
  { id: "hz000859", palabra: "图书馆", pinyin: "tu2 shu1 gua3n", significado: "biblioteca" },
  { id: "hz000860", palabra: "找", pinyin: "zha3o", significado: "buscar" },
  { id: "hz000861", palabra: "报", pinyin: "ba3o", significado: "periódico" },
  { id: "hz000862", palabra: "招聘", pinyin: "zha1 pi4n", significado: "solictar (trabajo)" },
  { id: "hz000863", palabra: "广告", pinyin: "gua3ng ga3o", significado: "anuncio" },
  { id: "hz000864", palabra: "公司", pinyin: "go1ng si1", significado: "compañía" },
  { id: "hz000865", palabra: "需要", pinyin: "xu1 ya4o", significado: "necesitar" },
  { id: "hz000866", palabra: "懂", pinyin: "do3ng", significado: "entender" },
  { id: "hz000867", palabra: "听", pinyin: "ti1ng", significado: "escuchar" },
  { id: "hz000868", palabra: "广播", pinyin: "gua3ng bo1", significado: "radiodifusión" },
  { id: "hz000869", palabra: "简历", pinyin: "jia3n li4", significado: "curriculum vitae" },
  { id: "hz000870", palabra: "准备", pinyin: "zhu3n be4i", significado: "preparar" },
  { id: "hz000871", palabra: "经理", pinyin: "ji1ng li3", significado: "genrente" },
  { id: "hz000872", palabra: "先", pinyin: "xia1n", significado: "antes que nada" },
  { id: "hz000873", palabra: "面试", pinyin: "mia4n shi4", significado: "entrevistar" },
  { id: "hz000874", palabra: "一下", pinyin: "yi2 xia4", significado: "una vez" },
  { id: "hz000875", palabra: "中文", pinyin: "zho1ng we2n", significado: "lengua china" },
  { id: "hz000876", palabra: "杂志", pinyin: "za2 zhi4", significado: "revista" },
  { id: "hz000877", palabra: "小说", pinyin: "xia3o shuo1", significado: "novela" },
  { id: "hz000878", palabra: "画报", pinyin: "hua4 ba4o", significado: "revista ilustrada" },
  { id: "hz000879", palabra: "电视", pinyin: "dia4n shi4", significado: "televisión" },
  { id: "hz000880", palabra: "笔试", pinyin: "bi3 shi4", significado: "examen escrito" },
  { id: "hz000881", palabra: "口试", pinyin: "ko3 shi4", significado: "examen oral" },
  { id: "hz000882", palabra: "考试", pinyin: "ka3o shi4", significado: "examen, examinar" },
  { id: "hz000883", palabra: "考", pinyin: "ka3o", significado: "examinar" },
  { id: "hz000884", palabra: "成绩", pinyin: "che2ng ji4", significado: "éxito, resultado" },
  { id: "hz000885", palabra: "翻译", pinyin: "fa1n yi4", significado: "traducir, traducción" },
  { id: "hz000886", palabra: "词典", pinyin: "ci2 dia3n", significado: "diccionario" },
  { id: "hz000887", palabra: "辅导", pinyin: "fu3 da3o", significado: "atender (consultas)" },
  { id: "hz000888", palabra: "复习", pinyin: "fu4 xi2", significado: "repasar" },
  { id: "hz000889", palabra: "多", pinyin: "duo1", significado: "¿cuánto?" },
  { id: "hz000890", palabra: "长", pinyin: "cha2ng", significado: "largo" },
  { id: "hz000891", palabra: "谈话", pinyin: "ta2n hua4", significado: "conversar" },
  { id: "hz000892", palabra: "用", pinyin: "yo4ng", significado: "usar" },
  { id: "hz000893", palabra: "硬件", pinyin: "yi4ng jia4n", significado: "hardware" },
  { id: "hz000894", palabra: "软件", pinyin: "rua3n jia4n", significado: "software" },
  { id: "hz000895", palabra: "大学", pinyin: "da4 xue2", significado: "universidad" },
  { id: "hz000896", palabra: "毕业", pinyin: "bi4 ye4", significado: "graduarse" },
  { id: "hz000897", palabra: "计算机", pinyin: "ji4 sua4n ji1", significado: "ordenador" },
  { id: "hz000898", palabra: "专业", pinyin: "zhua1n ye4", significado: "carrera" },
  { id: "hz000899", palabra: "秘书", pinyin: "mi4 shu1", significado: "secretario" },
  { id: "hz000900", palabra: "合同", pinyin: "he2 tong0", significado: "contrato" },
  { id: "hz000901", palabra: "同意", pinyin: "to2ng yi4", significado: "estar de acuerdo" },
  { id: "hz000902", palabra: "通知", pinyin: "to1ng zhi1", significado: "aviso, avisar" },
  { id: "hz000903", palabra: "职员", pinyin: "zhi2 yua2n", significado: "empleado" },
  { id: "hz000904", palabra: "英文", pinyin: "yi1ng we2n", significado: "lengua inglesa" },
  { id: "hz000905", palabra: "美国", pinyin: "me3i guo2", significado: "EEUU" },
  { id: "hz000906", palabra: "小时", pinyin: "xia3o shi2", significado: "hora" },
  { id: "hz000907", palabra: "服务", pinyin: "fu2 wu4", significado: "servir" },
  { id: "hz000908", palabra: "接着", pinyin: "jie1 zhe0", significado: "continuar" },
  { id: "hz000909", palabra: "继续", pinyin: "ji4 xu4", significado: "seguir" },
  { id: "hz000910", palabra: "技术", pinyin: "ji4 shu4", significado: "técnica" },
  { id: "hz000911", palabra: "计划", pinyin: "ji4 hua4", significado: "plan" },
  { id: "hz000912", palabra: "教育", pinyin: "jia4o yu4", significado: "educar" },
  { id: "hz000913", palabra: "解决", pinyin: "jie3 jue2", significado: "solucionar" },
  { id: "hz000914", palabra: "经济", pinyin: "ji1ng ji4", significado: "economía" },
  { id: "hz000915", palabra: "科学", pinyin: "ke1 xue2", significado: "ciencia" },
  { id: "hz000916", palabra: "饭店", pinyin: "fa4n dia4n", significado: "hotel" },
  { id: "hz000917", palabra: "房间", pinyin: "fa3ng jia1n", significado: "habitación" },
  {
    id: "hz000918",
    palabra: "标准间",
    pinyin: "bia1o zhu3n jia1n",
    significado: "habitación estándar",
  },
  {
    id: "hz000919",
    palabra: "豪华间",
    pinyin: "ha2o hua2 ji1an",
    significado: "habitación de lujo",
  },
  { id: "hz000920", palabra: "住", pinyin: "zhu4", significado: "ocupar, usar" },
  { id: "hz000921", palabra: "离", pinyin: "li2", significado: "de" },
  { id: "hz000922", palabra: "机场", pinyin: "ji1 cha3ng", significado: "aeropuerto" },
  { id: "hz000923", palabra: "远", pinyin: "yua3n", significado: "lejano, lejos" },
  { id: "hz000924", palabra: "从 . . 到", pinyin: "co2ng 0 0 da4o", significado: "desde .. hasta" },
  { id: "hz000925", palabra: "公里", pinyin: "go1ng li3", significado: "kilómetro" },
  { id: "hz000926", palabra: "市中心", pinyin: "shi4 zho1n xi1n", significado: "centro urbano" },
  { id: "hz000927", palabra: "步行", pinyin: "bu4 xi2ng", significado: "caminar" },
  { id: "hz000928", palabra: "分钟", pinyin: "fe1n zho1ng", significado: "minuto" },
  { id: "hz000929", palabra: "左右", pinyin: "zuo3 yo4u", significado: "aproximadamente" },
  { id: "hz000930", palabra: "安排", pinyin: "a1n pa2i", significado: "arreglar" },
  { id: "hz000931", palabra: "发", pinyin: "fa1", significado: "enviar" },
  { id: "hz000932", palabra: "传真", pinyin: "chua2n zhe1n", significado: "fax" },
  { id: "hz000933", palabra: "西安", pinyin: "xi1 a1n", significado: "Xian" },
  { id: "hz000934", palabra: "开", pinyin: "ka1i", significado: "conducir" },
  { id: "hz000935", palabra: "车", pinyin: "che1", significado: "vehículo" },
  { id: "hz000936", palabra: "去年", pinyin: "qu4 nia2n", significado: "el año pasado" },
  { id: "hz000937", palabra: "套间", pinyin: "ta4o jia1n", significado: "apartamento" },
  { id: "hz000938", palabra: "办理", pinyin: "ba4n li3", significado: "arreglar, tramitar" },
  { id: "hz000939", palabra: "车站", pinyin: "che1 zha4n", significado: "estación de vehículos" },
  { id: "hz000940", palabra: "出租汽车", pinyin: "chu1 zu1 qi4 che1", significado: "taxi" },
  { id: "hz000941", palabra: "电车", pinyin: "dia4n che1", significado: "tranvía" },
  { id: "hz000942", palabra: "成", pinyin: "che2ng", significado: "ciudad" },
  { id: "hz000943", palabra: "出发", pinyin: "chu1 fa1", significado: "partir" },
  { id: "hz000944", palabra: "方向", pinyin: "fa1ng xia4ng", significado: "dirección" },
  { id: "hz000945", palabra: "照片", pinyin: "zha4o pia4n", significado: "foto" },
  { id: "hz000946", palabra: "照", pinyin: "zha4o", significado: "sacar, tomar" },
  { id: "hz000947", palabra: "男朋友", pinyin: "na2n pe2ng you0", significado: "novio" },
  { id: "hz000948", palabra: "坐", pinyin: "zuo4", significado: "tomar (vehiculo)" },
  { id: "hz000949", palabra: "火车", pinyin: "huo3 che1", significado: "tren" },
  { id: "hz000950", palabra: "第", pinyin: "di4", significado: "prefijo numeral" },
  { id: "hz000951", palabra: "照相", pinyin: "zha4o xia4ng", significado: "fotografiar" },
  { id: "hz000952", palabra: "帅", pinyin: "shua4i", significado: "guapo" },
  { id: "hz000953", palabra: "嘛", pinyin: "ma0", significado: "partícula expletiva" },
  { id: "hz000954", palabra: "为什么", pinyin: "we4i she2n me0", significado: "por qué" },
  { id: "hz000955", palabra: "努力", pinyin: "nu3 li4", significado: "aplicado" },
  { id: "hz000956", palabra: "上海", pinyin: "sha4ng ha3i", significado: "Shanghai" },
  { id: "hz000957", palabra: "外滩", pinyin: "wa4i ta1n", significado: "Waitan" },
  { id: "hz000958", palabra: "骑", pinyin: "qi4", significado: "montar" },
  { id: "hz000959", palabra: "自行车", pinyin: "zi4 xi2ng che1", significado: "bicicleta" },
  { id: "hz000960", palabra: "摩托车", pinyin: "mo2 tuo1 che1", significado: "motocicleta" },
  { id: "hz000961", palabra: "三轮车", pinyin: "sa1n lu2n che1", significado: "triciclo" },
  { id: "hz000962", palabra: "姑娘", pinyin: "gu1 niang0", significado: "chica" },
  { id: "hz000963", palabra: "关系", pinyin: "gua1n xi0", significado: "relacion/relacionarse" },
  { id: "hz000964", palabra: "关心", pinyin: "gua1n xi1n", significado: "interesarse por" },
  { id: "hz000965", palabra: "家庭", pinyin: "jia1 ti2ng", significado: "familia" },
  { id: "hz000966", palabra: "说话", pinyin: "shuo1 hua4", significado: "hablar" },
  { id: "hz000967", palabra: "做", pinyin: "zuo4", significado: "hacer" },
  { id: "hz000968", palabra: "梦", pinyin: "me4ng", significado: "soñar, sueño" },
  { id: "hz000969", palabra: "怒朋友", pinyin: "nu3 pe2ng you0", significado: "novia" },
  { id: "hz000970", palabra: "狗", pinyin: "go3u", significado: "perro" },
  { id: "hz000971", palabra: "叫", pinyin: "jia4o", significado: "llamar" },
  { id: "hz000972", palabra: "养", pinyin: "ya3ng", significado: "criar" },
  { id: "hz000973", palabra: "它", pinyin: "ta1", significado: "ello" },
  { id: "hz000974", palabra: "好像", pinyin: "ha3o xia4ng", significado: "al parecer" },
  { id: "hz000975", palabra: "没错", pinyin: "me2i cuo4", significado: "exacto" },
  { id: "hz000976", palabra: "极了", pinyin: "ji2 le0", significado: "sufijo ísimo" },
  { id: "hz000977", palabra: "这么", pinyin: "zhe4 me0", significado: "tal, tan" },
  { id: "hz000978", palabra: "汤", pinyin: "ta1ng", significado: "sopa" },
  { id: "hz000979", palabra: "这样", pinyin: "zhe4 ya4ng", significado: "así" },
  { id: "hz000980", palabra: "下班", pinyin: "xia4 ba1n", significado: "fin del trabajo" },
  { id: "hz000981", palabra: "结婚", pinyin: "jie2 hu1n", significado: "casarse" },
  { id: "hz000982", palabra: "久", pinyin: "jiu3", significado: "largo tiempo" },
  { id: "hz000983", palabra: "小看", pinyin: "xia3o ka4n", significado: "menospreciar" },
  { id: "hz000984", palabra: "露", pinyin: "lo4u", significado: "exhibir" },
  { id: "hz000985", palabra: "一手", pinyin: "yi4 sho3u", significado: "habilidad" },
  { id: "hz000986", palabra: "定", pinyin: "di4ng", significado: "quedar" },
  { id: "hz000987", palabra: "名字", pinyin: "Mi2ng zi3", significado: "Mingzi" },
  { id: "hz000988", palabra: "露西", pinyin: "lu4 xi1", significado: "Rusi" },
  { id: "hz000989", palabra: "认识", pinyin: "re4n shi0", significado: "conocer" },
  { id: "hz000990", palabra: "中餐", pinyin: "zho1ng ca1n", significado: "comida china" },
  { id: "hz000991", palabra: "西餐", pinyin: "xi1 ca1n", significado: "comida occidental" },
  { id: "hz000992", palabra: "快餐", pinyin: "kua4i ca1n", significado: "comida rápida" },
  { id: "hz000993", palabra: "餐馆", pinyin: "ca1n gua3n", significado: "restaurante" },
  { id: "hz000994", palabra: "早餐", pinyin: "za3o ca1n", significado: "desayuno" },
  { id: "hz000995", palabra: "午餐", pinyin: "wu3 ca1n", significado: "almuerzo" },
  { id: "hz000996", palabra: "晚餐", pinyin: "wa3n ca1n", significado: "cena" },
  { id: "hz000997", palabra: "夜宵", pinyin: "ye4 xia1o", significado: "comida ligera (noche)" },
  { id: "hz000998", palabra: "早点", pinyin: "za30 dia3n", significado: "desayuno" },
  {
    id: "hz000999",
    palabra: "出差",
    pinyin: "chu1 cha1i",
    significado: "salir de viaje de negocios",
  },
  { id: "hz001000", palabra: "经常", pinyin: "ji1ng cha2ng", significado: "a menudo" },
  { id: "hz001001", palabra: "挺", pinyin: "ti3ng", significado: "muy" },
  { id: "hz001002", palabra: "辛苦", pinyin: "xi1n ku3", significado: "duro" },
  { id: "hz001003", palabra: "连。。也", pinyin: "lia2n 0 0 ye3", significado: "incluso" },
  { id: "hz001004", palabra: "周末", pinyin: "zho1u mo4", significado: "fin de semana" },
  { id: "hz001005", palabra: "休息", pinyin: "xiu1 xi0", significado: "descansar" },
  { id: "hz001006", palabra: "地", pinyin: "de0", significado: "partícula" },
  { id: "hz001007", palabra: "出来", pinyin: "chu1 la2i", significado: "salir" },
  { id: "hz001008", palabra: "回", pinyin: "hui2", significado: "regresar" },
  { id: "hz001009", palabra: "中午", pinyin: "zho1ng wu3", significado: "mediodía" },
  { id: "hz001010", palabra: "饭", pinyin: "fa4n", significado: "comida" },
  { id: "hz001011", palabra: "随便", pinyin: "sui2 bia4n", significado: "como sea" },
  { id: "hz001012", palabra: "一些", pinyin: "yi4 xie1", significado: "alguno que otro" },
  { id: "hz001013", palabra: "快餐", pinyin: "kua4 ca1n", significado: "comida rápida" },
  { id: "hz001014", palabra: "什么", pinyin: "she2n me0", significado: "cosas por el estilo" },
  { id: "hz001015", palabra: "注意", pinyin: "zhu4 yi4", significado: "tener cuidado con" },
  { id: "hz001016", palabra: "干", pinyin: "ga4n", significado: "hacer" },
  { id: "hz001017", palabra: "孩子", pinyin: "ha2i zi0", significado: "hijo" },
  { id: "hz001018", palabra: "带", pinyin: "da4i", significado: "llevar" },
  { id: "hz001019", palabra: "出去", pinyin: "chu1 qu4", significado: "salir" },
  { id: "hz001020", palabra: "不过", pinyin: "bu2 guo4", significado: "pero" },
  { id: "hz001021", palabra: "爱人", pinyin: "a4i ren0", significado: "marido/mujer" },
  {
    id: "hz001022",
    palabra: "游乐园",
    pinyin: "yo2u le4 yua3n",
    significado: "Parque de atracciones",
  },
  { id: "hz001023", palabra: "自己", pinyin: "zi4 ji3", significado: "uno mismo" },
  {
    id: "hz001024",
    palabra: "痛快",
    pinyin: "to4ng kua4i",
    significado: "contento",
  },
  { id: "hz001025", palabra: "轻松", pinyin: "qi1ng so1ng", significado: "cómodo" },
  { id: "hz001026", palabra: "忘", pinyin: "wa4ng", significado: "olvidar" },
  { id: "hz001027", palabra: "静", pinyin: "ji4ng", significado: "tranquilo" },
  { id: "hz001028", palabra: "安静", pinyin: "a1n ji4ng", significado: "tranquilo, silencioso" },
  { id: "hz001029", palabra: "北边", pinyin: "be3i bian0", significado: "norte" },
  { id: "hz001030", palabra: "必须", pinyin: "bi4 xu1", significado: "tener que" },
  { id: "hz001031", palabra: "电影", pinyin: "dia4n yi3ng", significado: "cine, película" },
  { id: "hz001032", palabra: "放假", pinyin: "fa4ng jia4", significado: "tener vacaciones" },
  { id: "hz001033", palabra: "高兴", pinyin: "ga1o xi4ng", significado: "contento" },
  { id: "hz001034", palabra: "不要", pinyin: "bu2 ya4o", significado: "no" },
  { id: "hz001035", palabra: "得到", pinyin: "de2 da4o", significado: "lograr" },
  { id: "hz001036", palabra: "曾经", pinyin: "ce2ng ji1ng", significado: "acción pasada" },
  { id: "hz001037", palabra: "熟悉", pinyin: "shu2 xi1", significado: "conocer bien" },
  { id: "hz001038", palabra: "敢", pinyin: "ga3n", significado: "atreverse" },
  { id: "hz001039", palabra: "到处", pinyin: "da4o chu4", significado: "por todas partes" },
  { id: "hz001040", palabra: "跑", pinyin: "pa3o", significado: "correr" },
  { id: "hz001041", palabra: "给", pinyin: "ge3i", significado: "dar" },
  { id: "hz001042", palabra: "印象", pinyin: "yi4n xia4ng", significado: "impresión" },
  { id: "hz001043", palabra: "如何", pinyin: "ru2 he2", significado: "qué, como" },
  { id: "hz001044", palabra: "深", pinyin: "she1n", significado: "profundo" },
  { id: "hz001045", palabra: "感情", pinyin: "ga3n qi2ng", significado: "sentimiento" },
  { id: "hz001046", palabra: "所以", pinyin: "suo3 yi3", significado: "por eso" },
  { id: "hz001047", palabra: "变化", pinyin: "bia4n hua4", significado: "cambio" },
  { id: "hz001048", palabra: "一样", pinyin: "yi2 ya4ng", significado: "igual" },
  { id: "hz001049", palabra: "地方", pinyin: "di4 fang0", significado: "sitio" },
  { id: "hz001050", palabra: "认识", pinyin: "re4n shi0", significado: "conocer" },
  { id: "hz001051", palabra: "汽车", pinyin: "qi4 che1", significado: "automovil" },
  { id: "hz001052", palabra: "越来越", pinyin: "yue4 la2i yue4", significado: "cada vez mas" },
  { id: "hz001053", palabra: "热情", pinyin: "re4 qi2ng", significado: "cordial" },
  { id: "hz001054", palabra: "穿着", pinyin: "chua1n zhuo2", significado: "indumentaria" },
  { id: "hz001055", palabra: "打扮", pinyin: "da3 ban0", significado: "ataviarse" },
  { id: "hz001056", palabra: "变", pinyin: "bia4n", significado: "cambiar" },
  { id: "hz001057", palabra: "时髦", pinyin: "shi2 ma2o", significado: "a la moda" },
  { id: "hz001058", palabra: "菲利普", pinyin: "fe1i li4 pu3", significado: "Felipe" },
  { id: "hz001059", palabra: "水平", pinyin: "shui3 pi2ng", significado: "nivel" },
  { id: "hz001060", palabra: "高", pinyin: "ga1o", significado: "alto" },
  { id: "hz001061", palabra: "同情", pinyin: "to2ng qi2ng", significado: "simpatizar" },
  { id: "hz001062", palabra: "从前", pinyin: "co2ng qia2n", significado: "antes" },
  { id: "hz001063", palabra: "丰富", pinyin: "fe1n fu4", significado: "rico, abundante" },
  { id: "hz001064", palabra: "感到", pinyin: "ga3n da4o", significado: "sentir" },
  { id: "hz001065", palabra: "欢迎", pinyin: "hua1n yi2ng", significado: "acoger" },
  { id: "hz001066", palabra: "机会", pinyin: "ji1 hui4", significado: "oportunidad" },
  { id: "hz001067", palabra: "特意", pinyin: "te4 yi4", significado: "de propio" },
  { id: "hz001068", palabra: "晨练", pinyin: "che2n lia4n", significado: "ejercicio matinal" },
  { id: "hz001069", palabra: "早晨", pinyin: "za3o chen", significado: "mañana" },
  { id: "hz001070", palabra: "注意", pinyin: "zhu4 yi4", significado: "darse cuenta" },
  { id: "hz001071", palabra: "特别", pinyin: "te4 bie3", significado: "sobre todo" },
  { id: "hz001072", palabra: "打", pinyin: "da3", significado: "practicar" },
  { id: "hz001073", palabra: "健美操", pinyin: "jia4n me3i ca1o", significado: "calistenia" },
  { id: "hz001074", palabra: "跑步", pinyin: "pa3o bu4", significado: "correr" },
  { id: "hz001075", palabra: "老大爷", pinyin: "la3o da4 ye0", significado: "abuelo" },
  { id: "hz001076", palabra: "散步", pinyin: "sa4n bu4", significado: "pasear" },
  { id: "hz001077", palabra: "唱", pinyin: "cha4ng", significado: "cantar" },
  { id: "hz001078", palabra: "老大妈", pinyin: "la3o da4 ma1", significado: "abuela" },
  { id: "hz001079", palabra: "大步", pinyin: "da4 bu4", significado: "a grandes pasos" },
  { id: "hz001080", palabra: "甩", pinyin: "shua3i", significado: "agitar" },
  { id: "hz001081", palabra: "手臂", pinyin: "sho3u bi4", significado: "brazo" },
  { id: "hz001082", palabra: "方式", pinyin: "fa1ng shi4", significado: "manera" },
  { id: "hz001083", palabra: "围", pinyin: "we2i", significado: "rodear" },
  { id: "hz001084", palabra: "唱歌", pinyin: "cha4n ge1", significado: "cantar canciones" },
  { id: "hz001085", palabra: "跳舞", pinyin: "tia4o wu3", significado: "bailar" },
  { id: "hz001086", palabra: "早上", pinyin: "za3o shang0", significado: "amanecer" },
  { id: "hz001087", palabra: "先", pinyin: "xia1n", significado: "ante todo, primero" },
  { id: "hz001088", palabra: "操场", pinyin: "ca1o cha3ng", significado: "campo de deporte" },
  { id: "hz001089", palabra: "网球", pinyin: "wa3ng qi2u", significado: "tenis" },
  { id: "hz001090", palabra: "决定", pinyin: "jue2 di4ng", significado: "decidir" },
  { id: "hz001091", palabra: "开始", pinyin: "ka1i shi3", significado: "empezar" },
  { id: "hz001092", palabra: "太极拳", pinyin: "ta4i ji2 qua2n", significado: "taijiquan" },
  { id: "hz001093", palabra: "京剧", pinyin: "ji1ng ju4", significado: "ópera de Pekín" },
  {
    id: "hz001094",
    palabra: "病情",
    pinyin: "bi4ng qi2ng",
    significado: "estado de la enfermedad",
  },
  { id: "hz001095", palabra: "病人", pinyin: "bi4n re2n", significado: "enfermo" },
  { id: "hz001096", palabra: "搞", pinyin: "ga3o", significado: "hacer" },
  { id: "hz001097", palabra: "代表", pinyin: "da4i bia3o", significado: "representante" },
  { id: "hz001098", palabra: "点钟", pinyin: "dia3n zho1ng", significado: "hora" },
  { id: "hz001099", palabra: "各种", pinyin: "ge4 zho3ng", significado: "toda clase de" },
  { id:"hz001100", palabra: "划船", pinyin: "hua3 chua3n", significado: "remar"},
  { id:"hz001101", palabra: "天气", pinyin: "tia1n qi4", significado: "tiempo"},
  { id:"hz001102", palabra: "风景", pinyin: "fe1ng ji3ng", significado: "paisaje"},
  { id:"hz001103", palabra: "天", pinyin: "tia1n", significado: "cielo"},
  { id:"hz001104", palabra: "朵", pinyin: "duo3", significado: "clas. Flores y nubes"},
  { id:"hz001105", palabra: "白", pinyin: "ba3i", significado: "blanco"},
  { id:"hz001106", palabra: "云", pinyin: "yu2n", significado: "nube"},
  { id:"hz001107", palabra: "湖边", pinyin: "hu2 bia1n", significado: "orilla del lago"},
  { id:"hz001108", palabra: "棵", pinyin: "ke1", significado: "clas. Plantas"},
  { id:"hz001109", palabra: "绿", pinyin: "lv4", significado: "verde"},
  { id:"hz001110", palabra: "树", pinyin: "shu4", significado: "árbol"},
  { id:"hz001111", palabra: "水面", pinyin: "shui3 mia4n", significado: "superficie del agua"},
  { id:"hz001112", palabra: "船", pinyin: "chua3n", significado: "barco"},
  { id:"hz001113", palabra: "鱼", pinyin: "yu2", significado: "pez"},
  { id:"hz001114", palabra: "前边", pinyin: "qia3n bia1n", significado: "delante"},
  { id:"hz001115", palabra: "游", pinyin: "yo2u", significado: "nadar"},
  { id:"hz001116", palabra: "多么", pinyin: "duo1 me0", significado: "qué, cuán"},
  { id:"hz001117", palabra: "快乐", pinyin: "kua4i le4", significado: "feliz"},
  { id:"hz001118", palabra: "故事", pinyin: "gu4 shi4", significado: "cuento"},
  { id:"hz001119", palabra: "古代", pinyin: "gu3 da4i", significado: "época antigua"},
  { id:"hz001120", palabra: "著名", pinyin: "zhu4 mi2ng", significado: "famoso"},
  { id:"hz001121", palabra: "哲学家", pinyin: "zhe2 xue2 jia1", significado: "filósofo"},
  { id:"hz001122", palabra: "回答", pinyin: "hui2 da3", significado: "responder"},
  { id:"hz001123", palabra: "秒", pinyin: "mia3o", significado: "maravilloso"},
  { id:"hz001124", palabra: "刮风", pinyin: "gua1 fe1ng", significado: "soplar el viento"},
  { id:"hz001125", palabra: "还", pinyin: "hua3n", significado: "devolver"},
  { id:"hz001126", palabra: "饿", pinyin: "e4", significado: "hambriento"},
  { id:"hz001127", palabra: "等", pinyin: "de3ng", significado: "esperar"},
  { id:"hz001128", palabra: "顿", pinyin: "du4n", significado: "clasif. Comida"},
  { id:"hz001129", palabra: "菜", pinyin: "ca4i", significado: "comida"},
  { id:"hz001130", palabra: "庄子", pinyin: "Zhua1ng Zi3", significado: "ZuangZi "},
  { id:"hz001131", palabra: "四川", pinyin: "Si4 Chua1n", significado: "Sichuan"},
  { id:"hz001132", palabra: "饺子", pinyin: "jia3o zi0", significado: "raviolis"},
  { id:"hz001133", palabra: "辆", pinyin: "lia4ng", significado: "clas. Vehículos de tierra"},
  { id:"hz001134", palabra: "客人", pinyin: "ke4 re2n", significado: "invitados"},
  { id:"hz001135", palabra: "下雨", pinyin: "xia4 yu3", significado: "llover"},
  { id:"hz001136", palabra: "太阳", pinyin: "ta4i ya3ng", significado: "sol"},
  { id:"hz001137", palabra: "进行", pinyin: "ji4n xi2ng", significado: "realizar"},
  { id:"hz001138", palabra: "摆", pinyin: "ba3i", significado: "colocar"},
  { id:"hz001139", palabra: "家", pinyin: "jia1", significado: "clasif. Familias Empresas"},
  { id:"hz001140", palabra: "川菜", pinyin: "chua1n ca4i", significado: "Comida Sichuan"},
  { id:"hz001141", palabra: "挺", pinyin: "ti4ng", significado: "muy "},
  { id:"hz001142", palabra: "看来", pinyin: "ka4n la2i ", significado: "al parecer"},
  { id:"hz001143", palabra: "楼下", pinyin: "lo2u xia4", significado: "piso de abajo"},
  { id:"hz001144", palabra: "好像", pinyin: "ha3o xia4ng", significado: "según parece"},
  { id:"hz001145", palabra: "位子", pinyin: "we4i zi0", significado: "mesa"},
  { id:"hz001146", palabra: "单间", pinyin: "da1n jia1n ", significado: "habitación individual"},
  { id:"hz001147", palabra: "靠", pinyin: "ka4o", significado: "pegar"},
  { id:"hz001148", palabra: "窗", pinyin: "chua1ng", significado: "ventana"},
  { id:"hz001149", palabra: "点菜", pinyin: "dia3n ca4i", significado: "platos"},
  { id:"hz001150", palabra: "随便", pinyin: "sui2 bia4n ", significado: "como sea"},
  { id:"hz001151", palabra: "鸡肉", pinyin: "jia1 ro4u", significado: "carne de pollo"},
  { id:"hz001152", palabra: "切", pinyin: "qie1", significado: "cortar"},
  { id:"hz001153", palabra: "丁", pinyin: "di1ng", significado: "dado"},
  { id:"hz001154", palabra: "加上", pinyin: "jia1 sha4ng", significado: "añadir"},
  { id:"hz001155", palabra: "油炸", pinyin: "yóu zha2", significado: "freir"},
  { id:"hz001156", palabra: "花生米", pinyin: "hua1 she1ng mi4", significado: "cacahuete"},
  { id:"hz001157", palabra: "辣椒", pinyin: "la4 jia1o", significado: "pimiento"},
  { id:"hz001158", palabra: "炒", pinyin: "cha3o ", significado: "sofreir"},
  { id:"hz001159", palabra: "小吃", pinyin: "xia3o chi1", significado: "bocadillo"},
  { id:"hz001160", palabra: "香", pinyin: "xia1ng", significado: "oloroso"},
  { id:"hz001161", palabra: "嫩", pinyin: "ne4n", significado: "tierno"},
  { id:"hz001162", palabra: "慢", pinyin: "ma4n ", significado: "despacio"},
  { id:"hz001163", palabra: "本来", pinyin: "be3n la2i", significado: "al principio"},
  { id:"hz001164", palabra: "特点", pinyin: "te4 dia3n", significado: "característica"},
  { id:"hz001165", palabra: "麻", pinyin: "ma2", significado: "mordaz (sabor)"},
  { id:"hz001166", palabra: "辣", pinyin: "la4", significado: "picante"},
  { id:"hz001167", palabra: "宫保鸡丁", pinyin: "go1ng  ba3o ji1 di1ng", significado: "Plato de dados de carne"},
  { id:"hz001168", palabra: "东坡肉", pinyin: "do1ng  po1 ro4u", significado: "Plato DongPo"},
  { id:"hz001169", palabra: "香酥鸭", pinyin: "xia1ng  su1  ya1", significado: "Pato frito"},
  { id:"hz001170", palabra: "小孩儿", pinyin: "xia3o ha2i er0", significado: "niño"},
  { id:"hz001171", palabra: "聪明", pinyin: "co1ng mi2ng", significado: "inteligente"},
  { id:"hz001172", palabra: "翻译", pinyin: "fa1n yi4", significado: "traducir, traducción"},
  { id:"hz001173", palabra: "明白", pinyin: "mi2ng ba2i", significado: "entendido"},
  { id:"hz001174", palabra: "回来", pinyin: "hui2 la2i", significado: "regresar aquí"},
  { id:"hz001175", palabra: "回去", pinyin: "hui2 qu4", significado: "volver allí"},
  { id:"hz001176", palabra: "进来", pinyin: "ji4n la2i", significado: "entrar aquí"},
  { id:"hz001177", palabra: "进去", pinyin: "ji4n qu4", significado: "entrar allí"},
  { id: "hz001178", palabra: "送"	 , pinyin:  "so4ng", significado: "despedir"},
{ id: "hz001179", palabra: "整理", pinyin: "zhe3ng li3", significado: "arreglar"},
{ id: "hz001180", palabra: "收拾", pinyin: "sho1u shi2", significado: "preparar"},
{ id: "hz001181", palabra: "穿", pinyin: "chua1n", significado: "vestirse"},
{ id: "hz001182", palabra: "礼物", pinyin: "li3 wu4", significado: "regalo"},
{ id: "hz001183", palabra: "土特产", pinyin: "tu3 te4 cha3n", significado: "productos especiales y auto2ctonos"},
{ id: "hz001184", palabra: "茶叶", pinyin: "cha2 ye4", significado: "te2"},
{ id: "hz001185", palabra: "玩具", pinyin: "wa2n ju4", significado: "juguete"},
{ id: "hz001186", palabra: "丝绸", pinyin: "si1 cho2u", significado: "seda"},
{ id: "hz001187", palabra: "满载而归", pinyin: "ma3n za4i e2r gui1", significado: "volver cargado de hallazgos"},
{ id: "hz001188", palabra: "遍", pinyin: "bia4n", significado: "vez"},
{ id: "hz001189", palabra: "要紧", pinyin: "ya4o ji3n", significado: "importante"},
{ id: "hz001190", palabra: "护照", pinyin: "hu4 zha4o", significado: "pasaporte"},
{ id: "hz001191", palabra: "机票", pinyin: "ji1 pia4o", significado: "pasaje de avión"},
{ id: "hz001192", palabra: "千万", pinyin: "qia1n wa4n", significado: "a toda costa, de ninguna manera"},
{ id: "hz001193", palabra: "虽然", pinyin: "sui1 ra2n", significado: "aunque"},
{ id: "hz001194", palabra: "长", pinyin: "cha2ng", significado: "largo"},
{ id: "hz001195", palabra: "收获", pinyin: "sho1u huo4", significado: "resultado, fruto"},
{ id: "hz001196", palabra: "不少", pinyin: "bu4 sha3o", significado: "no pocos"},
{ id: "hz001197", palabra: "新", pinyin: "xi1n", significado: "nuevo"},
{ id: "hz001198", palabra: "当然", pinyin: "da1ng ra2n", significado: "desde luego"},
{ id: "hz001199", palabra: "主要", pinyin: "zhu3 ya4o", significado: "principal"},
{ id: "hz001200", palabra: "明年", pinyin: "mi2ng nia2n", significado: "el año que viene"},
{ id: "hz001201", palabra: "错", pinyin: "cuo4", significado: "equivocado, desacertado"},
{ id: "hz001202", palabra: "不舒服", pinyin: "bu4 shu1 fu", significado: "indispuesto"},
{ id: "hz001203", palabra: "顺利", pinyin: "shu4n li4", significado: "feliz, sin dificultad alguna"},
{ id: "hz001204", palabra: "草地", pinyin: "ca3o di4", significado: "prado"},
{ id: "hz001205", palabra: "树林", pinyin: "shu4 li2n", significado: "bosque"},
{ id: "hz001206", palabra: "欧洲", pinyin: "o1u zho1u", significado: "Europa"},
{ id: "hz001207", palabra: "亚洲", pinyin: "Ya4 zho1u", significado: "Asia"},
{ id: "hz001208", palabra: "美洲", pinyin: "Me3i zho1u", significado: "América"},
{ id: "hz001209", palabra: "广场", pinyin: "gua3ng cha3ng", significado: "plaza"},
{ id: "hz001210", palabra: "风筝", pinyin: "fe1ng zhe1ng", significado: "cometa"},
{ id: "hz001211", palabra: "飞", pinyin: "fe1i", significado: "volar"},
{ id: "hz001212", palabra: "样子", pinyin: "ya4ng zi", significado: "forma"},
{ id: "hz001213", palabra: "不同", pinyin: "bu4 to2ng", significado: "diferente"},
{ id: "hz001214", palabra: "老鹰", pinyin: "la3o yi1ng", significado: "águila"},
{ id: "hz001215", palabra: "燕子", pinyin: "ya4n zi", significado: "golondrina"},
{ id: "hz001216", palabra: "蜻蜓", pinyin: "qi1ng ti2ng", significado: "libélula, caballito del diablo"},
{ id: "hz001217", palabra: "蝴蝶", pinyin: "hu2 die2", significado: "mariposa"},
{ id: "hz001218", palabra: "起来", pinyin: "qi3 la2i", significado: "elevarse"},
{ id: "hz001219", palabra: "向", pinyin: "xia4ng", significado: "hacia"},
{ id: "hz001220", palabra: "越..越", pinyin: "yue4...yue4", significado: "cada vez más"},
{ id: "hz001221", palabra: "高", pinyin: "ga1o", significado: "alto"},
{ id: "hz001222", palabra: "龙", pinyin: "lo2ng", significado: "dragón"},
{ id: "hz001223", palabra: "往", pinyin: "wa3ng", significado: "a, hacia"},
{ id: "hz001224", palabra: "过去", pinyin: "guo4 qu4", significado: "hasta allí"},
{ id: "hz001225", palabra: "好", pinyin: "ha3o", significado: "bien"},
{ id: "hz001226", palabra: "或者", pinyin: "huo4 zhe3", significado: " o"},
{ id: "hz001227", palabra: "大后天", pinyin: "da4 ho4u tia1n", significado: "el día siguiente al pasado mañana"},
{ id: "hz001228", palabra: "借", pinyin: "jie4", significado: "pedir prestado"},
{ id: "hz001229", palabra: "词典", pinyin: "ci2 dia3n", significado: "diccionario"},
{ id: "hz001230", palabra: "激动", pinyin: "ji1 do4ng", significado: "emocionado"},
{ id: "hz001231", palabra: "黑", pinyin: "he1i", significado: "negro"},
{ id: "hz001232", palabra: "红", pinyin: "ho2ng", significado: "rojo"},
{ id: "hz001233", palabra: "忽然", pinyin: "hu1 ra2n", significado: "de repente"},
{ id: "hz001234", palabra: "互相", pinyin: "hu4 xia1ng", significado: "mutuamente"},
{ id: "hz001235", palabra: "结果", pinyin: "jie2 guo3", significado: "resultado"},
{ id: "hz001236", palabra: "表", pinyin: "bia3o", significado: " reloj "},
{ id: "hz001237", palabra: "太太", pinyin: "ta4itai", significado: " señora "},
{ id: "hz001238", palabra: "块", pinyin: "kua4i", significado: " pieza, pedazo "},
{ id: "hz001239", palabra: "手表", pinyin: "sho3ubia3o", significado: " reloj de pulsera "},
{ id: "hz001240", palabra: "什么样", pinyin: "she2nme ya4ng", significado: " de qué forma "},
{ id: "hz001241", palabra: "产", pinyin: "cha3n", significado: " producir "},
{ id: "hz001242", palabra: "比", pinyin: "bi3", significado: " que [como conj. comparativa] "},
{ id: "hz001243", palabra: "更", pinyin: "ge4ng", significado: " ma2s "},
{ id: "hz001244", palabra: "牌", pinyin: "pa2i", significado: " marca "},
{ id: "hz001245", palabra: "价格", pinyin: "jia4ge2", significado: " precio "},
{ id: "hz001246", palabra: "拿", pinyin: "na2", significado: " tomar "},
{ id: "hz001247", palabra: "一般", pinyin: "yi4ba1n", significado: " generalmente "},
{ id: "hz001248", palabra: "这里", pinyin: "zhe4li3", significado: " aquí"},
{ id: "hz001249", palabra: "保险柜", pinyin: "ba3oxia3ngui4", significado: " caja fuerte "},
{ id: "hz001250", palabra: "这边", pinyin: "zhe4bia1n", significado: " aquí"},
{ id: "hz001251", palabra: "刚才", pinyin: "ga1ngca2i", significado: " poco antes, hace un momento "},
{ id: "hz001252", palabra: "名贵", pinyin: "mi2nggui4", significado: " famoso y valioso "},
{ id: "hz001253", palabra: "店", pinyin: "dia4n", significado: " tienda "},
{ id: "hz001254", palabra: "包装", pinyin: "ba1ozhua1ng", significado: " empaquetar "},
{ id: "hz001255", palabra: "礼物", pinyin: "li3wu4", significado: " regalo "},
{ id: "hz001256", palabra: "惊喜", pinyin: "ji1ngxi3", significado: " sorpresa "},
{ id: "hz001257", palabra: "瑞士", pinyin: "Rui4shi4", significado: " Suiza "},
{ id: "hz001258", palabra: "劳力士", pinyin: "La2oli4shi4", significado: " Rolex "},
{ id: "hz001259", palabra: "丢", pinyin: "diu1", significado: " perder "},
{ id: "hz001260", palabra: "篇", pinyin: "pia1n", significado: " para ensayo, arti2culo, hoja de papel, etc. "},
{ id: "hz001261", palabra: "文章", pinyin: "we2nzha1ng", significado: " ensayo, artículo "},
{ id: "hz001262", palabra: "汉字", pinyin: "ha4nzi4", significado: " carácter chino, escritura china "},
{ id: "hz001263", palabra: "课本", pinyin: "ke4be3n", significado: " libro de texto "},
{ id: "hz001264", palabra: "课文", pinyin: "ke4we2n", significado: " texto "},
{ id: "hz001265", palabra: "会话", pinyin: "hui4hua4", significado: " conversar, platicar "},
{ id: "hz001266", palabra: "热闹", pinyin: "re4na3o", significado: " animado, bullicioso "},
{ id: "hz001267", palabra: "建筑", pinyin: "jia4nzhu4", significado: " edificio "},
{ id: "hz001268", palabra: "夏天", pinyin: "xia4tia1n", significado: " verano "},
{ id: "hz001269", palabra: "热", pinyin: "re4", significado: " cálido "},
{ id: "hz001270", palabra: "情况", pinyin: "qi2ngkua4ng", significado: " condiciones "},
{ id: "hz001271", palabra: "差不多", pinyin: "cha4bu4duo1", significado: " parecido "},
{ id: "hz001272", palabra: "街道", pinyin: "jie1da4o", significado: " calle "},
{ id: "hz001273", palabra: "宽", pinyin: "kua1n", significado: " ancho "},
{ id: "hz001274", palabra: "立交桥", pinyin: "li4jia1oqia2o", significado: " cruces a desnivel "},
{ id: "hz001275", palabra: "高架路", pinyin: "ga1ojia4lu4", significado: " avenida elevada "},
{ id: "hz001276", palabra: "堵车", pinyin: "du3che1", significado: " atasco de coches "},
{ id: "hz001277", palabra: "城市", pinyin: "che2ngshi4", significado: " ciudad "},
{ id: "hz001278", palabra: "相比", pinyin: "xia1ngbi3", significado: " comparar "},
{ id: "hz001279", palabra: "不如", pinyin: "bu4ru2", significado: " palidecer, ser inferior "},
{ id: "hz001280", palabra: "商业", pinyin: "sha1ngye4", significado: " comercio "},
{ id: "hz001281", palabra: "名胜", pinyin: "mi2ngshe4ng", significado: " lugar famoso por su paisaje "},
{ id: "hz001282", palabra: "古迹", pinyin: "gu3ji4", significado: " lugar de interés histórico "},
{ id: "hz001283", palabra: "各", pinyin: "ge4", significado: " cada cual "},
{ id: "hz001284", palabra: "话", pinyin: "hua4", significado: " habla, dialecto "},
{ id: "hz001285", palabra: "句", pinyin: "ju4", significado: " clas. para frases "},
{ id: "hz001286", palabra: "好听", pinyin: "ha3oti1ng", significado: " agradable al oído "},
{ id: "hz001287", palabra: "河", pinyin: "he2", significado: " río "},
{ id: "hz001288", palabra: "流利", pinyin: "liu2li4", significado: " fluido, suelto "},
{ id: "hz001289", palabra: "技术", pinyin: "ji4shu4", significado: " técnica "},
{ id: "hz001290", palabra: "了解", pinyin: "lia3ojie3", significado: " conocer "},
{ id: "hz001291", palabra: "爱好", pinyin: "a4iha4o", significado: " afición "},
{ id: "hz001292", palabra: "除了 .. 以外", pinyin: "chu2le .. yi3wa4i", significado: " excepto, salvo, además de"},
{ id: "hz001293", palabra: "爱", pinyin: "a4i", significado: " gustar, aficionarse a "},
{ id: "hz001294", palabra: "比赛", pinyin: "bi3sa4i", significado: " partido, competición "},
{ id: "hz001295", palabra: "其他", pinyin: "qi2ta1", significado: " demás, otro "},
{ id: "hz001296", palabra: "迷", pinyin: "mi2", significado: " fan, hincha, fanático "},
{ id: "hz001297", palabra: "支", pinyin: "zhi1", significado: " clas. para equipo deportivo, ejército, canción, composición musical, objeto alargado, etc. "},
{ id: "hz001298", palabra: "球队", pinyin: "qiu2dui4", significado: " equipo "},
{ id: "hz001299", palabra: "队", pinyin: "dui4", significado: " equipo "},
{ id: "hz001300", palabra: "球员", pinyin: "qiu2yua2n", significado: " jugador "},
{ id: "hz001301", palabra: "骑", pinyin: "qi2", significado: " montar en (bicicleta, a [caballo]) "},
{ id: "hz001302", palabra: "自行车", pinyin: "zi4xi2ngche1", significado: " bicicleta "},
{ id: "hz001303", palabra: "全国", pinyin: "qua2nguo2", significado: " todo el país "},
{ id: "hz001304", palabra: "各地", pinyin: "ge4di4", significado: " diversos lugares "},
{ id: "hz001305", palabra: "旅行", pinyin: "lv3xi2ng", significado: " viaje "},
{ id: "hz001306", palabra: "既 .. 也", pinyin: "ji4 .. ye3", significado: " tanto... como "},
{ id: "hz001307", palabra: "风景", pinyin: "fe1ngji3ng", significado: " paisaje "},
{ id: "hz001308", palabra: "国外", pinyin: "guo2wa4i", significado: " fuera del país, extranjero "},
{ id: "hz001309", palabra: "倒", pinyin: "da4o", significado: " nada de eso "},
{ id: "hz001310", palabra: "电视", pinyin: "dia4nshi4", significado: " televisión "},
{ id: "hz001311", palabra: "节目", pinyin: "jie2mu4", significado: " programa "},
{ id: "hz001312", palabra: "打的", pinyin: "da3 di1", significado: " tomando taxi "},
{ id: "hz001313", palabra: "受", pinyin: "sho4u", significado: " ser objeto de... "},
{ id: "hz001314", palabra: "启发", pinyin: "qi3fa1", significado: " inspiración "},
{ id: "hz001315", palabra: "开车", pinyin: "ka1iche1", significado: " conducir "},
{ id: "hz001316", palabra: "车", pinyin: "che1", significado: " vehículo que se mueve en la tierra y sirve como medio de transporte "},
{ id: "hz001317", palabra: "遍", pinyin: "bia4n", significado: " todo "},
{ id: "hz001318", palabra: "全球", pinyin: "qua2nqiu2", significado: " todo el globo terráqueo "},
{ id: "hz001319", palabra: "巴西", pinyin: "Ba1xi1", significado: " Brasil "},
{ id: "hz001320", palabra: "罗纳尔多", pinyin: "Luo2 na4' e3r duo1", significado: " Ronaldo "},
{ id: "hz001321", palabra: "伦敦", pinyin: "Lu2ndu1n", significado: " Londres "},
{ id: "hz001322", palabra: "坚持", pinyin: "jia1nchi2", significado: " persistir "},
{ id: "hz001323", palabra: "笑", pinyin: "xia4o", significado: " reír "},
{ id: "hz001324", palabra: "大声", pinyin: "da4she1ng", significado: " en voz alta "},
{ id: "hz001325", palabra: "交谈", pinyin: "jia1ota2n", significado: " conversar "},
{ id: "hz001326", palabra: "西洋画儿", pinyin: "xi1ya2nghua4r", significado: " pintura occidental "},
{ id: "hz001327", palabra: "反对", pinyin: "fa3ndui4", significado: " oponerse "},
{ id: "hz001328", palabra: "感觉", pinyin: "ga3njue2", significado: " parecer "},
{ id: "hz001329", palabra: "非常", pinyin: "fe1icha2ng", significado: " sumamente "},
{ id: "hz001330", palabra: "美丽", pinyin: "me3ili4", significado: " hermoso, bonito "},
{ id: "hz001331", palabra: "美", pinyin: "me3i", significado: " hermoso, bonito "},
{ id: "hz001332", palabra: "东方", pinyin: "do1ngfa1ng", significado: " oriente "},
{ id: "hz001333", palabra: "都市", pinyin: "du1shi4", significado: " ciudad, metrópoli "},
{ id: "hz001334", palabra: "人口", pinyin: "re2nko3u", significado: " poblacio2n "},
{ id: "hz001335", palabra: "现代化", pinyin: "xia4nda4ihua4", significado: " modernización, moderno "},
{ id: "hz001336", palabra: "著名", pinyin: "zhu4mi2ng", significado: " famoso, célebre "},
{ id: "hz001337", palabra: "古都", pinyin: "gu3du1", significado: " capital antigua "},
{ id: "hz001338", palabra: "座", pinyin: "zuo4", significado: " clas. para cuerpos gigantescos e inmóviles "},
{ id: "hz001339", palabra: "杭州", pinyin: "Ha2ngzho1u", significado: " Hangzhou "},
{ id: "hz001340", palabra: "西安", pinyin: "Xi1'a1n", significado: " Xi2 an "},
{ id: "hz001341", palabra: "西湖", pinyin: "Xi1hu2", significado: " Lago del Oeste "},
{ id: "hz001342", palabra: "激动", pinyin: "ji1do4ng", significado: " emocionado "},
{ id: "hz001343", palabra: "流泪", pinyin: "liu2 le4i", significado: " lagrimear "},
{ id: "hz001344", palabra: "复杂", pinyin: "fu4za2", significado: " complicado "},
{ id: "hz001345", palabra: "负责", pinyin: "fu4ze2", significado: " encargarse deresponder"},
{ id: "hz001346", palabra: "公里", pinyin: "go1ngli3", significado: " clas. kilómetro "},
{ id: "hz001347", palabra: "公斤", pinyin: "go1ngji1n", significado: " clas. kilogramo "},
{ id: "hz001348", palabra: "不过", pinyin: "bu4guo4", significado: " pero "},
{ id: "hz001349", palabra: "差", pinyin: "cha4", significado: " no estar a la altura de..., distar de... "},
{ id: "hz001350", palabra: "老手", pinyin: "la3osho3u", significado: " veterano "},
{ id: "hz001351", palabra: "跳水", pinyin: "tia4oshui3", significado: " salto (de palanca) "},
{ id: "hz001352", palabra: "低", pinyin: "di1", significado: " bajo "},
{ id: "hz001353", palabra: "动作", pinyin: "do4ngzuo4", significado: " movimiento, acción "},
{ id: "hz001354", palabra: "难看", pinyin: "na2nka4n", significado: " feo "},
{ id: "hz001355", palabra: "强", pinyin: "qia2ng", significado: " mejor "},
{ id: "hz001356", palabra: "敢", pinyin: "ga3n", significado: " atreverse "},
{ id: "hz001357", palabra: "兴趣", pinyin: "xi4ngqu4", significado: " afición "},
{ id: "hz001358", palabra: "不但", pinyin: "bu4da4n", significado: " no sólo "},
{ id: "hz001359", palabra: "项目", pinyin: "xia4ngmu4", significado: " género "},
{ id: "hz001360", palabra: "乒乓球", pinyin: "pi1ngpa1ngqiu2", significado: " ping-pong "},
{ id: "hz001361", palabra: "篮球", pinyin: "la2nqiu2", significado: " baloncesto "},
{ id: "hz001362", palabra: "挺", pinyin: "ti3ng", significado: " muy, bastante "},
{ id: "hz001363", palabra: "广泛", pinyin: "gua3ngfa4n", significado: " amplio "},
{ id: "hz001364", palabra: "换", pinyin: "hua4n", significado: " cambiar "},
{ id: "hz001365", palabra: "活", pinyin: "huo2", significado: " vivo, vivir"},
{ id: "hz001366", palabra: "基础", pinyin: "ji1chu3", significado: " base "},
{ id: "hz001367", palabra: "集合", pinyin: "ji2he2", significado: " reunirse "},
{ id: "hz001368", palabra: "将来", pinyin: "jia1ngla2i", significado: " futuro "},
{ id: "hz001369", palabra: "交", pinyin: "jia1o", significado: " entregar "},
{ id: "hz001370", palabra: "脚", pinyin: "jia3o", significado: " pie"},
{ id: "hz001371", palabra: "被", pinyin: "be4i", significado: " (prep., signo de la voz pasiva) "},
{ id: "hz001372", palabra: "偷", pinyin: "to1u", significado: " robar "},
{ id: "hz001373", palabra: "发现", pinyin: "fa1xia4n", significado: " darse cuenta, advertir "},
{ id: "hz001374", palabra: "度假", pinyin: "du4jia4", significado: " pasar las vacaciones "},
{ id: "hz001375", palabra: "翻", pinyin: "fa1n", significado: " revolver "},
{ id: "hz001376", palabra: "乱七八糟", pinyin: "lua4nqi1ba1za1o", significado: " desordenado "},
{ id: "hz001377", palabra: "丢", pinyin: "diu1", significado: " perder "},
{ id: "hz001378", palabra: "首饰", pinyin: "sho3ushi4", significado: " joya, alhaja "},
{ id: "hz001379", palabra: "摄像机", pinyin: "she4xia4ngji1", significado: " videocámara "},
{ id: "hz001380", palabra: "别的", pinyin: "bie2de", significado: " otro "},
{ id: "hz001381", palabra: "花瓶", pinyin: "hua1pi2ng", significado: " florero "},
{ id: "hz001382", palabra: "破", pinyin: "po4", significado: " ruptura"},
{ id: "hz001383", palabra: "存折", pinyin: "cu2nzhe2", significado: " libreta de banco "},
{ id: "hz001384", palabra: "奇怪", pinyin: "qi2gua4i", significado: " extraño "},
{ id: "hz001385", palabra: "门", pinyin: "me2n", significado: " puerta "},
{ id: "hz001386", palabra: "小偷", pinyin: "xia3oto1u", significado: " ladrón "},
{ id: "hz001387", palabra: "搞", pinyin: "ga3o", significado: " hacer "},
{ id: "hz001388", palabra: "清楚", pinyin: "qi1ngchu", significado: " claro "},
{ id: "hz001389", palabra: "从", pinyin: "co2ng", significado: " desde, por "},
{ id: "hz001390", palabra: "窗户", pinyin: "chua1nghu4", significado: " ventana "},
{ id: "hz001391", palabra: "出门", pinyin: "chu1me2n", significado: " salir de casa "},
{ id: "hz001392", palabra: "关", pinyin: "gua1n", significado: " cerrar "},
{ id: "hz001393", palabra: "警察", pinyin: "ji3ngcha2", significado: " policía "},
{ id: "hz001394", palabra: "调查", pinyin: "dia4ocha2", significado: " investigar, indagar "},
{ id: "hz001395", palabra: "希望", pinyin: "xi1wa4ng", significado: " esperar "},
{ id: "hz001396", palabra: "尽快", pinyin: "ji3nkua4i", significado: " cuanto antes "},
{ id: "hz001397", palabra: "抓", pinyin: "zhua1", significado: " coger "},
{ id: "hz001398", palabra: "树", pinyin: "shu4", significado: " árbol "},
{ id: "hz001399", palabra: "刮", pinyin: "gua1", significado: " soplar "},
{ id: "hz001400", palabra: "倒", pinyin: "da3o", significado: " derribar "},
{ id: "hz001401", palabra: "吹", pinyin: "chui1", significado: " soplar "},
{ id: "hz001402", palabra: "治", pinyin: "zhi4", significado: " curar "},
{ id: "hz001403", palabra: "干净", pinyin: "ga1nji4ng", significado: " limpio "},
{ id: "hz001404", palabra: "表演", pinyin: "bia3oya3n", significado: " actuar "},
{ id: "hz001405", palabra: "外国", pinyin: "wa4iguo2", significado: " extranjero "},
{ id: "hz001406", palabra: "老外", pinyin: "la3owa4i", significado: " laowai "},
{ id: "hz001407", palabra: "意思", pinyin: "yi4si", significado: " significado, sentido "},
{ id: "hz001408", palabra: "简单", pinyin: "jia3nda1n", significado: " simple, sencillo "},
{ id: "hz001409", palabra: "脸谱", pinyin: "lia3npu3", significado: " maquillaje "},
{ id: "hz001410", palabra: "服装", pinyin: "fu2zhua1ng", significado: " vestimenta "},
{ id: "hz001411", palabra: "多", pinyin: "duo1", significado: " mucho "},
{ id: "hz001412", palabra: "怕", pinyin: "pa4", significado: " temer"},
{ id: "hz001413", palabra: "只要", pinyin: "zhi3ya4o", significado: " con tal de, con tal que "},
{ id: "hz001414", palabra: "学习班", pinyin: "xue2xi2ba1n", significado: " cursillo "},
{ id: "hz001415", palabra: "报名", pinyin: "ba4omi2ng", significado: " matricularse "},
{ id: "hz001416", palabra: "练", pinyin: "lia4n", significado: " ejercitarse, adiestrarse "},
{ id: "hz001417", palabra: "坚持", pinyin: "jia1nchi2", significado: " perseverar, persistir "},
{ id: "hz001418", palabra: "大卫", pinyin: "Da4we4i", significado: " David "},
{ id: "hz001419", palabra: "京剧", pinyin: "Ji1ngju4", significado: " ópera de Beijing "},
{ id: "hz001420", palabra: "山", pinyin: "sha1n", significado: " monte "},
{ id: "hz001421", palabra: "爬", pinyin: "pa2", significado: " escalar "},
{ id: "hz001422", palabra: "需要", pinyin: "xu1ya4o", significado: " necesitar "},
{ id: "hz001423", palabra: "热烈", pinyin: "re4lie4", significado: " cálido, caluroso "},
{ id: "hz001424", palabra: "经验", pinyin: "ji1ngya4n", significado: " experiencia "},
{ id: "hz001425", palabra: "旧", pinyin: "jiu4", significado: " viejo "},
{ id: "hz001426", palabra: "烤肉", pinyin: "ka3oro4u", significado: " carne asada "},
{ id: "hz001427", palabra: "涮羊肉", pinyin: "shua1nya2ngro4u", significado: " carne de cordero escalda en la mesa "},
{ id: "hz001428", palabra: "请客", pinyin: "qi3ngke4", significado: " invitar, ser anfitrión "},
{ id: "hz001429", palabra: "味道", pinyin: "we4i da4o", significado: " sabor "},
{ id: "hz001430", palabra: "半", pinyin: "ba4n", significado: " medio "},
{ id: "hz001431", palabra: "胃口", pinyin: "we4iko3u", significado: " apetito "},
{ id: "hz001432", palabra: "了", pinyin: "le", significado: " terminar de "},
{ id: "hz001433", palabra: "不光", pinyin: "bu4gua1ng", significado: " no sólo "},
{ id: "hz001434", palabra: "动", pinyin: "do4ng", significado: " usar, hacer uso de "},
{ id: "hz001435", palabra: "筷子", pinyin: "kua4izi", significado: " palillos "},
{ id: "hz001436", palabra: "动手", pinyin: "do4ngsho3u", significado: " hacer uso de las manos "},
{ id: "hz001437", palabra: "烧饼", pinyin: "sha1obi3ng", significado: " tortillas con semillas de sésamo "},
{ id: "hz001438", palabra: "吃法", pinyin: "chi1fa3", significado: " forma de comer "},
{ id: "hz001439", palabra: "独特", pinyin: "du2te4", significado: " peculiar "},
{ id: "hz001440", palabra: "围", pinyin: "we2i", significado: " rodear "},
{ id: "hz001441", palabra: "火锅", pinyin: "huo3guo1", significado: " caldero con fuego, caldero mongol "},
{ id: "hz001442", palabra: "涮", pinyin: "shua4n", significado: " escaldar "},
{ id: "hz001443", palabra: "鲜美", pinyin: "xia1nme3i", significado: " delicioso "},
{ id: "hz001444", palabra: "流", pinyin: "liu2", significado: " fluir, caer "},
{ id: "hz001445", palabra: "到处", pinyin: "da4o chu4", significado: " por todas partes "},
{ id: "hz001446", palabra: "品尝", pinyin: "pi3ncha2ng", significado: " probar, catar, degustar "},
{ id: "hz001447", palabra: "随时", pinyin: "sui2shi2", significado: " cuando quieras "},
{ id: "hz001448", palabra: "全聚德", pinyin: "Qua2nju4de2", significado: " Quanjude "},
{ id: "hz001449", palabra: "东来顺", pinyin: "Do1ngla2ishu4n", significado: " Donglaishun "},
{ id: "hz001450", palabra: "烤肉季", pinyin: "ka3oro4uji4", significado: " Asado de los Ji "},
{ id: "hz001451", palabra: "又袋", pinyin: "ko3uda4i", significado: " saco, bolsa "},
{ id: "hz001452", palabra: "客厅", pinyin: "ke4ti1ng", significado: " salo2n, sala de recibir "},
{ id: "hz001453", palabra: "米", pinyin: "mi3", significado: " metro "},
{ id: "hz001454", palabra: "化", pinyin: "hua4", significado: " gastar "},
{ id: "hz001455", palabra: "客气", pinyin: "ke4qi4", significado: " corte2s, cumplido "},
{ id: "hz001456", palabra: "空气", pinyin: "ko1ngqi4", significado: " aire "},
{ id: "hz001457", palabra: "信用卡", pinyin: "xi4nyo4ngka3", significado: " tarjeta de crédito"},
{ id: "hz001458", palabra: "普遍", pinyin: "pu3bia4n", significado: " común, generalizado"},
{ id: "hz001459", palabra: "大都", pinyin: "da4du1", significado: " en su mayoría"},
{ id: "hz001460", palabra: "而且", pinyin: "e2rqie3", significado: " sino, además"},
{ id: "hz001461", palabra: "安全", pinyin: "a1nqua2n", significado: " seguro"},
{ id: "hz001462", palabra: "连 .. 都", pinyin: "lia2n..do1u", significado: " incluso"},
{ id: "hz001463", palabra: "把", pinyin: "ba3", significado: " prep. para objeto directo adelantado"},
{ id: "hz001464", palabra: "钱包", pinyin: "qia2nba1o", significado: " billetero, portamonedas"},
{ id: "hz001465", palabra: "里面", pinyin: "li3mia4n", significado: " dentro"},
{ id: "hz001466", palabra: "急", pinyin: "ji2", significado: " inquieto, desasosegado"},
{ id: "hz001467", palabra: "坏", pinyin: "hua4i", significado: " malo"},
{ id: "hz001468", palabra: "当时", pinyin: "da1ngshi2", significado: " en aquel momento/tiempo"},
{ id: "hz001469", palabra: "着急", pinyin: "zha2oji2", significado: " estar como en ascuas"},
{ id: "hz001470", palabra: "名片", pinyin: "mi2ngpia4n", significado: " tarjeta personal"},
{ id: "hz001471", palabra: "该", pinyin: "ga1i", significado: " deber"},
{ id: "hz001472", palabra: "肯", pinyin: "ke3n", significado: " querer, acceder"},
{ id: "hz001473", palabra: "钢琴", pinyin: "ga1ngqi2n", significado: " piano"},
{ id: "hz001474", palabra: "弹", pinyin: "ta2n", significado: " tocar"},
{ id: "hz001475", palabra: "质量", pinyin: "zhi4lia4ng", significado: " calidad"},
{ id: "hz001476", palabra: "舒适", pinyin: "shu1shi4", significado: " cómodo, confortable"},
{ id: "hz001477", palabra: "夫人", pinyin: "fu1re2n", significado: " señora"},
{ id: "hz001478", palabra: "黑板", pinyin: "he1iba3n", significado: " encerado, pizarra"},
{ id: "hz001479", palabra: "教室", pinyin: "jia4oshi4", significado: " aula de clase"},
{ id: "hz001480", palabra: "做菜", pinyin: "zuo4 ca4i", significado: " guisar comida"},
{ id: "hz001481", palabra: "技术", pinyin: "ji4shu4", significado: " técnica, arte"},
{ id: "hz001482", palabra: "谈不上", pinyin: "ta2nbusha4ng", significado: " nada de (De técnica, nada)"},
{ id: "hz001483", palabra: "讲究", pinyin: "jia3ngjiu", significado: " delicado, exigente"},
{ id: "hz001484", palabra: "红烧鱼", pinyin: "ho2ngsha1o yu2", significado: " pescado estofado con salsa china"},
{ id: "hz001485", palabra: "虾", pinyin: "xia1", significado: " gamba, langostino"},
{ id: "hz001486", palabra: "煮", pinyin: "zhu3", significado: " cocer"},
{ id: "hz001487", palabra: "元宵", pinyin: "yua2nxia1o", significado: " yuanxiao (bolitas de arroz glutinoso rellenas de pasta azucarada)"},
{ id: "hz001488", palabra: "出洋相", pinyin: "chu1ya2ngxia4ng", significado: " quedar en ridículo"},
{ id: "hz001489", palabra: "别人", pinyin: "bie2re2n", significado: " los demás"},
{ id: "hz001490", palabra: "锅", pinyin: "guo1", significado: " caldera"},
{ id: "hz001491", palabra: "当", pinyin: "da1ng", significado: " tomar por"},
{ id: "hz001492", palabra: "雪白", pinyin: "xue3ba2i", significado: " de blancura nívea"},
{ id: "hz001493", palabra: "弄", pinyin: "no4ng", significado: " hacer"},
{ id: "hz001494", palabra: "糊涂", pinyin: "hu2tu", significado: " confuso"},
{ id: "hz001495", palabra: "后来", pinyin: "ho4ula2i", significado: " después"},
{ id: "hz001496", palabra: "特地", pinyin: "te4di4", significado: " de propio"},
{ id: "hz001497", palabra: "方法", pinyin: "fa1ngfa3", significado: " método"},
{ id: "hz001498", palabra: "容易", pinyin: "ro2ngyi4", significado: " fácil"},
{ id: "hz001499", palabra: "熟", pinyin: "shu2", significado: " cocido, hecho"},
{ id: "hz001500", palabra: "消息", pinyin: "xia1oxi", significado: " noticia"},
{ id: "hz001501", palabra: "炒", pinyin: "cha3o", significado: " saltear"},
{ id: "hz001502", palabra: "蒸", pinyin: "zhe1ng", significado: " cocer al vapor"},
{ id: "hz001503", palabra: "煎", pinyin: "jia1n", significado: " frei2r, sofreír"},
{ id: "hz001504", palabra: "饼干", pinyin: "bi3ngga1n", significado: " galleta"},
{ id: "hz001505", palabra: "蛋糕", pinyin: "da4nga1o", significado: " pastel, torta"},
{ id: "hz001506", palabra: "点心", pinyin: "dia3nxi1n", significado: " pasteles"},
{ id: "hz001507", palabra: "麻烦", pinyin: "ma2fan", significado: " complicado"},
{ id: "hz001508", palabra: "音乐", pinyin: "yi1nyue4", significado: "música"},
{ id: "hz001509", palabra: "帮", pinyin: "ba1ng", significado: "ayudar"},
{ id: "hz001510", palabra: "寄", pinyin: "ji4", significado: "enviar, mandar"},
{ id: "hz001511", palabra: "退休", pinyin: "tui4xiu1", significado: "jubilarse"},
{ id: "hz001512", palabra: "首先", pinyin: "sho3uxia1n", significado: "primero"},
{ id: "hz001513", palabra: "秋天", pinyin: "qiu1tia1n", significado: "otoño"},
{ id: "hz001514", palabra: "季节", pinyin: "ji4jie2", significado: "estación, temporada"},
{ id: "hz001515", palabra: "热", pinyin: "re4", significado: "cálido"},
{ id: "hz001516", palabra: "下雨", pinyin: "xia4yu3", significado: "llover"},
{ id: "hz001517", palabra: "建议", pinyin: "jia4nyi4", significado: "propuesta"},
{ id: "hz001518", palabra: "游览", pinyin: "yo2ula3n", significado: "recorrer, visitar"},
{ id: "hz001519", palabra: "导游", pinyin: "da3oyo2u", significado: "guía"},
{ id: "hz001520", palabra: "费劲", pinyin: "fe4iji4n", significado: "costar trabajo"},
{ id: "hz001521", palabra: "东南亚", pinyin: "Do1ngna2nya4", significado: "Sureste de Asia"},
{ id: "hz001522", palabra: "存", pinyin: "cu2n", significado: "depositar"},
{ id: "hz001523", palabra: "解决", pinyin: "jie3jue2", significado: "resolver"},
{ id: "hz001524", palabra: "文章", pinyin: "we2nzha1ng", significado: "escrito, artículo"},
{ id: "hz001525", palabra: "提高", pinyin: "ti2ga1o", significado: "elevar"},
{ id: "hz001526", palabra: "口语", pinyin: "ko3uyu3", significado: "expresión oral"},
{ id: "hz001527", palabra: "结束", pinyin: "jie2shu4", significado: "concluir"},
{ id: "hz001528", palabra: "举", pinyin: "ju3", significado: "enarbolar"},
{ id: "hz001529", palabra: "咳嗽", pinyin: "ke2so4u", significado: "toser"}
];
