export const libro01 = [
  { id: "hz000001", palabra: "是", pinyin: "shi4", significado: "ser" },
  { id: "hz000002", palabra: "哪", pinyin: "na3", significado: "¿cuál? ¿qué?" },
  { id: "hz000003", palabra: "国", pinyin: "guo2", significado: "país" },
  { id: "hz000004", palabra: "人", pinyin: "re2n", significado: "persona" },
  { id: "hz000005", palabra: "我", pinyin: "wo3", significado: "yo" },
  { id: "hz000006", palabra: "叫", pinyin: "jia4o", significado: "llamarse" },
  { id: "hz000007", palabra: "什么", pinyin: "she2n me0", significado: "¿qué?" },
  { id: "hz000008", palabra: "名字", pinyin: "mi2ng zi0", significado: "nombre" },
  { id: "hz000009", palabra: "欢迎", pinyin: "hua1n yi2ng", significado: "Bienvenido" },
  { id: "hz000010", palabra: "谢谢", pinyin: "xie4 xie0", significado: "Gracias" },
  { id: "hz000011", palabra: "西班牙", pinyin: "xi1 ba1n ya2", significado: "España" },
  { id: "hz000012", palabra: "马丁", pinyin: "ma3 di1ng", significado: "Martín" },
  { id: "hz000013", palabra: "这", pinyin: "zhe4", significado: "este" },
  { id: "hz000014", palabra: "谁", pinyin: "she2i", significado: "¿quién?" },
  { id: "hz000015", palabra: "爸爸", pinyin: "ba4 ba0", significado: "padre" },
  { id: "hz000016", palabra: "那", pinyin: "na4", significado: "ese, aquel" },
  { id: "hz000017", palabra: "妈妈", pinyin: "ma1 ma0", significado: "madre" },
  { id: "hz000018", palabra: "他们", pinyin: "ta1 men0", significado: "ellos" },
  { id: "hz000019", palabra: "身体", pinyin: "she1n ti3", significado: "salud" },
  { id: "hz000020", palabra: "吗", pinyin: "ma0", significado: "interrogación" },
  { id: "hz000021", palabra: "都", pinyin: "do1u", significado: "todos" },
  { id: "hz000022", palabra: "很", pinyin: "he3n", significado: "muy" },
  { id: "hz000023", palabra: "忙", pinyin: "ma2ng", significado: "ocupado" },
  { id: "hz000024", palabra: "李芳", pinyin: "li3 fa1ng", significado: "Li Fang" },
  { id: "hz000025", palabra: "玛利亚", pinyin: "ma3 li4 ya4", significado: "María" },
  { id: "hz000026", palabra: "请", pinyin: "qi3ng", significado: "solicitar" },
  { id: "hz000027", palabra: "坐", pinyin: "zuo4", significado: "sentarse" },
  { id: "hz000028", palabra: "的", pinyin: "de0", significado: "particula" },
  { id: "hz000029", palabra: "房间", pinyin: "fa2ng jia1n", significado: "habitación" },
  { id: "hz000030", palabra: "真", pinyin: "zhe1n", significado: "realmente, muy" },
  { id: "hz000031", palabra: "漂亮", pinyin: "pia4o liang", significado: "guapo" },
  { id: "hz000032", palabra: "要", pinyin: "ya4o", significado: "querer" },
  { id: "hz000033", palabra: "咖啡", pinyin: "ka1 fe1i", significado: "café" },
  { id: "hz000034", palabra: "不", pinyin: "bu4", significado: "no" },
  { id: "hz000035", palabra: "茶", pinyin: "cha2", significado: "té" },
  { id: "hz000036", palabra: "王大伟", pinyin: "wa2ng da4 we3i", significado: "Gran David" },
  { id: "hz000037", palabra: "住", pinyin: "zhu4", significado: "vivir" },
  { id: "hz000038", palabra: "哪儿", pinyin: "na3 er0", significado: "¿donde?" },
  { id: "hz000039", palabra: "楼", pinyin: "lo2u", significado: "edificio" },
  { id: "hz000040", palabra: "多少", pinyin: "duo1 shao0", significado: "¿cúanto?" },
  { id: "hz000041", palabra: "号", pinyin: "ha4o", significado: "número" },
  { id: "hz000042", palabra: "电话", pinyin: "dia4n hua4", significado: "número de teléfono" },
  { id: "hz000043", palabra: "号码", pinyin: "ha4o ma3", significado: "número" },
  { id: "hz000044", palabra: "呢", pinyin: "ne0", significado: "¿y el tuyo?" },
  {
    id: "hz000045",
    palabra: "名片",
    pinyin: "mi2ng pia4n",
    significado: "tarjeta de presentación",
  },
  {
    id: "hz000046",
    palabra: "北京大学",
    pinyin: "bei3 ji1ng da4 xue2",
    significado: "Universidad de Pekín",
  },
  { id: "hz000047", palabra: "请问", pinyin: "qi3ng w4en", significado: "dígmae por favor" },
  { id: "hz000048", palabra: "学校", pinyin: "xue2 xia4o", significado: "Uninversidad" },
  { id: "hz000049", palabra: "里边", pinyin: "li3 bian0", significado: "dentro de" },
  { id: "hz000050", palabra: "有", pinyin: "yo3u", significado: "haber" },
  { id: "hz000051", palabra: "餐厅", pinyin: "ca1n ti1ng", significado: "restaurante" },
  { id: "hz000052", palabra: "在", pinyin: "za4i", significado: "estar" },
  { id: "hz000053", palabra: "那 儿", pinyin: "na4 er0", significado: "allí" },
  { id: "hz000054", palabra: "没", pinyin: "me2i", significado: "no" },
  { id: "hz000055", palabra: "咖啡馆", pinyin: "ka1 fe1i gua3n", significado: "cafetería" },
  { id: "hz000056", palabra: "旁边", pinyin: "pa2ng bia1n", significado: "al lado de" },
  { id: "hz000057", palabra: "银行", pinyin: "yi2n ha2ng", significado: "banco" },
  { id: "hz000058", palabra: "点儿", pinyin: "dia3n er", significado: "Un poco de algo" },
  { id: "hz000059", palabra: "苹果", pinyin: "pi2ng guo3", significado: "manzana" },
  { id: "hz000060", palabra: "钱", pinyin: "qia2n", significado: "dinero" },
  { id: "hz000061", palabra: "斤", pinyin: "ji1n", significado: "unidad de peso (500gr)" },
  { id: "hz000062", palabra: "两", pinyin: "lia3ng", significado: "dos" },
  { id: "hz000063", palabra: "块", pinyin: "kua4i", significado: "yuan" },
  { id: "hz000064", palabra: "香蕉", pinyin: "xia1ng jia1o", significado: "plátano" },
  { id: "hz000065", palabra: "一共", pinyin: "yi2 go4ng", significado: "En total" },
  { id: "hz000066", palabra: "十二", pinyin: "shi2 e4r", significado: "Número 12" },
  { id: "hz000067", palabra: "服务员", pinyin: "fu2 wu4 yua2n", significado: "camarero" },
  { id: "hz000068", palabra: "先生", pinyin: "xia1n sheng0", significado: "caballero (Sr.)" },
  { id: "hz000069", palabra: "吃", pinyin: "chi1", significado: "comer" },
  { id: "hz000070", palabra: "饺子", pinyin: "jia3o zi0", significado: "empanadillas (dumpling)" },
  { id: "hz000071", palabra: "半", pinyin: "ba4n", significado: "mitad" },
  { id: "hz000072", palabra: "还", pinyin: "ha2i", significado: "aún, todavía más" },
  { id: "hz000073", palabra: "别的", pinyin: "bie2 de", significado: "otro (distinto)" },
  { id: "hz000074", palabra: "来", pinyin: "la2i", significado: "venir" },
  { id: "hz000075", palabra: "瓶", pinyin: "pi2ng", significado: "botella" },
  { id: "hz000076", palabra: "稍等", pinyin: "sha1o de3ng", significado: "(espere) un momento" },
  { id: "hz000077", palabra: "星期六", pinyin: "xi1ng qi1 liu4", significado: "sábado" },
  { id: "hz000078", palabra: "想", pinyin: "xia3ng", significado: "querer, desear" },
  { id: "hz000079", palabra: "去", pinyin: "qu4", significado: "ir" },
  { id: "hz000080", palabra: "远", pinyin: "yua3n", significado: "lejos" },
  { id: "hz000081", palabra: "比较", pinyin: "bi3 jia4o", significado: "bastante" },
  { id: "hz000082", palabra: "怎么", pinyin: "ze3n me0", significado: "¿Cómo?" },
  { id: "hz000083", palabra: "坐", pinyin: "zuo4", significado: "tomar (coger) un vehículo" },
  { id: "hz000084", palabra: "火车", pinyin: "huo3 che1", significado: "tren" },
  { id: "hz000085", palabra: "附近", pinyin: "fu4 ji4n", significado: "cerca de" },
  {
    id: "hz000086",
    palabra: "车站",
    pinyin: "che1 zha4n",
    significado: "Estación de (tren, autobus, etc)",
  },
  { id: "hz000087", palabra: "长城", pinyin: "cha2ng che2ng", significado: "Gran Muralla" },
  { id: "hz000088", palabra: "喂", pinyin: "we4i", significado: "¡Oye!" },
  { id: "hz000089", palabra: "你们", pinyin: "ni3 men0", significado: "vosotros" },
  { id: "hz000090", palabra: "我们", pinyin: "wo3 men0", significado: "nosotros" },
  { id: "hz000091", palabra: "也", pinyin: "ye3", significado: "también" },
  { id: "hz000092", palabra: "放心", pinyin: "fa4ng xi1n", significado: "preocupado" },
  { id: "hz000093", palabra: "吧", pinyin: "ba0", significado: "particula expletiva" },
  { id: "hz000094", palabra: "生活", pinyin: "she1ng huo2", significado: "vida, vivir" },
  { id: "hz000095", palabra: "习惯", pinyin: "xi2 gua4n", significado: "acostumbrarse" },
  { id: "hz000096", palabra: "没问题", pinyin: "me2i we4n ti2", significado: "No hay problema" },
  { id: "hz000097", palabra: "学习", pinyin: "xue2 xi2", significado: "estudiar" },
  { id: "hz000098", palabra: "多", pinyin: "duo1", significado: "mucho" },
  { id: "hz000099", palabra: "注意", pinyin: "zhu4 yi4", significado: "poner atención" },
  { id: "hz000100", palabra: "常", pinyin: "cha2ng", significado: "frecuente, a menudo" },
  { id: "hz000101", palabra: "打", pinyin: "da3", significado: "telefonear" },
  { id: "hz000102", palabra: "好的", pinyin: "ha3o de", significado: "de acuerdo, vale" },
  { id: "hz000103", palabra: "中国", pinyin: "zho1ng guo2", significado: "China" },
  { id: "hz000104", palabra: "你", pinyin: "ni3", significado: "tu" },
  { id: "hz000105", palabra: "好", pinyin: "ha3o", significado: "bueno" },
  { id: "hz000106", palabra: "学习", pinyin: "xue2 xi2", significado: "estudiar" },
  { id: "hz000107", palabra: "什么", pinyin: "she2n me0", significado: "que" },
  { id: "hz000108", palabra: "我", pinyin: "wo3", significado: "yo" },
  { id: "hz000109", palabra: "是", pinyin: "shi4", significado: "ser" },
  { id: "hz000110", palabra: "学生", pinyin: "xue2 sheng0", significado: "estudiante" },
  { id: "hz000111", palabra: "吗", pinyin: "ma0", significado: "particula expletiva" },
  { id: "hz000112", palabra: "对", pinyin: "dui4", significado: "correcto" },
  { id: "hz000113", palabra: "王大伟", pinyin: "wa2ng da4 we3i", significado: "Gran David" },
  { id: "hz000114", palabra: "马丁", pinyin: "ma3 ding1", significado: "Martín" },
  { id: "hz000115", palabra: "汉语", pinyin: "han4 yu3", significado: "chino (lengua)" },
  { id: "hz000116", palabra: "中国", pinyin: "zho1ng guo2", significado: "China" },
  {
    id: "hz000117",
    palabra: "西班牙语",
    pinyin: "xi1 ba1n ya2 yu3",
    significado: "español (idioma)",
  },
  { id: "hz000118", palabra: "墨西哥", pinyin: "mo4 xi1 ge1", significado: "México" },
  { id: "hz000119", palabra: "美国", pinyin: "me3i guo2", significado: "EEUU" },
  { id: "hz000120", palabra: "英国", pinyin: "yi1ng guo2", significado: "Reino Unido" },
  { id: "hz000121", palabra: "英语", pinyin: "yi1ng yu3", significado: "inglés" },
  { id: "hz000122", palabra: "加拿大", pinyin: "jia1 na2 da4", significado: "Canadá" },
  { id: "hz000123", palabra: "法国", pinyin: "fa3 guo2", significado: "Francia" },
  { id: "hz000124", palabra: "法语", pinyin: "fa3 yu3", significado: "francés" },
  { id: "hz000125", palabra: "徳国", pinyin: "de2 guo2", significado: "Alemania" },
  { id: "hz000126", palabra: "徳语", pinyin: "de2 yu3", significado: "alemán" },
  { id: "hz000127", palabra: "意大利", pinyin: "yi4 da4 li4", significado: "Italia" },
  { id: "hz000128", palabra: "俄罗斯", pinyin: "e2 luo2 si1", significado: "Rusia" },
  { id: "hz000129", palabra: "日本", pinyin: "ri4 be3n", significado: "Japón" },
  { id: "hz000130", palabra: "日语", pinyin: "ri4 yu3", significado: "japonés" },
  { id: "hz000131", palabra: "阿拉伯语", pinyin: "a1 la1 bo2 yu3", significado: "árabe" },
  { id: "hz000132", palabra: "这", pinyin: "zhe4", significado: "este" },
  { id: "hz000133", palabra: "她", pinyin: "ta1", significado: "ella" },
  { id: "hz000134", palabra: "朋友", pinyin: "pe2ng you0", significado: "amigo" },
  { id: "hz000135", palabra: "哪", pinyin: "na3", significado: "qué. Cuál" },
  { id: "hz000136", palabra: "国", pinyin: "guo2", significado: "país" },
  { id: "hz000137", palabra: "人", pinyin: "re2n", significado: "persona" },
  { id: "hz000138", palabra: "也", pinyin: "ye3", significado: "también" },
  { id: "hz000139", palabra: "不", pinyin: "bu4", significado: "no" },
  { id: "hz000140", palabra: "老师", pinyin: "la3o shi1", significado: "profesor" },
  { id: "hz000141", palabra: "教", pinyin: "jia1o", significado: "enseñar" },
  { id: "hz000142", palabra: "爱琳娜", pinyin: "a4i li2n na4", significado: "Elena" },
  { id: "hz000143", palabra: "我们", pinyin: "wo3 men", significado: "nosotros" },
  { id: "hz000144", palabra: "你们", pinyin: "ni3 men", significado: "vosotros" },
  { id: "hz000145", palabra: "他", pinyin: "ta1", significado: "el" },
  { id: "hz000146", palabra: "他们", pinyin: "ta1 men", significado: "ellos" },
  { id: "hz000147", palabra: "她", pinyin: "ta1", significado: "ella" },
  { id: "hz000148", palabra: "她们", pinyin: "ta1 men", significado: "ellas" },
  { id: "hz000149", palabra: "爸爸", pinyin: "ba4 ba0", significado: "papá" },
  { id: "hz000150", palabra: "妈妈", pinyin: "ma1 ma0", significado: "mamá" },
  { id: "hz000151", palabra: "在", pinyin: "za4i", significado: "en" },
  { id: "hz000152", palabra: "哪儿", pinyin: "na3 er0", significado: "dónde" },
  { id: "hz000153", palabra: "工作", pinyin: "go1ng zuo4", significado: "trabajar" },
  { id: "hz000154", palabra: "他", pinyin: "ta1", significado: "el" },
  { id: "hz000155", palabra: "医院", pinyin: "yi1 yua4n", significado: "hospital" },
  { id: "hz000156", palabra: "医生", pinyin: "yi1 she1ng", significado: "médico" },
  { id: "hz000157", palabra: "呢", pinyin: "ne0", significado: "partícula expletiva" },
  { id: "hz000158", palabra: "谁", pinyin: "she2i", significado: "quién" },
  { id: "hz000159", palabra: "姐姐", pinyin: "jie3 jie0", significado: "hermana mayor" },
  { id: "hz000160", palabra: "李芳", pinyin: "li3 fa1ng", significado: "Li Fang" },
  { id: "hz000161", palabra: "玛利亚", pinyin: "ma3 li4 ya4", significado: "María" },
  { id: "hz000162", palabra: "爷爷", pinyin: "ye2 ye0", significado: "Abuelo paterno" },
  { id: "hz000163", palabra: "奶奶", pinyin: "na3i nai0", significado: "Abuela paterna" },
  { id: "hz000164", palabra: "哥哥", pinyin: "ge1 ge0", significado: "hermano mayor" },
  { id: "hz000165", palabra: "弟弟", pinyin: "di4 di0", significado: "hermano menor" },
  { id: "hz000166", palabra: "妹妹", pinyin: "me4i mei0", significado: "hermana menor" },
  { id: "hz000167", palabra: "阿姨", pinyin: "a1 yi2", significado: "tia (hermana madre)" },
  {
    id: "hz000168",
    palabra: "叔叔",
    pinyin: "shu1 shu0",
    significado: "tio (hermano menor padre)",
  },
  {
    id: "hz000169",
    palabra: "教授",
    pinyin: "jia4o sho4u",
    significado: "profesor de universidad, catedrático",
  },
  { id: "hz000170", palabra: "系", pinyin: "xi4", significado: "facultad, departamento" },
  { id: "hz000171", palabra: "和", pinyin: "he2", significado: "y" },
  { id: "hz000172", palabra: "都", pinyin: "do1u", significado: "todos" },
  { id: "hz000173", palabra: "很", pinyin: "he3n", significado: "muy" },
  { id: "hz000174", palabra: "漂亮", pinyin: "pia4o liang0", significado: "guapa" },
  { id: "hz000175", palabra: "谢谢", pinyin: "xie4 xie0", significado: "agradecer" },
  { id: "hz000176", palabra: "叫", pinyin: "jia4o", significado: "llamarse" },
  { id: "hz000177", palabra: "名字", pinyin: "mi2ng zi0", significado: "nombre" },
  { id: "hz000178", palabra: "做", pinyin: "zuo4", significado: "hacer" },
  { id: "hz000179", palabra: "护士", pinyin: "hu4 shi0", significado: "enfermera" },
  { id: "hz000180", palabra: "忙", pinyin: "ma2ng", significado: "ocupado" },
  { id: "hz000181", palabra: "罗莎", pinyin: "luo2 sha1", significado: "Rosa" },
  { id: "hz000182", palabra: "教师", pinyin: "jia4o shi1", significado: "profesor" },
  { id: "hz000183", palabra: "工程师", pinyin: "go1ng che2ng shi1", significado: "ingeniero" },
  { id: "hz000184", palabra: "经理", pinyin: "ji1ng li3", significado: "gerente" },
  { id: "hz000185", palabra: "律师", pinyin: "lv4 shi1", significado: "abogado" },
  { id: "hz000186", palabra: "记者", pinyin: "yi4 zhe3", significado: "periodista" },
  { id: "hz000187", palabra: "编辑", pinyin: "bia1n yi2", significado: "editor" },
  { id: "hz000188", palabra: "演员", pinyin: "ya3n yua2n", significado: "actor" },
  { id: "hz000189", palabra: "公务员", pinyin: "go1ng wu4 yua2n", significado: "funcionario" },
  { id: "hz000190", palabra: "运动员", pinyin: "yu4n do4ng yua2n", significado: "deportista" },
  { id: "hz000191", palabra: "职员", pinyin: "zhi2 yua2n", significado: "empleado" },
  { id: "hz000192", palabra: "的", pinyin: "de0", significado: "partícula estructural" },
  { id: "hz000193", palabra: "衣服", pinyin: "yi1 fu0", significado: "ropa" },
  { id: "hz000194", palabra: "脏", pinyin: "za1ng", significado: "sucio" },
  { id: "hz000195", palabra: "别", pinyin: "bie2", significado: "no" },
  { id: "hz000196", palabra: "放", pinyin: "fa4ng", significado: "poner" },
  { id: "hz000197", palabra: "这儿", pinyin: "zhe4 er0", significado: "aquí" },
  { id: "hz000198", palabra: "洗衣机", pinyin: "xi3 yi1 ji1", significado: "lavadora" },
  { id: "hz000199", palabra: "里", pinyin: "li3", significado: "dentro" },
  { id: "hz000200", palabra: "那", pinyin: "na4", significado: "aquel" },
  { id: "hz000201", palabra: "裤子", pinyin: "ku4 zi0", significado: "pantalones" },
  { id: "hz000202", palabra: "弟弟", pinyin: "di4 di0", significado: "hermano menor" },
  { id: "hz000203", palabra: "夹克衫", pinyin: "jia1 ke4 sha1n", significado: "chaqueta" },
  { id: "hz000204", palabra: "大衣", pinyin: "da4 yi1", significado: "abrigo" },
  { id: "hz000205", palabra: "毛衣", pinyin: "ma2o yi1", significado: "jersey" },
  { id: "hz000206", palabra: "衬衣", pinyin: "che4n yi1", significado: "camisa" },
  { id: "hz000207", palabra: "T 恤衫", pinyin: "T0 xu4 sha1n", significado: "camiseta" },
  { id: "hz000208", palabra: "鞋", pinyin: "xie2", significado: "zapatos" },
  { id: "hz000209", palabra: "岁", pinyin: "sui4", significado: "años" },
  { id: "hz000210", palabra: "问", pinyin: "we4n", significado: "preguntar" },
  { id: "hz000211", palabra: "说", pinyin: "shuo1", significado: "decir" },
  { id: "hz000212", palabra: "帽子", pinyin: "ma4o zi0", significado: "sombrero" },
  { id: "hz000213", palabra: "裙子", pinyin: "qu2n zi0", significado: "falda" },
  { id: "hz000214", palabra: "喝", pinyin: "he1", significado: "beber" },
  { id: "hz000215", palabra: "茶", pinyin: "cha2", significado: "té" },
  { id: "hz000216", palabra: "咖啡", pinyin: "ka1 fe1", significado: "café" },
  { id: "hz000217", palabra: "还是", pinyin: "ha2i shi4", significado: "o" },
  { id: "hz000218", palabra: "有", pinyin: "yo3u", significado: "haber, tener" },
  { id: "hz000219", palabra: "可乐", pinyin: "ke3 le4", significado: "refresco de cola" },
  { id: "hz000220", palabra: "真", pinyin: "zhe1n", significado: "mucho, verdaderamente" },
  { id: "hz000221", palabra: "对不起", pinyin: "dui4 bu0 qi3", significado: "lo siento" },
  { id: "hz000222", palabra: "没", pinyin: "me2i", significado: "no" },
  { id: "hz000223", palabra: "王玲", pinyin: "wa2ng li2ng", significado: "Wang Ling" },
  { id: "hz000224", palabra: "张明", pinyin: "zha1ng mi2ng", significado: "Zhang Ming" },
  { id: "hz000225", palabra: "啤酒", pinyin: "pi2 jiu3", significado: "cerveza" },
  { id: "hz000226", palabra: "葡萄酒", pinyin: "pu2 ta2o jiu3", significado: "vino" },
  { id: "hz000227", palabra: "牛奶", pinyin: "niu2 na3i", significado: "leche" },
  { id: "hz000228", palabra: "矿泉水", pinyin: "kua4ng qua2n shui3", significado: "agua mineral" },
  { id: "hz000229", palabra: "冰水", pinyin: "bi1ng shui3", significado: "agua mineral" },
  { id: "hz000230", palabra: "冰激凌", pinyin: "bi1ng ji1 li2ng", significado: "helado" },
  { id: "hz000231", palabra: "面包", pinyin: "mia4n ba1o", significado: "pan" },
  { id: "hz000232", palabra: "鸡蛋", pinyin: "ji1 da4n", significado: "huevo" },
  { id: "hz000233", palabra: "果酱", pinyin: "guo3 jia4ng", significado: "mermelada" },
  { id: "hz000234", palabra: "奶酪", pinyin: "na3i la4o", significado: "queso" },
  { id: "hz000235", palabra: "商店", pinyin: "sha1ng dia4n", significado: "tienda" },
  { id: "hz000236", palabra: "学校", pinyin: "xue2 xia4o", significado: "colegio" },
  { id: "hz000237", palabra: "一", pinyin: "yi1", significado: "uno" },
  { id: "hz000238", palabra: "个", pinyin: "ge4", significado: "clasificador" },
  { id: "hz000239", palabra: "小", pinyin: "xia3o", significado: "pequeño" },
  { id: "hz000240", palabra: "附近", pinyin: "fu4 ji4n", significado: "cercania, alrededor" },
  { id: "hz000241", palabra: "大", pinyin: "da4", significado: "grande" },
  { id: "hz000242", palabra: "后边", pinyin: "ho4u bian0", significado: "detrás de" },
  { id: "hz000243", palabra: "那儿", pinyin: "na4 er0", significado: "allí" },
  { id: "hz000244", palabra: "水果", pinyin: "shui3 guo3", significado: "fruta" },
  { id: "hz000245", palabra: "贵", pinyin: "gui4", significado: "caro" },
  {
    id: "hz000246",
    palabra: "比较",
    pinyin: "bi3 jia4o",
    significado: "bastante, comparativamente",
  },
  { id: "hz000247", palabra: "但是", pinyin: "da4n shi4", significado: "pero" },
  { id: "hz000248", palabra: "我们", pinyin: "wo3 men0", significado: "nosotros" },
  { id: "hz000249", palabra: "去", pinyin: "qu4", significado: "ir" },
  { id: "hz000250", palabra: "买", pinyin: "ma3i", significado: "comprar" },
  { id: "hz000251", palabra: "吧", pinyin: "ba0", significado: "partícula expletiva" },
  { id: "hz000252", palabra: "苹果", pinyin: "pi2ng guo3", significado: "manzana" },
  { id: "hz000253", palabra: "香蕉", pinyin: "xia1ng jia1o", significado: "plátano" },
  { id: "hz000254", palabra: "西瓜", pinyin: "xi1 gua1", significado: "sandía" },
  { id: "hz000255", palabra: "葡萄", pinyin: "pu2 tao", significado: "uva" },
  { id: "hz000256", palabra: "橘子", pinyin: "ju2 zi0", significado: "naranja" },
  { id: "hz000257", palabra: "樱桃", pinyin: "yi1ng ta2o", significado: "cereza" },
  { id: "hz000258", palabra: "草莓", pinyin: "ca3o me2i", significado: "fresa" },
  { id: "hz000259", palabra: "柠檬", pinyin: "ni2ng me2ng", significado: "limón" },
  { id: "hz000260", palabra: "家", pinyin: "jia1", significado: "casa, familia" },
  { id: "hz000261", palabra: "常常", pinyin: "cha2ng cha2ng", significado: "frecuentemente" },
  { id: "hz000262", palabra: "手机", pinyin: "sho3u ji1", significado: "tlf. móvil" },
  { id: "hz000263", palabra: "多少", pinyin: "duo1 sha3o", significado: "¿cuánto?" },
  { id: "hz000264", palabra: "钱", pinyin: "qia2n", significado: "dinero?" },
  { id: "hz000265", palabra: "蓝色", pinyin: "la2n se4", significado: "azul" },
  { id: "hz000266", palabra: "两", pinyin: "lia3ng", significado: "dos" },
  { id: "hz000267", palabra: "千", pinyin: "qia1n", significado: "mil" },
  { id: "hz000268", palabra: "百", pinyin: "ba3i", significado: "cien" },
  { id: "hz000269", palabra: "块", pinyin: "kua4i", significado: "moneda (coloq.)" },
  { id: "hz000270", palabra: "太..了", pinyin: "ta4i .. le0", significado: "muy/demasiado" },
  { id: "hz000271", palabra: "灰色", pinyin: "hui1 se4", significado: "gris" },
  { id: "hz000272", palabra: "牌子", pinyin: "pa2i zi0", significado: "marca comercial" },
  { id: "hz000273", palabra: "黑色", pinyin: "he1i se4", significado: "negro" },
  { id: "hz000274", palabra: "白色", pinyin: "ba2i se4", significado: "blanco" },
  { id: "hz000275", palabra: "红色", pinyin: "ho2ng se4", significado: "rojo" },
  { id: "hz000276", palabra: "黄色", pinyin: "hua2ng se4", significado: "amarillo" },
  { id: "hz000277", palabra: "绿色", pinyin: "lv4 se4", significado: "verde" },
  { id: "hz000278", palabra: "咖啡色", pinyin: "ka1 fe1i se4", significado: "color café" },
  { id: "hz000279", palabra: "深色", pinyin: "she1n se4", significado: "color oscuro" },
  { id: "hz000280", palabra: "浅色", pinyin: "qia3n se4", significado: "color claro" },
  { id: "hz000281", palabra: "多", pinyin: "duo1", significado: "mucho" },
  { id: "hz000282", palabra: "种", pinyin: "zho3ng", significado: "(clasif.)" },
  { id: "hz000283", palabra: "想", pinyin: "xia3ng", significado: "pensar, desear" },
  { id: "hz000284", palabra: "租", pinyin: "zu1", significado: "alquilar" },
  { id: "hz000285", palabra: "套", pinyin: "ta4o", significado: "clasificador" },
  { id: "hz000286", palabra: "房子", pinyin: "fa2ng zi0", significado: "piso" },
  { id: "hz000287", palabra: "合适", pinyin: "he2 shi0", significado: "apropiado" },
  { id: "hz000288", palabra: "看", pinyin: "ka4n", significado: "ver" },
  { id: "hz000289", palabra: "怎么样", pinyin: "ze3n me0 ya4ng", significado: "qué tal" },
  { id: "hz000290", palabra: "太", pinyin: "ta4i", significado: "demasiado" },
  { id: "hz000291", palabra: "明天", pinyin: "mi2ng tia1n", significado: "mañana" },
  { id: "hz000292", palabra: "能", pinyin: "ne2ng", significado: "poder" },
  { id: "hz000293", palabra: "跟", pinyin: "ge1n", significado: "con" },
  { id: "hz000294", palabra: "一起", pinyin: "yi4 qi3", significado: "juntos" },
  { id: "hz000295", palabra: "餐厅", pinyin: "ca1n ti1ng", significado: "comedor" },
  { id: "hz000296", palabra: "客厅", pinyin: "ke4 ti1ng", significado: "salón" },
  { id: "hz000297", palabra: "卧室", pinyin: "wo4 shi4", significado: "dormitorio" },
  { id: "hz000298", palabra: "卫生间", pinyin: "we4i she1ng jia1n", significado: "lavabo" },
  { id: "hz000299", palabra: "沙发", pinyin: "sha1 fa1", significado: "sofá" },
  { id: "hz000300", palabra: "床", pinyin: "chua2ng", significado: "cama" },
  { id: "hz000301", palabra: "椅子", pinyin: "yi3 zi0", significado: "silla" },
  { id: "hz000302", palabra: "昨天", pinyin: "zuo2 tia1n", significado: "ayer" },
  { id: "hz000303", palabra: "房间", pinyin: "fa2ng jia1n", significado: "habitación" },
  { id: "hz000304", palabra: "房租", pinyin: "fa2ng zu1", significado: "alquiler" },
  { id: "hz000305", palabra: "小区", pinyin: "xia3o qu1", significado: "residencial" },
  { id: "hz000306", palabra: "啊", pinyin: "a0", significado: "partícula expletiva" },
  { id: "hz000307", palabra: "你们", pinyin: "ni3 men0", significado: "vosotros" },
  { id: "hz000308", palabra: "就", pinyin: "jiu4", significado: "justamente" },
  { id: "hz000309", palabra: "楼", pinyin: "lo2u", significado: "edificio" },
  { id: "hz000310", palabra: "几", pinyin: "ji3", significado: "¿cuántos?", undefined: "varios" },
  { id: "hz000311", palabra: "层", pinyin: "ce2ng", significado: "clasificador de piso" },
  { id: "hz000312", palabra: "交通", pinyin: "jia1o to1ng", significado: "comunicaciones" },
  { id: "hz000313", palabra: "方便", pinyin: "fa1ng bia4n", significado: "fácil" },
  { id: "hz000314", palabra: "那边", pinyin: "na4 bia1n", significado: "allí" },
  { id: "hz000315", palabra: "地铁站", pinyin: "di4 tie3 zha4n", significado: "estación de metro" },
  { id: "hz000316", palabra: "银行", pinyin: "yi2n ha2ng", significado: "banco" },
  { id: "hz000317", palabra: "上边", pinyin: "sha4ng bian0", significado: "arriba" },
  { id: "hz000318", palabra: "下边", pinyin: "xia4 bian", significado: "abajo" },
  { id: "hz000319", palabra: "里边", pinyin: "li3 bian", significado: "dentro" },
  { id: "hz000320", palabra: "外边", pinyin: "wa4i bian", significado: "fuera" },
  { id: "hz000321", palabra: "前边", pinyin: "quia2n bian", significado: "delante" },
  { id: "hz000322", palabra: "后边", pinyin: "ho4u bian", significado: "detrás" },
  { id: "hz000323", palabra: "左边", pinyin: "zuo3 bian", significado: "izquierda" },
  { id: "hz000324", palabra: "右边", pinyin: "yo4u bian", significado: "derecha" },
  { id: "hz000325", palabra: "中间", pinyin: "zho1ng jia1n", significado: "centro" },
  { id: "hz000326", palabra: "对面", pinyin: "dui4 mia4n", significado: "en frente" },
  { id: "hz000327", palabra: "照片", pinyin: "zha4o pia4n", significado: "fotografía" },
  { id: "hz000328", palabra: "后天", pinyin: "ho4u tia1n", significado: "pasado mañana" },
  { id: "hz000329", palabra: "生日", pinyin: "she1ng ri4", significado: "cumpleaños" },
  { id: "hz000330", palabra: "请", pinyin: "qi3ng", significado: "invitar" },
  { id: "hz000331", palabra: "参加", pinyin: "ca1n jia1", significado: "participar" },
  { id: "hz000332", palabra: "晚会", pinyin: "wa3n hui4", significado: "fiesta" },
  { id: "hz000333", palabra: "号", pinyin: "ha4o", significado: "día, número" },
  { id: "hz000334", palabra: "月", pinyin: "yue4", significado: "mes" },
  { id: "hz000335", palabra: "星期", pinyin: "xi1ng qi1", significado: "semana" },
  { id: "hz000336", palabra: "晚上", pinyin: "wa3n shang0", significado: "noche" },
  { id: "hz000337", palabra: "时间", pinyin: "shi2 jia1n", significado: "tiempo" },
  { id: "hz000338", palabra: "点", pinyin: "dia3n", significado: "hora" },
  { id: "hz000339", palabra: "开始", pinyin: "ka1i shi3", significado: "comenzar" },
  { id: "hz000340", palabra: "半", pinyin: "ba4n", significado: "medio" },
  { id: "hz000341", palabra: "一定", pinyin: "yi2 di4ng", significado: "sin falta" },
  { id: "hz000342", palabra: "来", pinyin: "la2i", significado: "venir" },
  { id: "hz000343", palabra: "今年", pinyin: "ji1n nia2n", significado: "este año" },
  { id: "hz000344", palabra: "多", pinyin: "duo1", significado: "cuánto" },
  { id: "hz000345", palabra: "属", pinyin: "shu3", significado: "corresponder horóscopo chino" },
  { id: "hz000346", palabra: "年", pinyin: "nia2n", significado: "año" },
  { id: "hz000347", palabra: "出生", pinyin: "chu1 she1ng", significado: "nacer" },
  { id: "hz000348", palabra: "啊", pinyin: "a2", significado: "ah!" },
  { id: "hz000349", palabra: "俩", pinyin: "lia3", significado: "(ambos) dos" },
  { id: "hz000350", palabra: "铜", pinyin: "to2ng", significado: "ser (de) igual, (el) mismo" },
  { id: "hz000351", palabra: "岁", pinyin: "sui4", significado: "edad, años" },
  { id: "hz000352", palabra: "鼠", pinyin: "shu3", significado: "ratón" },
  { id: "hz000353", palabra: "牛", pinyin: "niu2", significado: "buey" },
  { id: "hz000354", palabra: "虎", pinyin: "hu3", significado: "tigre" },
  { id: "hz000355", palabra: "兔", pinyin: "tu4", significado: "conejo" },
  { id: "hz000356", palabra: "龙", pinyin: "lo3ng", significado: "dragón" },
  { id: "hz000357", palabra: "蛇", pinyin: "she2", significado: "serpiente" },
  { id: "hz000358", palabra: "马", pinyin: "ma3", significado: "caballo" },
  { id: "hz000359", palabra: "羊", pinyin: "ya2ng", significado: "carnero" },
  { id: "hz000360", palabra: "猴", pinyin: "ho2u", significado: "mono" },
  { id: "hz000361", palabra: "鸡", pinyin: "ji1", significado: "gallo" },
  { id: "hz000362", palabra: "狗", pinyin: "go3u", significado: "perro" },
  { id: "hz000363", palabra: "猪", pinyin: "zhu1", significado: "cerdo" },
  { id: "hz000364", palabra: "圣诞节", pinyin: "She4ng da4n jie2", significado: "Navidad" },
  { id: "hz000365", palabra: "现在", pinyin: "xia4n za4i", significado: "ahora" },
  { id: "hz000366", palabra: "了", pinyin: "le0", significado: "part" },
  { id: "hz000367", palabra: "零", pinyin: "li2ng", significado: "part" },
  { id: "hz000368", palabra: "分", pinyin: "fe1n", significado: "minuto" },
  { id: "hz000369", palabra: "早", pinyin: "za3o", significado: "temprano" },
  { id: "hz000370", palabra: "得", pinyin: "de3i", significado: "tener" },
  { id: "hz000371", palabra: "走", pinyin: "zo3u", significado: "caminar" },
  { id: "hz000372", palabra: "着急", pinyin: "zha2o ji2", significado: "preocupado" },
  { id: "hz000373", palabra: "还", pinyin: "ha2i", significado: "todavía" },
  { id: "hz000374", palabra: "上课", pinyin: "sha4ng ke4", significado: "tener clase" },
  { id: "hz000375", palabra: "没关系", pinyin: "me2i gua1n xi0", significado: "no importa" },
  { id: "hz000376", palabra: "每(天)", pinyin: "me3i (tia1n)", significado: "cada (día)" },
  { id: "hz000377", palabra: "才", pinyin: "ca2i", significado: "pronto" },
  { id: "hz000378", palabra: "睡觉", pinyin: "shui4 jia4o", significado: "dormir" },
  { id: "hz000379", palabra: "这么", pinyin: "zhe4 me", significado: "tan" },
  { id: "hz000380", palabra: "晚", pinyin: "wa3n", significado: "tarde" },
  { id: "hz000381", palabra: "早上", pinyin: "za3o shang0", significado: "mañana temprano" },
  { id: "hz000382", palabra: "起床", pinyin: "qi3 chua2ng", significado: "despertarse" },
  { id: "hz000383", palabra: "觉得", pinyin: "jue2 de0", significado: "parecer" },
  { id: "hz000384", palabra: "要", pinyin: "ya4o", significado: "querer" },
  { id: "hz000385", palabra: "问", pinyin: "we4n", significado: "preguntar" },
  { id: "hz000386", palabra: "前天", pinyin: "qia2n tia1n", significado: "anteayer" },
  { id: "hz000387", palabra: "昨天", pinyin: "zuo2 tian1", significado: "ayer" },
  { id: "hz000388", palabra: "今天", pinyin: "jin1 tian1", significado: "hoy" },
  { id: "hz000389", palabra: "上午", pinyin: "sha4ng wu3", significado: "mañana" },
  { id: "hz000390", palabra: "中午", pinyin: "zho1ng wu3", significado: "mediodía" },
  { id: "hz000391", palabra: "下午", pinyin: "xia4 wu3", significado: "tarde" },
  { id: "hz000392", palabra: "下课", pinyin: "xia4 ke4", significado: "salir de clase" },
  { id: "hz000393", palabra: "请假", pinyin: "qi3n jia4", significado: "pedir permiso" },
  { id: "hz000394", palabra: "迟到", pinyin: "chi2 da4o", significado: "llegar tarde" },
  { id: "hz000395", palabra: "同", pinyin: "to2ng wu1", significado: "compañero" },
  { id: "hz000396", palabra: "办公室", pinyin: "ba4n go1ng shi4", significado: "oficina" },
  { id: "hz000397", palabra: "张", pinyin: "zha1ng", significado: "clasif. (plano)" },
  { id: "hz000398", palabra: "桌子", pinyin: "zhuo1 zi0", significado: "clasif. (plano)" },
  { id: "hz000399", palabra: "他们", pinyin: "ta1 men0", significado: "ellos" },
  { id: "hz000400", palabra: "台", pinyin: "ta2i", significado: "clasif. (dispositivos grandes)" },
  { id: "hz000401", palabra: "部", pinyin: "bu4", significado: "clasif. (dispositivos pequeños)" },
  { id: "hz000402", palabra: "电脑", pinyin: "dia4n na3o", significado: "ordenador" },
  { id: "hz000403", palabra: "电话", pinyin: "dia4n hua4", significado: "teléfono" },
  { id: "hz000404", palabra: "传真机", pinyin: "chua2n zhe1n ji1", significado: "fax" },
  { id: "hz000405", palabra: "复印机", pinyin: "fu4 yi4n ji1", significado: "fotocopiadora" },
  { id: "hz000406", palabra: "旁边", pinyin: "pa2ng bia1n", significado: "al lado" },
  { id: "hz000407", palabra: "沙发", pinyin: "sha1 fa1", significado: "sofá" },
  {
    id: "hz000408",
    palabra: "条件",
    pinyin: "tia2o jia4n",
    significado: "condiciones (económicas)",
  },
  { id: "hz000409", palabra: "不错", pinyin: "bu2 cuo4", significado: "correcto, muy bueno" },
  { id: "hz000410", palabra: "画儿", pinyin: "hua4 er0", significado: "cuadro" },
  { id: "hz000411", palabra: "匹", pinyin: "pi3", significado: "clasif. (caballo)" },
  { id: "hz000412", palabra: "文件", pinyin: "we2n jia4n", significado: "documento" },
  { id: "hz000413", palabra: "公文包", pinyin: "go1ng we2n ba1o", significado: "portafolio" },
  { id: "hz000414", palabra: "钢笔", pinyin: "ga1ng bi3", significado: "pluma estilográfica" },
  { id: "hz000415", palabra: "圆珠笔", pinyin: "yua2nz hu1 bi3", significado: "bolígrafo" },
  { id: "hz000416", palabra: "铅笔", pinyin: "qia1n bi3", significado: "lápiz" },
  { id: "hz000417", palabra: "签字笔", pinyin: "qia1n zi4 bi3", significado: "bolígrafo (firmar)" },
  { id: "hz000418", palabra: "打印机", pinyin: "da3 yi4n ji1", significado: "impresora" },
  { id: "hz000419", palabra: "扫描仪", pinyin: "sa3o mia2o yi2", significado: "escáner" },
  {
    id: "hz000420",
    palabra: "无绳电话",
    pinyin: "wu2 she2ng dia4n hua4",
    significado: "teléfono inalámbrico",
  },
  { id: "hz000421", palabra: "电话簿", pinyin: "dia4n hua4 bu4", significado: "listín telefónico" },
  { id: "hz000422", palabra: "最近", pinyin: "zui4 ji4n", significado: "últimamente" },
  { id: "hz000423", palabra: "刚", pinyin: "ga1ng", significado: "apenas, recién" },
  {
    id: "hz000424",
    palabra: "时候",
    pinyin: "shi2 hou0",
    significado: "momento",
    undefined: "+ cuando",
  },
  { id: "hz000425", palabra: "有点儿", pinyin: "yo3u dia3n er0", significado: "algo, un poco" },
  { id: "hz000426", palabra: "紧张", pinyin: "ji3n zha1ng", significado: "nervioso" },
  { id: "hz000427", palabra: "一点儿", pinyin: "yi4 dia3n er0", significado: "un poco" },
  { id: "hz000428", palabra: "天气", pinyin: "tia1n qi4", significado: "tiempo atmosférico" },
  { id: "hz000429", palabra: "习惯", pinyin: "xi2 gua4n", significado: "acostumbrarse" },
  { id: "hz000430", palabra: "冬天", pinyin: "do1ng tia1n", significado: "invierno" },
  { id: "hz000431", palabra: "冷", pinyin: "le3ng", significado: "frío" },
  { id: "hz000432", palabra: "菜", pinyin: "ca4i", significado: "comida, plato" },
  { id: "hz000433", palabra: "吃", pinyin: "chi1", significado: "comer" },
  { id: "hz000434", palabra: "喜欢", pinyin: "xi3 huan0", significado: "gustar" },
  {
    id: "hz000435",
    palabra: "看起来",
    pinyin: "ka4n4qi3 la2i",
    significado: "parecer, por los que se (te) ve",
  },
  { id: "hz000436", palabra: "脸色", pinyin: "lia3n se4", significado: "aspecto físico" },
  { id: "hz000437", palabra: "累", pinyin: "le4i", significado: "cansado" },
  { id: "hz000438", palabra: "走", pinyin: "zo3u", significado: "ir" },
  { id: "hz000439", palabra: "何赛", pinyin: "He2 sa4i", significado: "José" },
  { id: "hz000440", palabra: "北京", pinyin: "be3i ji1ng", significado: "Beijing" },
  { id: "hz000441", palabra: "春天", pinyin: "chu1n tia1n", significado: "primavera" },
  { id: "hz000442", palabra: "夏天", pinyin: "xia4 tia1n", significado: "verano" },
  { id: "hz000443", palabra: "秋天", pinyin: "qiu1 tia1n", significado: "otoño" },
  { id: "hz000444", palabra: "凉快", pinyin: "lia2ng kuai0", significado: "fresco" },
  { id: "hz000445", palabra: "热", pinyin: "re4", significado: "cálido" },
  { id: "hz000446", palabra: "暖和", pinyin: "nua3n huo0", significado: "templado" },
  { id: "hz000447", palabra: "下雨", pinyin: "xia4 yu3", significado: "llover" },
  { id: "hz000448", palabra: "下雪", pinyin: "xia2 xue3", significado: "nevar" },
  { id: "hz000449", palabra: "刮风", pinyin: "gua1 fe1ng", significado: "soplar viento" },
  { id: "hz000450", palabra: "病", pinyin: "bi4ng", significado: "estar enfermo" },
  { id: "hz000451", palabra: "嗓子", pinyin: "sa3ng zi0", significado: "garganta" },
  { id: "hz000452", palabra: "疼", pinyin: "te2ng", significado: "doler" },
  { id: "hz000453", palabra: "可能", pinyin: "ke3 ne2ng", significado: "quizás" },
  { id: "hz000454", palabra: "感冒", pinyin: "ga3n ma4o", significado: "resfriarse" },
  { id: "hz000455", palabra: "发烧", pinyin: "fa1 sha1o", significado: "tener fiebre" },
  { id: "hz000456", palabra: "不用", pinyin: "bu2 yo4ng", significado: "no ser necesario" },
  { id: "hz000457", palabra: "药", pinyin: "ya4o", significado: "medicina" },
  {
    id: "hz000458",
    palabra: "身体",
    pinyin: "she1n ti3",
    significado: "cuerpo",
    undefined: "salud",
  },
  { id: "hz000459", palabra: "只是", pinyin: "zhi3 shi4", significado: "sólo que, simplemente" },
  { id: "hz000460", palabra: "家", pinyin: "jia1", significado: "casa, familia, especialista" },
  { id: "hz000461", palabra: "办法", pinyin: "ba4n fa3", significado: "solución, método" },
  { id: "hz000462", palabra: "餐厅", pinyin: "ca1n ti1ng", significado: "restaurante" },
  { id: "hz000463", palabra: "头疼", pinyin: "to2u te2ng", significado: "dolor de cabeza" },
  { id: "hz000464", palabra: "咳嗽", pinyin: "ke2 sou0", significado: "tos, toser" },
  { id: "hz000465", palabra: "胃疼", pinyin: "we4i te2ng", significado: "dolor de estómago" },
  { id: "hz000466", palabra: "牙疼", pinyin: "ya2 te2ng", significado: "dolor de dientes" },
  { id: "hz000467", palabra: "拉肚子", pinyin: "la1 du4 zi0", significado: "diarrea" },
  { id: "hz000468", palabra: "失眠", pinyin: "shi1 mia2n", significado: "insomnio" },
  {
    id: "hz000469",
    palabra: "挂号",
    pinyin: "gua4 ha4o",
    significado: "registrarse en un hospital",
  },
  {
    id: "hz000470",
    palabra: "内科",
    pinyin: "ne4i ke1",
    significado: "medicina interna (general)",
  },
  { id: "hz000471", palabra: "外科", pinyin: "wa4i ke1", significado: "cirujía" },
  { id: "hz000472", palabra: "大夫", pinyin: "da4i fu0", significado: "doctor" },
  { id: "hz000473", palabra: "头", pinyin: "to2u", significado: "cabeza" },
  { id: "hz000474", palabra: "全身", pinyin: "qua2n she1n", significado: "todo el cuerp" },
  { id: "hz000475", palabra: "不舒服", pinyin: "bu4 shu1 fu0", significado: "indispuesto" },
  { id: "hz000476", palabra: "给", pinyin: "ge3i", significado: "a" },
  { id: "hz000477", palabra: "检查", pinyin: "jia3n cha2", significado: "examinar" },
  { id: "hz000478", palabra: "问题", pinyin: "we4n ti2", significado: "problema" },
  { id: "hz000479", palabra: "常常", pinyin: "cha2ng cha2ng", significado: "frecuentemente" },
  { id: "hz000480", palabra: "加班", pinyin: "jia1 ba1n", significado: "trabajar horas extras" },
  { id: "hz000481", palabra: "锻炼", pinyin: "dua4n lia4n", significado: "hacer ejercicio físico" },
  { id: "hz000482", palabra: "应该", pinyin: "yi1ng ga1i", significado: "deber" },
  { id: "hz000483", palabra: "对", pinyin: "dui4", significado: "para" },
  { id: "hz000484", palabra: "好处", pinyin: "ha3o chu0", significado: "ventaja, beneficio" },
  { id: "hz000485", palabra: "重要", pinyin: "zho4ng ya4o", significado: "importante" },
  { id: "hz000486", palabra: "眼睛", pinyin: "ya3n jing0", significado: "ojos" },
  { id: "hz000487", palabra: "鼻子", pinyin: "bi2 zi0", significado: "nariz" },
  { id: "hz000488", palabra: "嘴", pinyin: "zui3", significado: "boca" },
  { id: "hz000489", palabra: "耳朵", pinyin: "e3r duo0", significado: "oreja" },
  { id: "hz000490", palabra: "脸", pinyin: "lia3n", significado: "cara" },
  { id: "hz000491", palabra: "手", pinyin: "sho3u", significado: "mano" },
  { id: "hz000492", palabra: "脚", pinyin: "jia3o", significado: "pie" },
  { id: "hz000493", palabra: "运动", pinyin: "yu4n do4ng", significado: "deporte, hacer deporte" },
  { id: "hz000494", palabra: "请问", pinyin: "qi3ng we4n", significado: "Por favor" },
  { id: "hz000495", palabra: "好久", pinyin: "ha3o jiu3", significado: "Hace mucho que" },
  { id: "hz000496", palabra: "见", pinyin: "jia4n", significado: "ver" },
  { id: "hz000497", palabra: "马马虎虎", pinyin: "ma3 ma3 hu1 hu1", significado: "regular" },
  { id: "hz000498", palabra: "搬", pinyin: "ba1n", significado: "mover, trasladar" },
  { id: "hz000499", palabra: "玩儿", pinyin: "wa2n er0", significado: "divertirse" },
  { id: "hz000500", palabra: "行", pinyin: "xi2ng", significado: "bien, vale" },
  { id: "hz000501", palabra: "聊天儿", pinyin: "lia2o tia1nr", significado: "charlar" },
  { id: "hz000502", palabra: "等", pinyin: "de3ng", significado: "esperar" },
  { id: "hz000503", palabra: "这样", pinyin: "zhe4 ya4ng", significado: "así" },
  { id: "hz000504", palabra: "再见", pinyin: "za4i jia4n", significado: "adios" },
  { id: "hz000505", palabra: "告诉", pinyin: "ga4o su4", significado: "decir" },
  { id: "hz000506", palabra: "地址", pinyin: "di4 zhi3", significado: "dirección (domicilio)" },
  { id: "hz000507", palabra: "喂", pinyin: "we4i", significado: "¡oye! ¡eh!" },
  { id: "hz000508", palabra: "赵小英", pinyin: "Zha4o Xia3o yi1ng", significado: "Zhao Xiao Ying" },
  { id: "hz000509", palabra: "唱歌", pinyin: "cha4ng ge1", significado: "cantar (una canción)" },
  { id: "hz000510", palabra: "跳舞", pinyin: "tia4o wu3", significado: "bailar (un baile)" },
  { id: "hz000511", palabra: "听音乐", pinyin: "ti1ng yi1n yue4", significado: "escuchar música" },
  { id: "hz000512", palabra: "下棋", pinyin: "xia4 qi2", significado: "jugar al ajedrez" },
  { id: "hz000513", palabra: "打扑克", pinyin: "da3 pu1 ke4", significado: "jugar al póker" },
  { id: "hz000514", palabra: "看碟", pinyin: "ka4n die2", significado: "ver un videodisco" },
  {
    id: "hz000515",
    palabra: "看录像",
    pinyin: "ka4n lu4 xia4ng",
    significado: "ver una videocinta",
  },
  { id: "hz000516", palabra: "下午", pinyin: "xia4 wu3", significado: "la tarde" },
  { id: "hz000517", palabra: "逛", pinyin: "gua4ng", significado: "pasear" },
  { id: "hz000518", palabra: "打", pinyin: "da3", significado: "dar, golpear, llamar" },
  { id: "hz000519", palabra: "次", pinyin: "ci4", significado: "vez" },
  { id: "hz000520", palabra: "事儿", pinyin: "shi4r", significado: "asunto" },
  { id: "hz000521", palabra: "让", pinyin: "ra4ng", significado: "pedir, invitar" },
  { id: "hz000522", palabra: "忘", pinyin: "wa4ng", significado: "olvidar" },
  { id: "hz000523", palabra: "知道", pinyin: "zhi1 da4o", significado: "saber" },
  { id: "hz000524", palabra: "号码", pinyin: "ha4o ma3", significado: "número" },
  { id: "hz000525", palabra: "昨天", pinyin: "zuo2 tia1n", significado: "ayer" },
  { id: "hz000526", palabra: "挂", pinyin: "gua4", significado: "colgar" },
  { id: "hz000527", palabra: "门口", pinyin: "me2n ko3u", significado: "entrada" },
  { id: "hz000528", palabra: "件", pinyin: "jia4n", significado: "clas. ropa" },
  { id: "hz000529", palabra: "毛衣", pinyin: "ma3o yi1", significado: "jersey" },
  { id: "hz000530", palabra: "顶", pinyin: "di3ng", significado: "clas. sombreros" },
  { id: "hz000531", palabra: "帽子", pinyin: "ma4o zi", significado: "sombrero" },
  { id: "hz000532", palabra: "条", pinyin: "tia2o", significado: "clas. cosas largas y delgadas" },
  { id: "hz000533", palabra: "围巾", pinyin: "we2i ji1n", significado: "bufanda" },
  {
    id: "hz000534",
    palabra: "身份证号码",
    pinyin: "she1n fe4n zhe4ng ha4o ma3",
    significado: "Número Carnet de Identidad",
  },
  {
    id: "hz000535",
    palabra: "门牌号码",
    pinyin: "me2n pa2i ha4o ma3",
    significado: "Número de puerta",
  },
  {
    id: "hz000536",
    palabra: "房间号码",
    pinyin: "fa2ng jia1n ha4o ma3",
    significado: "Número de habitación",
  },
  {
    id: "hz000537",
    palabra: "信用卡号码",
    pinyin: "xi4n yo4ng ka3 ha4o ma3",
    significado: "Número de tarjeta de crédito",
  },
  {
    id: "hz000538",
    palabra: "驾照号码",
    pinyin: "jia4 zha4o ha4o ma3",
    significado: "Número de carnet de conducir",
  },
  { id: "hz000539", palabra: "在", pinyin: "za4i", significado: "estar (+gerundio)" },
  { id: "hz000540", palabra: "书", pinyin: "shu1", significado: "libro" },
  { id: "hz000541", palabra: "呀", pinyin: "ya0", significado: "particula expletiva" },
  { id: "hz000542", palabra: "正", pinyin: "zhe4ng", significado: "justamente" },
  { id: "hz000543", palabra: "说", pinyin: "shuo1", significado: "decir" },
  { id: "hz000544", palabra: "打算", pinyin: "da3 suan0", significado: "planear" },
  { id: "hz000545", palabra: "下", pinyin: "xia4", significado: "próximo" },
  { id: "hz000546", palabra: "假", pinyin: "jia4", significado: "vacaciones" },
  { id: "hz000547", palabra: "飞机", pinyin: "fe1i ji1", significado: "avión" },
  { id: "hz000548", palabra: "票", pinyin: "pia4o", significado: "billete" },
  { id: "hz000549", palabra: "正在", pinyin: "zhe4ng za4i", significado: "justamente" },
  { id: "hz000550", palabra: "考试", pinyin: "ka3o shi4", significado: "tener exámenes" },
  { id: "hz000551", palabra: "担心", pinyin: "da1n xi1n", significado: "temer, preocuparse" },
  { id: "hz000552", palabra: "陪", pinyin: "pe2i", significado: "acompañar" },
  { id: "hz000553", palabra: "可以", pinyin: "ke3 yi3", significado: "poder" },
  { id: "hz000554", palabra: "到", pinyin: "da4o", significado: "llegar" },
  { id: "hz000555", palabra: "接", pinyin: "jie1", significado: "recibir" },
  { id: "hz000556", palabra: "维克多", pinyin: "we2i ke4 duo1", significado: "Víctor" },
  { id: "hz000557", palabra: "前年", pinyin: "qia2n nia2n", significado: "hace dos años" },
  { id: "hz000558", palabra: "去年", pinyin: "qu4 nia2n", significado: "el año pasado" },
  { id: "hz000559", palabra: "今年", pinyin: "ji1n nia2n", significado: "este año" },
  { id: "hz000560", palabra: "明年", pinyin: "mi2ng nia2n", significado: "el próximo año" },
  { id: "hz000561", palabra: "后年", pinyin: "ho4u nia2n", significado: "dentro de dos años" },
  { id: "hz000562", palabra: "上个月", pinyin: "sha4ng ge4 yue4", significado: "el mes pasado" },
  { id: "hz000563", palabra: "这个月", pinyin: "zhe4 ge4 yue4", significado: "este mes" },
  { id: "hz000564", palabra: "下个月", pinyin: "xia4 ge4 yue4", significado: "el próximo mes" },
  {
    id: "hz000565",
    palabra: "上星期",
    pinyin: "sha4ng xi1ng qi1",
    significado: "la semana pasada",
  },
  { id: "hz000566", palabra: "这星期", pinyin: "zhe4 xi1ng qi1", significado: "esta semana" },
  { id: "hz000567", palabra: "下星期", pinyin: "xia4 xi1ng qi1", significado: "la próxima semana" },
  { id: "hz000568", palabra: "快", pinyin: "kua4i", significado: "rápido, pronto" },
  { id: "hz000569", palabra: "要。了", pinyin: "ya4o 0 le0", significado: "ir a" },
  { id: "hz000570", palabra: "迟到", pinyin: "chi2 da4o", significado: "llegar tarde" },
  { id: "hz000571", palabra: "来得及", pinyin: "la2i de0 ji2", significado: "hay tiempo" },
  { id: "hz000572", palabra: "分钟", pinyin: "fe1n zho1ng", significado: "minuto" },
  { id: "hz000573", palabra: "出口", pinyin: "chu1 ko3u", significado: "salida" },
  { id: "hz000574", palabra: "怎么", pinyin: "ze3n me0", significado: "¿cómo es que ..?" },
  { id: "hz000575", palabra: "行李", pinyin: "xi2ng li0", significado: "equipaje" },
  { id: "hz000576", palabra: "再", pinyin: "za4i", significado: "más" },
  { id: "hz000577", palabra: "一会儿", pinyin: "yi2 hui4 er0", significado: "un momento" },
  { id: "hz000578", palabra: "机场", pinyin: "ji1 cha3ng", significado: "aeropuerto" },
  { id: "hz000579", palabra: "候机厅", pinyin: "ho4u ji1 ti1ng", significado: "sala de espera" },
  { id: "hz000580", palabra: "入口", pinyin: "ru4 ko3u", significado: "entrada" },
  { id: "hz000581", palabra: "海关", pinyin: "ha3i gua1n", significado: "aduana" },
  { id: "hz000582", palabra: "安检", pinyin: "a1n jia3n", significado: "control de seguridad" },
  { id: "hz000583", palabra: "出境", pinyin: "chu1 ji4ng", significado: "salir del país" },
  {
    id: "hz000584",
    palabra: "入境卡",
    pinyin: "ru4 ji4ng ka3",
    significado: "registro de entrada en el país",
  },
  { id: "hz000585", palabra: "护照", pinyin: "hu4 zha4o", significado: "pasaporte" },
  { id: "hz000586", palabra: "签证", pinyin: "qia1n zhe4ng", significado: "visado" },
  {
    id: "hz000587",
    palabra: "机场费",
    pinyin: "ji1 cha3ng fe4i",
    significado: "tasa del aeropuerto",
  },
];
