export const palabras = [
  { id: "hz000001", palabra: "是", pinyin: "shi4", significado: "ser" },
  { id: "hz000002", palabra: "哪", pinyin: "na3", significado: "¿cuál? ¿qué?" },
  { id: "hz000003", palabra: "国", pinyin: "guo2", significado: "país" },
  { id: "hz000004", palabra: "人", pinyin: "re2n", significado: "persona" },
  { id: "hz000005", palabra: "我", pinyin: "wo3", significado: "yo" },
  { id: "hz000006", palabra: "叫", pinyin: "jia4o", significado: "llamarse" },
  { id: "hz000007", palabra: "什么", pinyin: "she2n me0", significado: "¿qué?" },
  { id: "hz000008", palabra: "名字", pinyin: "mi2ng zi0", significado: "nombre" },

  { id: "hz000010", palabra: "谢谢", pinyin: "xie4 xie0", significado: "Gracias" },
  { id: "hz000011", palabra: "西班牙", pinyin: "xi1 ba1n ya2", significado: "España" },
  { id: "hz000012", palabra: "马丁", pinyin: "ma3 di1ng", significado: "Martín" },
  { id: "hz000013", palabra: "这", pinyin: "zhe4", significado: "este" },
  { id: "hz000014", palabra: "谁", pinyin: "she2i", significado: "¿quién?" },
  { id: "hz000015", palabra: "爸爸", pinyin: "ba4 ba0", significado: "padre" },
  { id: "hz000016", palabra: "那", pinyin: "na4", significado: "ese, aquel" },
  { id: "hz000017", palabra: "妈妈", pinyin: "ma1 ma0", significado: "madre" },
  { id: "hz000018", palabra: "他们", pinyin: "ta1 men0", significado: "ellos" },
  { id: "hz000019", palabra: "身体", pinyin: "she1n ti3", significado: "salud" },
  { id: "hz000020", palabra: "吗", pinyin: "ma0", significado: "interrogación" },
  { id: "hz000021", palabra: "都", pinyin: "do1u", significado: "todos" },
  { id: "hz000022", palabra: "很", pinyin: "he3n", significado: "muy" },
  { id: "hz000023", palabra: "忙", pinyin: "ma2ng", significado: "ocupado" },
  { id: "hz000024", palabra: "李芳", pinyin: "li3 fa1ng", significado: "Li Fang" },
  { id: "hz000025", palabra: "玛利亚", pinyin: "ma3 li4 ya4", significado: "María" },
  { id: "hz000026", palabra: "请", pinyin: "qi3ng", significado: "solicitar" },
  { id: "hz000027", palabra: "坐", pinyin: "zuo4", significado: "sentarse" },
  { id: "hz000028", palabra: "的", pinyin: "de0", significado: "particula" },
  { id: "hz000029", palabra: "房间", pinyin: "fa2ng jia1n", significado: "habitación" },
  { id: "hz000030", palabra: "真", pinyin: "zhe1n", significado: "realmente, muy" },
  { id: "hz000031", palabra: "漂亮", pinyin: "pia4o liang", significado: "guapo" },
  { id: "hz000032", palabra: "要", pinyin: "ya4o", significado: "querer" },
  { id: "hz000033", palabra: "咖啡", pinyin: "ka1 fe1i", significado: "café" },
  { id: "hz000034", palabra: "不", pinyin: "bu4", significado: "no" },
  { id: "hz000035", palabra: "茶", pinyin: "cha2", significado: "té" },
  { id: "hz000036", palabra: "王大伟", pinyin: "wa2ng da4 we3i", significado: "Gran David" },
  { id: "hz000037", palabra: "住", pinyin: "zhu4", significado: "vivir" },
  { id: "hz000038", palabra: "哪儿", pinyin: "na3 er0", significado: "¿donde?" },
  { id: "hz000039", palabra: "楼", pinyin: "lo2u", significado: "edificio" },
  { id: "hz000040", palabra: "多少", pinyin: "duo1 shao0", significado: "¿cúanto?" },
  { id: "hz000041", palabra: "号", pinyin: "ha4o", significado: "número" },
  { id: "hz000042", palabra: "电话", pinyin: "dia4n hua4", significado: "número de teléfono" },
  { id: "hz000043", palabra: "号码", pinyin: "ha4o ma3", significado: "número" },
  { id: "hz000044", palabra: "呢", pinyin: "ne0", significado: "¿y el tuyo?" },
  { id: "hz000047", palabra: "请问", pinyin: "qi3ng w4en", significado: "dígmae por favor" },
  { id: "hz000048", palabra: "学校", pinyin: "xue2 xia4o", significado: "Uninversidad" },
  { id: "hz000049", palabra: "里边", pinyin: "li3 bian0", significado: "dentro de" },
  { id: "hz000050", palabra: "有", pinyin: "yo3u", significado: "haber" },
  { id: "hz000051", palabra: "餐厅", pinyin: "ca1n ti1ng", significado: "restaurante" },
  { id: "hz000052", palabra: "在", pinyin: "za4i", significado: "estar" },
  { id: "hz000053", palabra: "那 儿", pinyin: "na4 er0", significado: "allí" },
  { id: "hz000054", palabra: "没", pinyin: "me2i", significado: "no" },
  { id: "hz000055", palabra: "咖啡馆", pinyin: "ka1 fe1i gua3n", significado: "cafetería" },
  { id: "hz000056", palabra: "旁边", pinyin: "pa2ng bia1n", significado: "al lado de" },
  { id: "hz000057", palabra: "银行", pinyin: "yi2n ha2ng", significado: "banco" },
  { id: "hz000058", palabra: "点儿", pinyin: "dia3n er", significado: "Un poco de algo" },
  { id: "hz000059", palabra: "苹果", pinyin: "pi2ng guo3", significado: "manzana" },
  { id: "hz000060", palabra: "钱", pinyin: "qia2n", significado: "dinero" },
  { id: "hz000061", palabra: "斤", pinyin: "ji1n", significado: "unidad de peso (500gr)" },
  { id: "hz000062", palabra: "两", pinyin: "lia3ng", significado: "dos" },
  { id: "hz000063", palabra: "块", pinyin: "kua4i", significado: "yuan" },
  { id: "hz000064", palabra: "香蕉", pinyin: "xia1ng jia1o", significado: "plátano" },
  { id: "hz000065", palabra: "一共", pinyin: "yi2 go4ng", significado: "En total" },
  { id: "hz000066", palabra: "十二", pinyin: "shi2 e4r", significado: "Número 12" },
  { id: "hz000067", palabra: "服务员", pinyin: "fu2 wu4 yua2n", significado: "camarero" },
  { id: "hz000068", palabra: "先生", pinyin: "xia1n sheng0", significado: "caballero (Sr.)" },
  { id: "hz000069", palabra: "吃", pinyin: "chi1", significado: "comer" },
  { id: "hz000070", palabra: "饺子", pinyin: "jia3o zi0", significado: "empanadillas (dumpling)" },
  { id: "hz000071", palabra: "半", pinyin: "ba4n", significado: "mitad" },
  { id: "hz000072", palabra: "还", pinyin: "ha2i", significado: "aún, todavía más" },
  { id: "hz000073", palabra: "别的", pinyin: "bie2 de", significado: "otro (distinto)" },
  { id: "hz000074", palabra: "来", pinyin: "la2i", significado: "venir" },
  { id: "hz000075", palabra: "瓶", pinyin: "pi2ng", significado: "botella" },
  { id: "hz000076", palabra: "稍等", pinyin: "sha1o de3ng", significado: "(espere) un momento" },
  { id: "hz000077", palabra: "星期六", pinyin: "xi1ng qi1 liu4", significado: "sábado" },
  { id: "hz000078", palabra: "想", pinyin: "xia3ng", significado: "querer, desear" },
  { id: "hz000079", palabra: "去", pinyin: "qu4", significado: "ir" },
  { id: "hz000080", palabra: "远", pinyin: "yua3n", significado: "lejos" },
  { id: "hz000081", palabra: "比较", pinyin: "bi3 jia4o", significado: "bastante" },
  { id: "hz000082", palabra: "怎么", pinyin: "ze3n me0", significado: "¿Cómo?" },
  { id: "hz000083", palabra: "坐", pinyin: "zuo4", significado: "tomar (coger) un vehículo" },
  { id: "hz000084", palabra: "火车", pinyin: "huo3 che1", significado: "tren" },
  { id: "hz000085", palabra: "附近", pinyin: "fu4 ji4n", significado: "cerca de" },
  {
    id: "hz000086",
    palabra: "车站",
    pinyin: "che1 zha4n",
    significado: "Estación de (tren, autobus, etc)",
  },
  { id: "hz000088", palabra: "喂", pinyin: "we4i", significado: "¡Oye!" },
  { id: "hz000089", palabra: "你们", pinyin: "ni3 men0", significado: "vosotros" },
  { id: "hz000090", palabra: "我们", pinyin: "wo3 men0", significado: "nosotros" },
  { id: "hz000091", palabra: "也", pinyin: "ye3", significado: "también" },
  { id: "hz000092", palabra: "放心", pinyin: "fa4ng xi1n", significado: "preocupado" },
  { id: "hz000093", palabra: "吧", pinyin: "ba0", significado: "particula expletiva" },
  { id: "hz000094", palabra: "生活", pinyin: "she1ng huo2", significado: "vida, vivir" },
  { id: "hz000095", palabra: "习惯", pinyin: "xi2 gua4n", significado: "acostumbrarse" },
  { id: "hz000096", palabra: "没问题", pinyin: "me2i we4n ti2", significado: "No hay problema" },
  { id: "hz000097", palabra: "学习", pinyin: "xue2 xi2", significado: "estudiar" },
  { id: "hz000098", palabra: "多", pinyin: "duo1", significado: "mucho" },
  { id: "hz000099", palabra: "注意", pinyin: "zhu4 yi4", significado: "poner atención" },
  { id: "hz000100", palabra: "常", pinyin: "cha2ng", significado: "frecuente, a menudo" },
  { id: "hz000101", palabra: "打", pinyin: "da3", significado: "telefonear" },
  { id: "hz000102", palabra: "好的", pinyin: "ha3o de", significado: "de acuerdo, vale" },
  { id: "hz000103", palabra: "中国", pinyin: "zho1ng guo2", significado: "China" },
  { id: "hz000104", palabra: "你", pinyin: "ni3", significado: "tu" },
  { id: "hz000105", palabra: "好", pinyin: "ha3o", significado: "bueno" },
  { id: "hz000106", palabra: "学习", pinyin: "xue2 xi2", significado: "estudiar" },
  { id: "hz000107", palabra: "什么", pinyin: "she2n me0", significado: "que" },
  { id: "hz000108", palabra: "我", pinyin: "wo3", significado: "yo" },
  { id: "hz000109", palabra: "是", pinyin: "shi4", significado: "ser" },
  { id: "hz000110", palabra: "学生", pinyin: "xue2 sheng0", significado: "estudiante" },
  { id: "hz000111", palabra: "吗", pinyin: "ma0", significado: "particula expletiva" },
  { id: "hz000112", palabra: "对", pinyin: "dui4", significado: "correcto" },
  { id: "hz000113", palabra: "王大伟", pinyin: "wa2ng da4 we3i", significado: "Gran David" },
  { id: "hz000114", palabra: "马丁", pinyin: "ma3 ding1", significado: "Martín" },
  { id: "hz000115", palabra: "汉语", pinyin: "han4 yu3", significado: "chino (lengua)" },
  { id: "hz000116", palabra: "中国", pinyin: "zho1ng guo2", significado: "China" },
  {
    id: "hz000117",
    palabra: "西班牙语",
    pinyin: "xi1 ba1n ya2 yu3",
    significado: "español (idioma)",
  },
  { id: "hz000119", palabra: "美国", pinyin: "me3i guo2", significado: "EEUU" },
  { id: "hz000120", palabra: "英国", pinyin: "yi1ng guo2", significado: "Reino Unido" },
  { id: "hz000121", palabra: "英语", pinyin: "yi1ng yu3", significado: "inglés" },
  { id: "hz000123", palabra: "法国", pinyin: "fa3 guo2", significado: "Francia" },
  { id: "hz000125", palabra: "徳国", pinyin: "de2 guo2", significado: "Alemania" },
  { id: "hz000127", palabra: "意大利", pinyin: "yi4 da4 li4", significado: "Italia" },
  { id: "hz000129", palabra: "日本", pinyin: "ri4 be3n", significado: "Japón" },
  { id: "hz000130", palabra: "日语", pinyin: "ri4 yu3", significado: "japonés" },
  { id: "hz000132", palabra: "这", pinyin: "zhe4", significado: "este" },
  { id: "hz000133", palabra: "她", pinyin: "ta1", significado: "ella" },
  { id: "hz000134", palabra: "朋友", pinyin: "pe2ng you0", significado: "amigo" },
  { id: "hz000135", palabra: "哪", pinyin: "na3", significado: "qué. Cuál" },
  { id: "hz000136", palabra: "国", pinyin: "guo2", significado: "país" },
  { id: "hz000137", palabra: "人", pinyin: "re2n", significado: "persona" },
  { id: "hz000138", palabra: "也", pinyin: "ye3", significado: "también" },
  { id: "hz000139", palabra: "不", pinyin: "bu4", significado: "no" },
  { id: "hz000140", palabra: "老师", pinyin: "la3o shi1", significado: "profesor" },
  { id: "hz000141", palabra: "教", pinyin: "jia1o", significado: "enseñar" },
  { id: "hz000142", palabra: "爱琳娜", pinyin: "a4i li2n na4", significado: "Elena" },
  { id: "hz000143", palabra: "我们", pinyin: "wo3 men", significado: "nosotros" },
  { id: "hz000144", palabra: "你们", pinyin: "ni3 men", significado: "vosotros" },
  { id: "hz000145", palabra: "他", pinyin: "ta1", significado: "el" },
  { id: "hz000146", palabra: "他们", pinyin: "ta1 men", significado: "ellos" },
  { id: "hz000147", palabra: "她", pinyin: "ta1", significado: "ella" },
  { id: "hz000148", palabra: "她们", pinyin: "ta1 men", significado: "ellas" },
  { id: "hz000149", palabra: "爸爸", pinyin: "ba4 ba0", significado: "papá" },
  { id: "hz000150", palabra: "妈妈", pinyin: "ma1 ma0", significado: "mamá" },
  { id: "hz000151", palabra: "在", pinyin: "za4i", significado: "en" },
  { id: "hz000152", palabra: "哪儿", pinyin: "na3 er0", significado: "dónde" },
  { id: "hz000153", palabra: "工作", pinyin: "go1ng zuo4", significado: "trabajar" },
  { id: "hz000154", palabra: "他", pinyin: "ta1", significado: "el" },
  { id: "hz000155", palabra: "医院", pinyin: "yi1 yua4n", significado: "hospital" },
  { id: "hz000156", palabra: "医生", pinyin: "yi1 she1ng", significado: "médico" },
  { id: "hz000157", palabra: "呢", pinyin: "ne0", significado: "partícula expletiva" },
  { id: "hz000158", palabra: "谁", pinyin: "she2i", significado: "quién" },
  { id: "hz000159", palabra: "姐姐", pinyin: "jie3 jie0", significado: "hermana mayor" },
  { id: "hz000160", palabra: "李芳", pinyin: "li3 fa1ng", significado: "Li Fang" },
  { id: "hz000161", palabra: "玛利亚", pinyin: "ma3 li4 ya4", significado: "María" },
  { id: "hz000164", palabra: "哥哥", pinyin: "ge1 ge0", significado: "hermano mayor" },
  { id: "hz000165", palabra: "弟弟", pinyin: "di4 di0", significado: "hermano menor" },
  { id: "hz000167", palabra: "阿姨", pinyin: "a1 yi2", significado: "tia (hermana madre)" },
  { id: "hz000171", palabra: "和", pinyin: "he2", significado: "y" },
  { id: "hz000172", palabra: "都", pinyin: "do1u", significado: "todos" },
  { id: "hz000173", palabra: "很", pinyin: "he3n", significado: "muy" },
  { id: "hz000174", palabra: "漂亮", pinyin: "pia4o liang0", significado: "guapa" },
  { id: "hz000175", palabra: "谢谢", pinyin: "xie4 xie0", significado: "agradecer" },
  { id: "hz000176", palabra: "叫", pinyin: "jia4o", significado: "llamarse" },
  { id: "hz000177", palabra: "名字", pinyin: "mi2ng zi0", significado: "nombre" },
  { id: "hz000178", palabra: "做", pinyin: "zuo4", significado: "hacer" },
  { id: "hz000179", palabra: "护士", pinyin: "hu4 shi0", significado: "enfermera" },
  { id: "hz000180", palabra: "忙", pinyin: "ma2ng", significado: "ocupado" },
  { id: "hz000181", palabra: "罗莎", pinyin: "luo2 sha1", significado: "Rosa" },
  { id: "hz000182", palabra: "教师", pinyin: "jia4o shi1", significado: "profesor" },
  { id: "hz000184", palabra: "经理", pinyin: "ji1ng li3", significado: "gerente" },
  { id: "hz000191", palabra: "职员", pinyin: "zhi2 yua2n", significado: "empleado" },
  { id: "hz000192", palabra: "的", pinyin: "de0", significado: "partícula estructural" },
  { id: "hz000193", palabra: "衣服", pinyin: "yi1 fu0", significado: "ropa" },
  { id: "hz000194", palabra: "脏", pinyin: "za1ng", significado: "sucio" },
  { id: "hz000195", palabra: "别", pinyin: "bie2", significado: "no" },
  { id: "hz000196", palabra: "放", pinyin: "fa4ng", significado: "poner" },
  { id: "hz000197", palabra: "这儿", pinyin: "zhe4 er0", significado: "aquí" },
  { id: "hz000198", palabra: "洗衣机", pinyin: "xi3 yi1 ji1", significado: "lavadora" },
  { id: "hz000199", palabra: "里", pinyin: "li3", significado: "dentro" },
  { id: "hz000200", palabra: "那", pinyin: "na4", significado: "aquel" },
  { id: "hz000201", palabra: "裤子", pinyin: "ku4 zi0", significado: "pantalones" },
  { id: "hz000202", palabra: "弟弟", pinyin: "di4 di0", significado: "hermano menor" },
  { id: "hz000206", palabra: "衬衣", pinyin: "che4n yi1", significado: "camisa" },
  { id: "hz000209", palabra: "岁", pinyin: "sui4", significado: "años" },
  { id: "hz000210", palabra: "问", pinyin: "we4n", significado: "preguntar" },
  { id: "hz000211", palabra: "说", pinyin: "shuo1", significado: "decir" },
  { id: "hz000214", palabra: "喝", pinyin: "he1", significado: "beber" },
  { id: "hz000215", palabra: "茶", pinyin: "cha2", significado: "té" },
  { id: "hz000216", palabra: "咖啡", pinyin: "ka1 fe1", significado: "café" },
  { id: "hz000217", palabra: "还是", pinyin: "ha2i shi4", significado: "o" },
  { id: "hz000218", palabra: "有", pinyin: "yo3u", significado: "haber, tener" },
  { id: "hz000220", palabra: "真", pinyin: "zhe1n", significado: "mucho, verdaderamente" },
  { id: "hz000221", palabra: "对不起", pinyin: "dui4 bu0 qi3", significado: "lo siento" },
  { id: "hz000222", palabra: "没", pinyin: "me2i", significado: "no" },
  { id: "hz000223", palabra: "王玲", pinyin: "wa2ng li2ng", significado: "Wang Ling" },
  { id: "hz000224", palabra: "张明", pinyin: "zha1ng mi2ng", significado: "Zhang Ming" },
  { id: "hz000225", palabra: "啤酒", pinyin: "pi2 jiu3", significado: "cerveza" },
  { id: "hz000226", palabra: "葡萄酒", pinyin: "pu2 ta2o jiu3", significado: "vino" },
  { id: "hz000228", palabra: "矿泉水", pinyin: "kua4ng qua2n shui3", significado: "agua mineral" },
  { id: "hz000231", palabra: "面包", pinyin: "mia4n ba1o", significado: "pan" },
  { id: "hz000235", palabra: "商店", pinyin: "sha1ng dia4n", significado: "tienda" },
  { id: "hz000236", palabra: "学校", pinyin: "xue2 xia4o", significado: "colegio" },
  { id: "hz000237", palabra: "一", pinyin: "yi1", significado: "uno" },
  { id: "hz000238", palabra: "个", pinyin: "ge4", significado: "clasificador" },
  { id: "hz000239", palabra: "小", pinyin: "xia3o", significado: "pequeño" },
  { id: "hz000240", palabra: "附近", pinyin: "fu4 ji4n", significado: "cercania, alrededor" },
  { id: "hz000241", palabra: "大", pinyin: "da4", significado: "grande" },
  { id: "hz000242", palabra: "后边", pinyin: "ho4u bian0", significado: "detrás de" },
  { id: "hz000243", palabra: "那儿", pinyin: "na4 er0", significado: "allí" },
  { id: "hz000244", palabra: "水果", pinyin: "shui3 guo3", significado: "fruta" },
  { id: "hz000245", palabra: "贵", pinyin: "gui4", significado: "caro" },
  { id: "hz000246", palabra: "比较", pinyin: "bi3 jia4o", significado: "bastante" },
  { id: "hz000247", palabra: "但是", pinyin: "da4n shi4", significado: "pero" },
  { id: "hz000248", palabra: "我们", pinyin: "wo3 men0", significado: "nosotros" },
  { id: "hz000249", palabra: "去", pinyin: "qu4", significado: "ir" },
  { id: "hz000250", palabra: "买", pinyin: "ma3i", significado: "comprar" },
  { id: "hz000251", palabra: "吧", pinyin: "ba0", significado: "partícula expletiva" },
  { id: "hz000252", palabra: "苹果", pinyin: "pi2ng guo3", significado: "manzana" },
  { id: "hz000260", palabra: "家", pinyin: "jia1", significado: "casa, familia" },
  { id: "hz000261", palabra: "常常", pinyin: "cha2ng cha2ng", significado: "frecuentemente" },
  { id: "hz000262", palabra: "手机", pinyin: "sho3u ji1", significado: "tlf. móvil" },
  { id: "hz000263", palabra: "多少", pinyin: "duo1 sha3o", significado: "¿cuánto?" },
  { id: "hz000264", palabra: "钱", pinyin: "qia2n", significado: "dinero?" },
  { id: "hz000265", palabra: "蓝色", pinyin: "la2n se4", significado: "azul" },
  { id: "hz000266", palabra: "两", pinyin: "lia3ng", significado: "dos" },
  { id: "hz000267", palabra: "千", pinyin: "qia1n", significado: "mil" },
  { id: "hz000268", palabra: "百", pinyin: "ba3i", significado: "cien" },
  { id: "hz000269", palabra: "块", pinyin: "kua4i", significado: "moneda (coloq.)" },
  { id: "hz000270", palabra: "太..了", pinyin: "ta4i .. le0", significado: "muy/demasiado" },
  { id: "hz000271", palabra: "灰色", pinyin: "hui1 se4", significado: "gris" },
  { id: "hz000272", palabra: "牌子", pinyin: "pa2i zi0", significado: "marca comercial" },
  { id: "hz000273", palabra: "黑色", pinyin: "he1i se4", significado: "negro" },
  { id: "hz000274", palabra: "白色", pinyin: "ba2i se4", significado: "blanco" },
  { id: "hz000275", palabra: "红色", pinyin: "ho2ng se4", significado: "rojo" },
  { id: "hz000276", palabra: "黄色", pinyin: "hua2ng se4", significado: "amarillo" },
  { id: "hz000277", palabra: "绿色", pinyin: "lv4 se4", significado: "verde" },
  { id: "hz000279", palabra: "深色", pinyin: "she1n se4", significado: "color oscuro" },
  { id: "hz000280", palabra: "浅色", pinyin: "qia3n se4", significado: "color claro" },
  { id: "hz000281", palabra: "多", pinyin: "duo1", significado: "mucho" },
  { id: "hz000282", palabra: "种", pinyin: "zho3ng", significado: "(clasif.)" },
  { id: "hz000283", palabra: "想", pinyin: "xia3ng", significado: "pensar, desear" },
  { id: "hz000284", palabra: "租", pinyin: "zu1", significado: "alquilar" },
  { id: "hz000285", palabra: "套", pinyin: "ta4o", significado: "clasificador" },
  { id: "hz000286", palabra: "房子", pinyin: "fa2ng zi0", significado: "piso" },
  { id: "hz000287", palabra: "合适", pinyin: "he2 shi0", significado: "apropiado" },
  { id: "hz000288", palabra: "看", pinyin: "ka4n", significado: "ver" },
  { id: "hz000289", palabra: "怎么样", pinyin: "ze3n me0 ya4ng", significado: "qué tal" },
  { id: "hz000290", palabra: "太", pinyin: "ta4i", significado: "demasiado" },
  { id: "hz000291", palabra: "明天", pinyin: "mi2ng tia1n", significado: "mañana" },
  { id: "hz000292", palabra: "能", pinyin: "ne2ng", significado: "poder" },
  { id: "hz000293", palabra: "跟", pinyin: "ge1n", significado: "con" },
  { id: "hz000294", palabra: "一起", pinyin: "yi4 qi3", significado: "juntos" },
  { id: "hz000302", palabra: "昨天", pinyin: "zuo2 tia1n", significado: "ayer" },
  { id: "hz000303", palabra: "房间", pinyin: "fa2ng jia1n", significado: "habitación" },
  { id: "hz000304", palabra: "房租", pinyin: "fa2ng zu1", significado: "alquiler" },
  { id: "hz000305", palabra: "小区", pinyin: "xia3o qu1", significado: "residencial" },
  { id: "hz000306", palabra: "啊", pinyin: "a0", significado: "partícula expletiva" },
  { id: "hz000307", palabra: "你们", pinyin: "ni3 men0", significado: "vosotros" },
  { id: "hz000308", palabra: "就", pinyin: "jiu4", significado: "justamente" },
  { id: "hz000309", palabra: "楼", pinyin: "lo2u", significado: "edificio" },
  { id: "hz000310", palabra: "几", pinyin: "ji3", significado: "¿cuántos?", undefined: "varios" },
  { id: "hz000311", palabra: "层", pinyin: "ce2ng", significado: "clasificador de piso" },
  { id: "hz000312", palabra: "交通", pinyin: "jia1o to1ng", significado: "comunicaciones" },
  { id: "hz000313", palabra: "方便", pinyin: "fa1ng bia4n", significado: "fácil" },
  { id: "hz000314", palabra: "那边", pinyin: "na4 bia1n", significado: "allí" },
  { id: "hz000315", palabra: "地铁站", pinyin: "di4 tie3 zha4n", significado: "estación de metro" },
  { id: "hz000316", palabra: "银行", pinyin: "yi2n ha2ng", significado: "banco" },
  { id: "hz000317", palabra: "上边", pinyin: "sha4ng bian0", significado: "arriba" },
  { id: "hz000318", palabra: "下边", pinyin: "xia4 bian", significado: "abajo" },
  { id: "hz000319", palabra: "里边", pinyin: "li3 bian", significado: "dentro" },
  { id: "hz000320", palabra: "外边", pinyin: "wa4i bian", significado: "fuera" },
  { id: "hz000321", palabra: "前边", pinyin: "quia2n bian", significado: "delante" },
  { id: "hz000322", palabra: "后边", pinyin: "ho4u bian", significado: "detrás" },
  { id: "hz000323", palabra: "左边", pinyin: "zuo3 bian", significado: "izquierda" },
  { id: "hz000324", palabra: "右边", pinyin: "yo4u bian", significado: "derecha" },
  { id: "hz000325", palabra: "中间", pinyin: "zho1ng jia1n", significado: "centro" },
  { id: "hz000326", palabra: "对面", pinyin: "dui4 mia4n", significado: "en frente" },
  { id: "hz000327", palabra: "照片", pinyin: "zha4o pia4n", significado: "fotografía" },
  { id: "hz000328", palabra: "后天", pinyin: "ho4u tia1n", significado: "pasado mañana" },
  { id: "hz000329", palabra: "生日", pinyin: "she1ng ri4", significado: "cumpleaños" },
  { id: "hz000330", palabra: "请", pinyin: "qi3ng", significado: "invitar" },
  { id: "hz000331", palabra: "参加", pinyin: "ca1n jia1", significado: "participar" },
  { id: "hz000332", palabra: "晚会", pinyin: "wa3n hui4", significado: "fiesta" },
  { id: "hz000333", palabra: "号", pinyin: "ha4o", significado: "día, número" },
  { id: "hz000334", palabra: "月", pinyin: "yue4", significado: "mes" },
  { id: "hz000335", palabra: "星期", pinyin: "xi1ng qi1", significado: "semana" },
  { id: "hz000336", palabra: "晚上", pinyin: "wa3n shang0", significado: "noche" },
  { id: "hz000337", palabra: "时间", pinyin: "shi2 jia1n", significado: "tiempo" },
  { id: "hz000338", palabra: "点", pinyin: "dia3n", significado: "hora" },
  { id: "hz000339", palabra: "开始", pinyin: "ka1i shi3", significado: "comenzar" },
  { id: "hz000340", palabra: "半", pinyin: "ba4n", significado: "medio" },
  { id: "hz000341", palabra: "一定", pinyin: "yi2 di4ng", significado: "sin falta" },
  { id: "hz000342", palabra: "来", pinyin: "la2i", significado: "venir" },
  { id: "hz000343", palabra: "今年", pinyin: "ji1n nia2n", significado: "este año" },
  { id: "hz000344", palabra: "多", pinyin: "duo1", significado: "cuánto" },
  { id: "hz000345", palabra: "属", pinyin: "shu3", significado: "corresponder horóscopo chino" },
  { id: "hz000346", palabra: "年", pinyin: "nia2n", significado: "año" },
  { id: "hz000347", palabra: "出生", pinyin: "chu1 she1ng", significado: "nacer" },
  { id: "hz000348", palabra: "啊", pinyin: "a2", significado: "ah!" },
  { id: "hz000349", palabra: "俩", pinyin: "lia3", significado: "(ambos) dos" },
  { id: "hz000350", palabra: "铜", pinyin: "to2ng", significado: "ser (de) igual, (el) mismo" },
  { id: "hz000351", palabra: "岁", pinyin: "sui4", significado: "edad, años" },
  { id: "hz000365", palabra: "现在", pinyin: "xia4n za4i", significado: "ahora" },
  { id: "hz000366", palabra: "了", pinyin: "le0", significado: "part" },
  { id: "hz000367", palabra: "零", pinyin: "li2ng", significado: "part" },
  { id: "hz000368", palabra: "分", pinyin: "fe1n", significado: "minuto" },
  { id: "hz000369", palabra: "早", pinyin: "za3o", significado: "temprano" },
  { id: "hz000370", palabra: "得", pinyin: "de3i", significado: "tener" },
  { id: "hz000371", palabra: "走", pinyin: "zo3u", significado: "caminar" },
  { id: "hz000372", palabra: "着急", pinyin: "zha2o ji2", significado: "preocupado" },
  { id: "hz000373", palabra: "还", pinyin: "ha2i", significado: "todavía" },
  { id: "hz000374", palabra: "上课", pinyin: "sha4ng ke4", significado: "tener clase" },
  { id: "hz000375", palabra: "没关系", pinyin: "me2i gua1n xi0", significado: "no importa" },
  { id: "hz000376", palabra: "每(天)", pinyin: "me3i (tia1n)", significado: "cada (día)" },
  { id: "hz000377", palabra: "才", pinyin: "ca2i", significado: "pronto" },
  { id: "hz000378", palabra: "睡觉", pinyin: "shui4 jia4o", significado: "dormir" },
  { id: "hz000379", palabra: "这么", pinyin: "zhe4 me", significado: "tan" },
  { id: "hz000380", palabra: "晚", pinyin: "wa3n", significado: "tarde" },
  { id: "hz000381", palabra: "早上", pinyin: "za3o shang0", significado: "mañana temprano" },
  { id: "hz000382", palabra: "起床", pinyin: "qi3 chua2ng", significado: "despertarse" },
  { id: "hz000383", palabra: "觉得", pinyin: "jue2 de0", significado: "parecer" },
  { id: "hz000384", palabra: "要", pinyin: "ya4o", significado: "querer" },
  { id: "hz000385", palabra: "问", pinyin: "we4n", significado: "preguntar" },
  { id: "hz000386", palabra: "前天", pinyin: "qia2n tia1n", significado: "anteayer" },
  { id: "hz000387", palabra: "昨天", pinyin: "zuo2 tian1", significado: "ayer" },
  { id: "hz000388", palabra: "今天", pinyin: "jin1 tian1", significado: "hoy" },
  { id: "hz000389", palabra: "上午", pinyin: "sha4ng wu3", significado: "mañana" },
  { id: "hz000390", palabra: "中午", pinyin: "zho1ng wu3", significado: "mediodía" },
  { id: "hz000391", palabra: "下午", pinyin: "xia4 wu3", significado: "tarde" },
  { id: "hz000392", palabra: "下课", pinyin: "xia4 ke4", significado: "salir de clase" },
  { id: "hz000395", palabra: "同", pinyin: "to2ng wu1", significado: "compañero" },
  { id: "hz000396", palabra: "办公室", pinyin: "ba4n go1ng shi4", significado: "oficina" },
  { id: "hz000397", palabra: "张", pinyin: "zha1ng", significado: "clasif. (plano)" },
  { id: "hz000398", palabra: "桌子", pinyin: "zhuo1 zi0", significado: "clasif. (plano)" },
  { id: "hz000399", palabra: "他们", pinyin: "ta1 men0", significado: "ellos" },
  { id: "hz000400", palabra: "台", pinyin: "ta2i", significado: "clasif. (dispositivos grandes)" },
  { id: "hz000401", palabra: "部", pinyin: "bu4", significado: "clasif. (dispositivos pequeños)" },
  { id: "hz000402", palabra: "电脑", pinyin: "dia4n na3o", significado: "ordenador" },
  { id: "hz000403", palabra: "电话", pinyin: "dia4n hua4", significado: "teléfono" },
  { id: "hz000406", palabra: "旁边", pinyin: "pa2ng bia1n", significado: "al lado" },
  { id: "hz000407", palabra: "沙发", pinyin: "sha1 fa1", significado: "sofá" },
  { id: "hz000409", palabra: "不错", pinyin: "bu2 cuo4", significado: "correcto, muy bueno" },
  { id: "hz000410", palabra: "画儿", pinyin: "hua4 er0", significado: "cuadro" },
  { id: "hz000411", palabra: "匹", pinyin: "pi3", significado: "clasif. (caballo)" },
  { id: "hz000422", palabra: "最近", pinyin: "zui4 ji4n", significado: "últimamente" },
  { id: "hz000423", palabra: "刚", pinyin: "ga1ng", significado: "apenas, recién" },
  {
    id: "hz000424",
    palabra: "时候",
    pinyin: "shi2 hou0",
    significado: "momento",
  },
  { id: "hz000425", palabra: "有点儿", pinyin: "yo3u dia3n er0", significado: "algo, un poco" },
  { id: "hz000426", palabra: "紧张", pinyin: "ji3n zha1ng", significado: "nervioso" },
  { id: "hz000427", palabra: "一点儿", pinyin: "yi4 dia3n er0", significado: "un poco" },
  { id: "hz000428", palabra: "天气", pinyin: "tia1n qi4", significado: "tiempo atmosférico" },
  { id: "hz000429", palabra: "习惯", pinyin: "xi2 gua4n", significado: "acostumbrarse" },
  { id: "hz000430", palabra: "冬天", pinyin: "do1ng tia1n", significado: "invierno" },
  { id: "hz000431", palabra: "冷", pinyin: "le3ng", significado: "frío" },
  { id: "hz000432", palabra: "菜", pinyin: "ca4i", significado: "comida, plato" },
  { id: "hz000433", palabra: "吃", pinyin: "chi1", significado: "comer" },
  { id: "hz000434", palabra: "喜欢", pinyin: "xi3 huan0", significado: "gustar" },
  { id: "hz000437", palabra: "累", pinyin: "le4i", significado: "cansado" },
  { id: "hz000438", palabra: "走", pinyin: "zo3u", significado: "ir" },
  { id: "hz000439", palabra: "何赛", pinyin: "He2 sa4i", significado: "José" },
  { id: "hz000440", palabra: "北京", pinyin: "be3i ji1ng", significado: "Beijing" },
  { id: "hz000441", palabra: "春天", pinyin: "chu1n tia1n", significado: "primavera" },
  { id: "hz000442", palabra: "夏天", pinyin: "xia4 tia1n", significado: "verano" },
  { id: "hz000443", palabra: "秋天", pinyin: "qiu1 tia1n", significado: "otoño" },
  { id: "hz000445", palabra: "热", pinyin: "re4", significado: "cálido" },
  { id: "hz000446", palabra: "暖和", pinyin: "nua3n huo0", significado: "templado" },
  { id: "hz000447", palabra: "下雨", pinyin: "xia4 yu3", significado: "llover" },
  { id: "hz000450", palabra: "病", pinyin: "bi4ng", significado: "estar enfermo" },
  { id: "hz000451", palabra: "嗓子", pinyin: "sa3ng zi0", significado: "garganta" },
  { id: "hz000452", palabra: "疼", pinyin: "te2ng", significado: "doler" },
  { id: "hz000453", palabra: "可能", pinyin: "ke3 ne2ng", significado: "quizás" },
  { id: "hz000454", palabra: "感冒", pinyin: "ga3n ma4o", significado: "resfriarse" },
  { id: "hz000455", palabra: "发烧", pinyin: "fa1 sha1o", significado: "tener fiebre" },
  { id: "hz000456", palabra: "不用", pinyin: "bu2 yo4ng", significado: "no ser necesario" },
  { id: "hz000457", palabra: "药", pinyin: "ya4o", significado: "medicina" },
  {
    id: "hz000458",
    palabra: "身体",
    pinyin: "she1n ti3",
    significado: "cuerpo",
    undefined: "salud",
  },
  { id: "hz000459", palabra: "只是", pinyin: "zhi3 shi4", significado: "sólo que, simplemente" },
  { id: "hz000460", palabra: "家", pinyin: "jia1", significado: "casa, familia, especialista" },
  { id: "hz000461", palabra: "办法", pinyin: "ba4n fa3", significado: "solución, método" },
  { id: "hz000462", palabra: "餐厅", pinyin: "ca1n ti1ng", significado: "restaurante" },
  { id: "hz000463", palabra: "头疼", pinyin: "to2u te2ng", significado: "dolor de cabeza" },
  { id: "hz000472", palabra: "大夫", pinyin: "da4i fu0", significado: "doctor" },
  { id: "hz000473", palabra: "头", pinyin: "to2u", significado: "cabeza" },
  { id: "hz000474", palabra: "全身", pinyin: "qua2n she1n", significado: "todo el cuerp" },
  { id: "hz000475", palabra: "不舒服", pinyin: "bu4 shu1 fu0", significado: "indispuesto" },
  { id: "hz000476", palabra: "给", pinyin: "ge3i", significado: "a" },
  { id: "hz000477", palabra: "检查", pinyin: "jia3n cha2", significado: "examinar" },
  { id: "hz000478", palabra: "问题", pinyin: "we4n ti2", significado: "problema" },
  { id: "hz000479", palabra: "常常", pinyin: "cha2ng cha2ng", significado: "frecuentemente" },
  { id: "hz000480", palabra: "加班", pinyin: "jia1 ba1n", significado: "trabajar horas extras" },
  { id: "hz000481", palabra: "锻炼", pinyin: "dua4n lia4n", significado: "hacer ejercicio físico" },
  { id: "hz000482", palabra: "应该", pinyin: "yi1ng ga1i", significado: "deber" },
  { id: "hz000483", palabra: "对", pinyin: "dui4", significado: "para" },
  { id: "hz000484", palabra: "好处", pinyin: "ha3o chu0", significado: "ventaja, beneficio" },
  { id: "hz000485", palabra: "重要", pinyin: "zho4ng ya4o", significado: "importante" },
  { id: "hz000491", palabra: "手", pinyin: "sho3u", significado: "mano" },
  { id: "hz000493", palabra: "运动", pinyin: "yu4n do4ng", significado: "deporte, hacer deporte" },
  { id: "hz000494", palabra: "请问", pinyin: "qi3ng we4n", significado: "Por favor" },
  { id: "hz000495", palabra: "好久", pinyin: "ha3o jiu3", significado: "Hace mucho que" },
  { id: "hz000496", palabra: "见", pinyin: "jia4n", significado: "ver" },
  { id: "hz000497", palabra: "马马虎虎", pinyin: "ma3 ma3 hu1 hu1", significado: "regular" },
  { id: "hz000498", palabra: "搬", pinyin: "ba1n", significado: "mover, trasladar" },
  { id: "hz000499", palabra: "玩儿", pinyin: "wa2n er0", significado: "divertirse" },
  { id: "hz000500", palabra: "行", pinyin: "xi2ng", significado: "bien, vale" },
  { id: "hz000501", palabra: "聊天儿", pinyin: "lia2o tia1nr", significado: "charlar" },
  { id: "hz000502", palabra: "等", pinyin: "de3ng", significado: "esperar" },
  { id: "hz000503", palabra: "这样", pinyin: "zhe4 ya4ng", significado: "así" },
  { id: "hz000504", palabra: "再见", pinyin: "za4i jia4n", significado: "adios" },
  { id: "hz000505", palabra: "告诉", pinyin: "ga4o su4", significado: "decir" },
  { id: "hz000506", palabra: "地址", pinyin: "di4 zhi3", significado: "dirección (domicilio)" },
  { id: "hz000507", palabra: "喂", pinyin: "we4i", significado: "¡oye! ¡eh!" },
  { id: "hz000508", palabra: "赵小英", pinyin: "Zha4o Xia3o yi1ng", significado: "Zhao Xiao Ying" },
  { id: "hz000509", palabra: "唱歌", pinyin: "cha4ng ge1", significado: "cantar (una canción)" },
  { id: "hz000510", palabra: "跳舞", pinyin: "tia4o wu3", significado: "bailar (un baile)" },
  { id: "hz000511", palabra: "听音乐", pinyin: "ti1ng yi1n yue4", significado: "escuchar música" },
  { id: "hz000512", palabra: "下棋", pinyin: "xia4 qi2", significado: "jugar al ajedrez" },
  { id: "hz000516", palabra: "下午", pinyin: "xia4 wu3", significado: "la tarde" },
  { id: "hz000518", palabra: "打", pinyin: "da3", significado: "dar, golpear, llamar" },
  { id: "hz000519", palabra: "次", pinyin: "ci4", significado: "vez" },
  { id: "hz000520", palabra: "事儿", pinyin: "shi4r", significado: "asunto" },
  { id: "hz000521", palabra: "让", pinyin: "ra4ng", significado: "pedir, invitar" },
  { id: "hz000522", palabra: "忘", pinyin: "wa4ng", significado: "olvidar" },
  { id: "hz000523", palabra: "知道", pinyin: "zhi1 da4o", significado: "saber" },
  { id: "hz000524", palabra: "号码", pinyin: "ha4o ma3", significado: "número" },
  { id: "hz000525", palabra: "昨天", pinyin: "zuo2 tia1n", significado: "ayer" },
  { id: "hz000526", palabra: "挂", pinyin: "gua4", significado: "colgar" },
  { id: "hz000527", palabra: "门口", pinyin: "me2n ko3u", significado: "entrada" },
  { id: "hz000528", palabra: "件", pinyin: "jia4n", significado: "clas. ropa" },
  { id: "hz000529", palabra: "毛衣", pinyin: "ma3o yi1", significado: "jersey" },
  { id: "hz000530", palabra: "顶", pinyin: "di3ng", significado: "clas. sombreros" },
  { id: "hz000531", palabra: "帽子", pinyin: "ma4o zi", significado: "sombrero" },
  { id: "hz000532", palabra: "条", pinyin: "tia2o", significado: "clas. cosas largas y delgadas" },
  { id: "hz000539", palabra: "在", pinyin: "za4i", significado: "estar (+gerundio)" },
  { id: "hz000540", palabra: "书", pinyin: "shu1", significado: "libro" },
  { id: "hz000541", palabra: "呀", pinyin: "ya0", significado: "particula expletiva" },
  { id: "hz000542", palabra: "正", pinyin: "zhe4ng", significado: "justamente" },
  { id: "hz000543", palabra: "说", pinyin: "shuo1", significado: "decir" },
  { id: "hz000544", palabra: "打算", pinyin: "da3 suan0", significado: "planear" },
  { id: "hz000545", palabra: "下", pinyin: "xia4", significado: "próximo" },
  { id: "hz000546", palabra: "假", pinyin: "jia4", significado: "vacaciones" },
  { id: "hz000547", palabra: "飞机", pinyin: "fe1i ji1", significado: "avión" },
  { id: "hz000548", palabra: "票", pinyin: "pia4o", significado: "billete" },
  { id: "hz000549", palabra: "正在", pinyin: "zhe4ng za4i", significado: "justamente" },
  { id: "hz000550", palabra: "考试", pinyin: "ka3o shi4", significado: "tener exámenes" },
  { id: "hz000551", palabra: "担心", pinyin: "da1n xi1n", significado: "temer, preocuparse" },
  { id: "hz000552", palabra: "陪", pinyin: "pe2i", significado: "acompañar" },
  { id: "hz000553", palabra: "可以", pinyin: "ke3 yi3", significado: "poder" },
  { id: "hz000554", palabra: "到", pinyin: "da4o", significado: "llegar" },
  { id: "hz000555", palabra: "接", pinyin: "jie1", significado: "recibir" },
  { id: "hz000556", palabra: "维克多", pinyin: "we2i ke4 duo1", significado: "Víctor" },
  { id: "hz000557", palabra: "前年", pinyin: "qia2n nia2n", significado: "hace dos años" },
  { id: "hz000558", palabra: "去年", pinyin: "qu4 nia2n", significado: "el año pasado" },
  { id: "hz000559", palabra: "今年", pinyin: "ji1n nia2n", significado: "este año" },
  { id: "hz000560", palabra: "明年", pinyin: "mi2ng nia2n", significado: "el próximo año" },
  { id: "hz000561", palabra: "后年", pinyin: "ho4u nia2n", significado: "dentro de dos años" },
  { id: "hz000562", palabra: "上个月", pinyin: "sha4ng ge4 yue4", significado: "el mes pasado" },
  { id: "hz000563", palabra: "这个月", pinyin: "zhe4 ge4 yue4", significado: "este mes" },
  { id: "hz000564", palabra: "下个月", pinyin: "xia4 ge4 yue4", significado: "el próximo mes" },
  {
    id: "hz000565",
    palabra: "上星期",
    pinyin: "sha4ng xi1ng qi1",
    significado: "la semana pasada",
  },
  { id: "hz000566", palabra: "这星期", pinyin: "zhe4 xi1ng qi1", significado: "esta semana" },
  { id: "hz000567", palabra: "下星期", pinyin: "xia4 xi1ng qi1", significado: "la próxima semana" },
  { id: "hz000568", palabra: "快", pinyin: "kua4i", significado: "rápido, pronto" },
  { id: "hz000569", palabra: "要。了", pinyin: "ya4o 0 le0", significado: "ir a" },
  { id: "hz000570", palabra: "迟到", pinyin: "chi2 da4o", significado: "llegar tarde" },
  { id: "hz000571", palabra: "来得及", pinyin: "la2i de0 ji2", significado: "hay tiempo" },
  { id: "hz000572", palabra: "分钟", pinyin: "fe1n zho1ng", significado: "minuto" },
  { id: "hz000573", palabra: "出口", pinyin: "chu1 ko3u", significado: "salida" },
  { id: "hz000574", palabra: "怎么", pinyin: "ze3n me0", significado: "¿cómo es que ..?" },
  { id: "hz000575", palabra: "行李", pinyin: "xi2ng li0", significado: "equipaje" },
  { id: "hz000576", palabra: "再", pinyin: "za4i", significado: "más" },
  { id: "hz000577", palabra: "一会儿", pinyin: "yi2 hui4 er0", significado: "un momento" },
  { id: "hz000578", palabra: "机场", pinyin: "ji1 cha3ng", significado: "aeropuerto" },
  { id: "hz000579", palabra: "候机厅", pinyin: "ho4u ji1 ti1ng", significado: "sala de espera" },
  { id: "hz000580", palabra: "入口", pinyin: "ru4 ko3u", significado: "entrada" },
  { id: "hz000801", palabra: "运动", pinyin: "yu4n do4ng", significado: "deporte" },
  { id: "hz000802", palabra: "足球", pinyin: "zu2 qiu2", significado: "fútbol" },
  { id: "hz000803", palabra: "踢", pinyin: "ti1", significado: "jugar, patear" },
  { id: "hz000804", palabra: "可", pinyin: "ke3", significado: "sumamente" },
  { id: "hz000805", palabra: "多", pinyin: "duo1", significado: "mucho" },
  { id: "hz000806", palabra: "网球", pinyin: "wa3ng qiu2", significado: "tenis" },
  { id: "hz000807", palabra: "游泳", pinyin: "yo2u yo3ng", significado: "nadar" },
  { id: "hz000808", palabra: "滑冰", pinyin: "hua2 bi1ng", significado: "patinar" },
  { id: "hz000809", palabra: "以后", pinyin: "yi3 ho4u", significado: "en adelante" },
  { id: "hz000810", palabra: "会", pinyin: "hui4", significado: "saber" },
  { id: "hz000811", palabra: "只", pinyin: "zhi3", significado: "sólo" },
  { id: "hz000812", palabra: "游", pinyin: "yo2u", significado: "nadar" },
  { id: "hz000813", palabra: "愿意", pinyin: "yua4n yi4", significado: "querer" },
  { id: "hz000814", palabra: "当", pinyin: "da1ng", significado: "ser" },
  { id: "hz000815", palabra: "教练", pinyin: "jia4o lia4n", significado: "entrenador" },
  { id: "hz000820", palabra: "流利", pinyin: "liu2 li4", significado: "fluido" },
  { id: "hz000821", palabra: "整齐", pinyin: "zhe3ng qi2", significado: "ordenado" },
  { id: "hz000822", palabra: "旅行", pinyin: "lv3 xi2ng", significado: "viajar" },
  { id: "hz000823", palabra: "见面", pinyin: "jia4n mia4n", significado: "entrevistarse" },
  { id: "hz000826", palabra: "以前", pinyin: "yi3 qia2n", significado: "antes" },
  { id: "hz000827", palabra: "过", pinyin: "guo0", significado: "alguna vez" },
  { id: "hz000828", palabra: "听说", pinyin: "ti1ng shu1o", significado: "haber oído decir" },
  { id: "hz000829", palabra: "有名", pinyin: "yo3u mi2ng", significado: "famoso" },
  { id: "hz000830", palabra: "烤鸭", pinyin: "ka3o ya1", significado: "pato laqueado" },
  { id: "hz000831", palabra: "店", pinyin: "dia4n", significado: "restaurante" },
  { id: "hz000832", palabra: "已经", pinyin: "yi3 ji1ng", significado: "ya" },
  { id: "hz000833", palabra: "历史", pinyin: "li4 shi3", significado: "historia" },
  { id: "hz000834", palabra: "座位", pinyin: "zuo4 we4i", significado: "asiento" },
  { id: "hz000835", palabra: "提前", pinyin: "ti2 qia2n", significado: "previamente" },
  { id: "hz000836", palabra: "预订", pinyin: "yu4 di4ng", significado: "reservar" },
  { id: "hz000837", palabra: "几", pinyin: "ji3", significado: "varios" },
  { id: "hz000838", palabra: "今天", pinyin: "ji1n tia1n", significado: "hoy" },
  { id: "hz000839", palabra: "请客", pinyin: "qi3ng ke4", significado: "invitar" },
  { id: "hz000840", palabra: "点菜", pinyin: "dia3n ca4i", significado: "pedir de comer" },
  { id: "hz000841", palabra: "要", pinyin: "ya4o", significado: "querer" },
  { id: "hz000842", palabra: "啤酒", pinyin: "pi2 jiu3", significado: "cerveza" },
  { id: "hz000843", palabra: "杯", pinyin: "be1i", significado: "vaso" },
  { id: "hz000844", palabra: "矿泉水", pinyin: "kua4ng qua2n shui3", significado: "agua mineral" },
  { id: "hz000845", palabra: "只", pinyin: "zhi1", significado: "clasif. Animales" },
  { id: "hz000846", palabra: "瓶", pinyin: "pi2ng", significado: "botella" },
  { id: "hz000847", palabra: "全聚德", pinyin: "qua2n ju4 de2", significado: "Quanjude" },
  { id: "hz000850", palabra: "葡萄酒", pinyin: "pu2 ta2o jiu3", significado: "vino" },
  { id: "hz000851", palabra: "白酒", pinyin: "ba2i jiu3", significado: "licor" },
  { id: "hz000855", palabra: "杯子", pinyin: "be1i zi0", significado: "vaso" },
  { id: "hz000856", palabra: "饱", pinyin: "ba3o", significado: "lleno" },
  { id: "hz000857", palabra: "鸡蛋", pinyin: "ji1 da4n", significado: "huevo (de gallina)" },
  { id: "hz000859", palabra: "图书馆", pinyin: "tu2 shu1 gua3n", significado: "biblioteca" },
  { id: "hz000860", palabra: "找", pinyin: "zha3o", significado: "buscar" },
  { id: "hz000861", palabra: "报", pinyin: "ba3o", significado: "periódico" },
  { id: "hz000862", palabra: "招聘", pinyin: "zha1 pi4n", significado: "solictar (trabajo)" },
  { id: "hz000863", palabra: "广告", pinyin: "gua3ng ga3o", significado: "anuncio" },
  { id: "hz000864", palabra: "公司", pinyin: "go1ng si1", significado: "compañía" },
  { id: "hz000865", palabra: "需要", pinyin: "xu1 ya4o", significado: "necesitar" },
  { id: "hz000866", palabra: "懂", pinyin: "do3ng", significado: "entender" },
  { id: "hz000867", palabra: "听", pinyin: "ti1ng", significado: "escuchar" },
  { id: "hz000868", palabra: "广播", pinyin: "gua3ng bo1", significado: "radiodifusión" },
  { id: "hz000869", palabra: "简历", pinyin: "jia3n li4", significado: "curriculum vitae" },
  { id: "hz000870", palabra: "准备", pinyin: "zhu3n be4i", significado: "preparar" },
  { id: "hz000871", palabra: "经理", pinyin: "ji1ng li3", significado: "gerente" },
  { id: "hz000872", palabra: "先", pinyin: "xia1n", significado: "antes que nada" },
  { id: "hz000873", palabra: "面试", pinyin: "mia4n shi4", significado: "entrevistar" },
  { id: "hz000874", palabra: "一下", pinyin: "yi2 xia4", significado: "una vez" },
  { id: "hz000875", palabra: "中文", pinyin: "zho1ng we2n", significado: "lengua china" },
  { id: "hz000876", palabra: "杂志", pinyin: "za2 zhi4", significado: "revista" },
  { id: "hz000877", palabra: "小说", pinyin: "xia3o shuo1", significado: "novela" },
  { id: "hz000878", palabra: "画报", pinyin: "hua4 ba4o", significado: "revista ilustrada" },
  { id: "hz000879", palabra: "电视", pinyin: "dia4n shi4", significado: "televisión" },
  { id: "hz000883", palabra: "考", pinyin: "ka3o", significado: "examinar" },
  { id: "hz000884", palabra: "成绩", pinyin: "che2ng ji4", significado: "éxito, resultado" },
  { id: "hz000888", palabra: "复习", pinyin: "fu4 xi2", significado: "repasar" },
  { id: "hz000889", palabra: "多", pinyin: "duo1", significado: "¿cuánto?" },
  { id: "hz000890", palabra: "长", pinyin: "cha2ng", significado: "largo" },
  { id: "hz000891", palabra: "谈话", pinyin: "ta2n hua4", significado: "conversar" },
  { id: "hz000892", palabra: "用", pinyin: "yo4ng", significado: "usar" },
  { id: "hz000893", palabra: "硬件", pinyin: "yi4ng jia4n", significado: "hardware" },
  { id: "hz000894", palabra: "软件", pinyin: "rua3n jia4n", significado: "software" },
  { id: "hz000895", palabra: "大学", pinyin: "da4 xue2", significado: "universidad" },
  { id: "hz000896", palabra: "毕业", pinyin: "bi4 ye4", significado: "graduarse" },
  { id: "hz000897", palabra: "计算机", pinyin: "ji4 sua4n ji1", significado: "ordenador" },
  { id: "hz000898", palabra: "专业", pinyin: "zhua1n ye4", significado: "carrera" },
  { id: "hz000899", palabra: "秘书", pinyin: "mi4 shu1", significado: "secretario" },
  { id: "hz000900", palabra: "合同", pinyin: "he2 tong0", significado: "contrato" },
  { id: "hz000901", palabra: "同意", pinyin: "to2ng yi4", significado: "estar de acuerdo" },
  { id: "hz000902", palabra: "通知", pinyin: "to1ng zhi1", significado: "aviso, avisar" },
  { id: "hz000903", palabra: "职员", pinyin: "zhi2 yua2n", significado: "empleado" },
  { id: "hz000904", palabra: "英文", pinyin: "yi1ng we2n", significado: "lengua inglesa" },
  { id: "hz000905", palabra: "美国", pinyin: "me3i guo2", significado: "EEUU" },
  { id: "hz000906", palabra: "小时", pinyin: "xia3o shi2", significado: "hora" },
  { id: "hz000907", palabra: "服务", pinyin: "fu2 wu4", significado: "servir" },
  { id: "hz000908", palabra: "接着", pinyin: "jie1 zhe0", significado: "continuar" },
  { id: "hz000909", palabra: "继续", pinyin: "ji4 xu4", significado: "seguir" },
  { id: "hz000916", palabra: "饭店", pinyin: "fa4n dia4n", significado: "hotel" },
  { id: "hz000917", palabra: "房间", pinyin: "fa3ng jia1n", significado: "habitación" },
  { id: "hz000920", palabra: "住", pinyin: "zhu4", significado: "ocupar, usar" },
  { id: "hz000921", palabra: "离", pinyin: "li2", significado: "de" },
  { id: "hz000922", palabra: "机场", pinyin: "ji1 cha3ng", significado: "aeropuerto" },
  { id: "hz000923", palabra: "远", pinyin: "yua3n", significado: "lejano, lejos" },
  { id: "hz000924", palabra: "从 . . 到", pinyin: "co2ng 0 0 da4o", significado: "desde .. hasta" },
  { id: "hz000925", palabra: "公里", pinyin: "go1ng li3", significado: "kilómetro" },
  { id: "hz000926", palabra: "市中心", pinyin: "shi4 zho1n xi1n", significado: "centro urbano" },
  { id: "hz000927", palabra: "步行", pinyin: "bu4 xi2ng", significado: "caminar" },
  { id: "hz000928", palabra: "分钟", pinyin: "fe1n zho1ng", significado: "minuto" },
  { id: "hz000929", palabra: "左右", pinyin: "zuo3 yo4u", significado: "aproximadamente" },
  { id: "hz000930", palabra: "安排", pinyin: "a1n pa2i", significado: "arreglar" },
  { id: "hz000931", palabra: "发", pinyin: "fa1", significado: "enviar" },
  { id: "hz000932", palabra: "传真", pinyin: "chua2n zhe1n", significado: "fax" },
  { id: "hz000933", palabra: "西安", pinyin: "xi1 a1n", significado: "Xian" },
  { id: "hz000934", palabra: "开", pinyin: "ka1i", significado: "conducir" },
  { id: "hz000935", palabra: "车", pinyin: "che1", significado: "vehículo" },
  { id: "hz000936", palabra: "去年", pinyin: "qu4 nia2n", significado: "el año pasado" },
  { id: "hz000937", palabra: "套间", pinyin: "ta4o jia1n", significado: "apartamento" },
  { id: "hz000938", palabra: "办理", pinyin: "ba4n li3", significado: "arreglar, tramitar" },
  { id: "hz000939", palabra: "车站", pinyin: "che1 zha4n", significado: "estación de vehículos" },
  { id: "hz000940", palabra: "出租汽车", pinyin: "chu1 zu1 qi4 che1", significado: "taxi" },
  { id: "hz000941", palabra: "电车", pinyin: "dia4n che1", significado: "tranvía" },
  { id: "hz000942", palabra: "成", pinyin: "che2ng", significado: "ciudad" },
  { id: "hz000943", palabra: "出发", pinyin: "chu1 fa1", significado: "partir" },
  { id: "hz000944", palabra: "方向", pinyin: "fa1ng xia4ng", significado: "dirección" },
  { id: "hz000945", palabra: "照片", pinyin: "zha4o pia4n", significado: "foto" },
  { id: "hz000946", palabra: "照", pinyin: "zha4o", significado: "sacar, tomar" },
  { id: "hz000947", palabra: "男朋友", pinyin: "na2n pe2ng you0", significado: "novio" },
  { id: "hz000948", palabra: "坐", pinyin: "zuo4", significado: "tomar (vehiculo)" },
  { id: "hz000949", palabra: "火车", pinyin: "huo3 che1", significado: "tren" },
  { id: "hz000950", palabra: "第", pinyin: "di4", significado: "prefijo numeral" },
  { id: "hz000951", palabra: "照相", pinyin: "zha4o xia4ng", significado: "fotografiar" },
  { id: "hz000952", palabra: "帅", pinyin: "shua4i", significado: "guapo" },
  { id: "hz000953", palabra: "嘛", pinyin: "ma0", significado: "partícula expletiva" },
  { id: "hz000954", palabra: "为什么", pinyin: "we4i she2n me0", significado: "por qué" },
  { id: "hz000955", palabra: "努力", pinyin: "nu3 li4", significado: "aplicado" },
  { id: "hz000956", palabra: "上海", pinyin: "sha4ng ha3i", significado: "Shanghai" },
  { id: "hz000957", palabra: "外滩", pinyin: "wa4i ta1n", significado: "Waitan" },
  { id: "hz000958", palabra: "骑", pinyin: "qi4", significado: "montar" },
  { id: "hz000959", palabra: "自行车", pinyin: "zi4 xi2ng che1", significado: "bicicleta" },
  { id: "hz000960", palabra: "摩托车", pinyin: "mo2 tuo1 che1", significado: "motocicleta" },
  { id: "hz000961", palabra: "三轮车", pinyin: "sa1n lu2n che1", significado: "triciclo" },
  { id: "hz000962", palabra: "姑娘", pinyin: "gu1 niang0", significado: "chica" },
  { id: "hz000963", palabra: "关系", pinyin: "gua1n xi0", significado: "relacion/relacionarse" },
  { id: "hz000964", palabra: "关心", pinyin: "gua1n xi1n", significado: "interesarse por" },
  { id: "hz000965", palabra: "家庭", pinyin: "jia1 ti2ng", significado: "familia" },
  { id: "hz000966", palabra: "说话", pinyin: "shuo1 hua4", significado: "hablar" },
  { id: "hz000967", palabra: "做", pinyin: "zuo4", significado: "hacer" },
  { id: "hz000968", palabra: "梦", pinyin: "me4ng", significado: "soñar, sueño" },
  { id: "hz000969", palabra: "怒朋友", pinyin: "nu3 pe2ng you0", significado: "novia" },
  { id: "hz000970", palabra: "狗", pinyin: "go3u", significado: "perro" },
  { id: "hz000971", palabra: "叫", pinyin: "jia4o", significado: "llamar" },
  { id: "hz000972", palabra: "养", pinyin: "ya3ng", significado: "criar" },
  { id: "hz000973", palabra: "它", pinyin: "ta1", significado: "ello" },
  { id: "hz000974", palabra: "好像", pinyin: "ha3o xia4ng", significado: "al parecer" },
  { id: "hz000975", palabra: "没错", pinyin: "me2i cuo4", significado: "exacto" },
  { id: "hz000976", palabra: "极了", pinyin: "ji2 le0", significado: "sufijo ísimo" },
  { id: "hz000977", palabra: "这么", pinyin: "zhe4 me0", significado: "tal, tan" },
  { id: "hz000978", palabra: "汤", pinyin: "ta1ng", significado: "sopa" },
  { id: "hz000979", palabra: "这样", pinyin: "zhe4 ya4ng", significado: "así" },
  { id: "hz000980", palabra: "下班", pinyin: "xia4 ba1n", significado: "fin del trabajo" },
  { id: "hz000981", palabra: "结婚", pinyin: "jie2 hu1n", significado: "casarse" },
  { id: "hz000982", palabra: "久", pinyin: "jiu3", significado: "largo tiempo" },
  { id: "hz000983", palabra: "小看", pinyin: "xia3o ka4n", significado: "menospreciar" },
  { id: "hz000984", palabra: "露", pinyin: "lo4u", significado: "exhibir" },
  { id: "hz000985", palabra: "一手", pinyin: "yi4 sho3u", significado: "habilidad" },
  { id: "hz000986", palabra: "定", pinyin: "di4ng", significado: "quedar" },
  { id: "hz000987", palabra: "名字", pinyin: "Mi2ng zi3", significado: "Mingzi" },
  { id: "hz000989", palabra: "认识", pinyin: "re4n shi0", significado: "conocer" },
  { id: "hz000992", palabra: "快餐", pinyin: "kua4i ca1n", significado: "comida rápida" },
  { id: "hz000993", palabra: "餐馆", pinyin: "ca1n gua3n", significado: "restaurante" },
  { id: "hz000994", palabra: "早餐", pinyin: "za3o ca1n", significado: "desayuno" },
  { id: "hz000995", palabra: "午餐", pinyin: "wu3 ca1n", significado: "almuerzo" },
  { id: "hz000996", palabra: "晚餐", pinyin: "wa3n ca1n", significado: "cena" },
  { id: "hz000997", palabra: "夜宵", pinyin: "ye4 xia1o", significado: "comida ligera (noche)" },
  { id: "hz000998", palabra: "早点", pinyin: "za30 dia3n", significado: "desayuno" },
  {
    id: "hz000999",
    palabra: "出差",
    pinyin: "chu1 cha1i",
    significado: "salir de viaje de negocios",
  },
  { id: "hz001000", palabra: "经常", pinyin: "ji1ng cha2ng", significado: "a menudo" },
  { id: "hz001001", palabra: "挺", pinyin: "ti3ng", significado: "muy" },
  { id: "hz001002", palabra: "辛苦", pinyin: "xi1n ku3", significado: "duro" },
  { id: "hz001003", palabra: "连。。也", pinyin: "lia2n 0 0 ye3", significado: "incluso" },
  { id: "hz001004", palabra: "周末", pinyin: "zho1u mo4", significado: "fin de semana" },
  { id: "hz001005", palabra: "休息", pinyin: "xiu1 xi0", significado: "descansar" },
  { id: "hz001006", palabra: "地", pinyin: "de0", significado: "partícula" },
  { id: "hz001007", palabra: "出来", pinyin: "chu1 la2i", significado: "salir" },
  { id: "hz001008", palabra: "回", pinyin: "hui2", significado: "regresar" },
  { id: "hz001009", palabra: "中午", pinyin: "zho1ng wu3", significado: "mediodía" },
  { id: "hz001010", palabra: "饭", pinyin: "fa4n", significado: "comida" },
  { id: "hz001011", palabra: "随便", pinyin: "sui2 bia4n", significado: "como sea" },
  { id: "hz001012", palabra: "一些", pinyin: "yi4 xie1", significado: "alguno que otro" },
  { id: "hz001013", palabra: "快餐", pinyin: "kua4 ca1n", significado: "comida rápida" },
  { id: "hz001014", palabra: "什么", pinyin: "she2n me0", significado: "cosas por el estilo" },
  { id: "hz001015", palabra: "注意", pinyin: "zhu4 yi4", significado: "tener cuidado con" },
  { id: "hz001016", palabra: "干", pinyin: "ga4n", significado: "hacer" },
  { id: "hz001017", palabra: "孩子", pinyin: "ha2i zi0", significado: "hijo" },
  { id: "hz001018", palabra: "带", pinyin: "da4i", significado: "llevar" },
  { id: "hz001019", palabra: "出去", pinyin: "chu1 qu4", significado: "salir" },
  { id: "hz001020", palabra: "不过", pinyin: "bu2 guo4", significado: "pero" },
  { id: "hz001021", palabra: "爱人", pinyin: "a4i ren0", significado: "marido/mujer" },
  {
    id: "hz001022",
    palabra: "游乐园",
    pinyin: "yo2u le4 yua3n",
    significado: "Parque de atracciones",
  },
  { id: "hz001023", palabra: "自己", pinyin: "zi4 ji3", significado: "uno mismo" },
  {
    id: "hz001024",
    palabra: "痛快",
    pinyin: "to4ng kua4i",
    significado: "contento",
  },
  { id: "hz001025", palabra: "轻松", pinyin: "qi1ng so1ng", significado: "cómodo" },
  { id: "hz001026", palabra: "忘", pinyin: "wa4ng", significado: "olvidar" },
  { id: "hz001027", palabra: "静", pinyin: "ji4ng", significado: "tranquilo" },
  { id: "hz001028", palabra: "安静", pinyin: "a1n ji4ng", significado: "tranquilo, silencioso" },
  { id: "hz001029", palabra: "北边", pinyin: "be3i bian0", significado: "norte" },
  { id: "hz001030", palabra: "必须", pinyin: "bi4 xu1", significado: "tener que" },
  { id: "hz001031", palabra: "电影", pinyin: "dia4n yi3ng", significado: "cine, película" },
  { id: "hz001032", palabra: "放假", pinyin: "fa4ng jia4", significado: "tener vacaciones" },
  { id: "hz001033", palabra: "高兴", pinyin: "ga1o xi4ng", significado: "contento" },
  { id: "hz001034", palabra: "不要", pinyin: "bu2 ya4o", significado: "no" },
  { id: "hz001035", palabra: "得到", pinyin: "de2 da4o", significado: "lograr" },
  { id: "hz001036", palabra: "曾经", pinyin: "ce2ng ji1ng", significado: "acción pasada" },
  { id: "hz001037", palabra: "熟悉", pinyin: "shu2 xi1", significado: "conocer bien" },
  { id: "hz001038", palabra: "敢", pinyin: "ga3n", significado: "atreverse" },
  { id: "hz001039", palabra: "到处", pinyin: "da4o chu4", significado: "por todas partes" },
  { id: "hz001040", palabra: "跑", pinyin: "pa3o", significado: "correr" },
  { id: "hz001041", palabra: "给", pinyin: "ge3i", significado: "dar" },
  { id: "hz001042", palabra: "印象", pinyin: "yi4n xia4ng", significado: "impresión" },
  { id: "hz001043", palabra: "如何", pinyin: "ru2 he2", significado: "qué, como" },
  { id: "hz001044", palabra: "深", pinyin: "she1n", significado: "profundo" },
  { id: "hz001045", palabra: "感情", pinyin: "ga3n qi2ng", significado: "sentimiento" },
  { id: "hz001046", palabra: "所以", pinyin: "suo3 yi3", significado: "por eso" },
  { id: "hz001047", palabra: "变化", pinyin: "bia4n hua4", significado: "cambio" },
  { id: "hz001048", palabra: "一样", pinyin: "yi2 ya4ng", significado: "igual" },
  { id: "hz001049", palabra: "地方", pinyin: "di4 fang0", significado: "sitio" },
  { id: "hz001050", palabra: "认识", pinyin: "re4n shi0", significado: "conocer" },
  { id: "hz001051", palabra: "汽车", pinyin: "qi4 che1", significado: "automovil" },
  { id: "hz001052", palabra: "越来越", pinyin: "yue4 la2i yue4", significado: "cada vez mas" },
  { id: "hz001053", palabra: "热情", pinyin: "re4 qi2ng", significado: "cordial" },
  { id: "hz001054", palabra: "穿着", pinyin: "chua1n zhuo2", significado: "indumentaria" },
  { id: "hz001055", palabra: "打扮", pinyin: "da3 ban0", significado: "ataviarse" },
  { id: "hz001056", palabra: "变", pinyin: "bia4n", significado: "cambiar" },
  { id: "hz001057", palabra: "时髦", pinyin: "shi2 ma2o", significado: "a la moda" },
  { id: "hz001058", palabra: "菲利普", pinyin: "fe1i li4 pu3", significado: "Felipe" },
  { id: "hz001059", palabra: "水平", pinyin: "shui3 pi2ng", significado: "nivel" },
  { id: "hz001060", palabra: "高", pinyin: "ga1o", significado: "alto" },
  { id: "hz001061", palabra: "同情", pinyin: "to2ng qi2ng", significado: "simpatizar" },
  { id: "hz001062", palabra: "从前", pinyin: "co2ng qia2n", significado: "antes" },
];
